<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="pl">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="139"/>
        <source>Abort</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="184"/>
        <source>Wrong value for camera orientation</source>
        <translation>Zła wartość dla parametru położenia aparatu</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="184"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Nie można zmienić położenia aparatu na &apos;dobrane przez użytkownika&apos; póki w trybie &apos;mozaika&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="198"/>
        <source>Wrong value for lens type</source>
        <translation>Zła wartość w polu &apos;rodzaj obiektywu&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="198"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Nie można zmienić rodzaju obiektywu na &apos;rybie oko&apos; póki w trybie &apos;mozaika&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="242"/>
        <source>Choose Data Storage dir</source>
        <translation>Wskaz folder zapisu danych</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="346"/>
        <source>Here goes the title</source>
        <translation>Wpisz tytuł</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="350"/>
        <source>Here goes the location</source>
        <translation>Wpisz region</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="354"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Wygenerowane przez Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="110"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="119"/>
        <source>Exception</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="92"/>
        <source>Info</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="319"/>
        <source>Manual speed set to slow</source>
        <translation>Prędkość ręczna - niska</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="335"/>
        <source>Manual speed set to normal</source>
        <translation>Prędkość ręczna - średnia</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="341"/>
        <source>Manual speed set to fast</source>
        <translation>Prędkość ręczną ustawiono na wysoką</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="347"/>
        <source>About to Quit</source>
        <translation>Wyjście za chwile</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="347"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Jesteś pewien, że chcesz zamknąć Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="363"/>
        <source>Import Preset File</source>
        <translation>Wczytaj plik ustawień</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="363"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>Pliki XML (*.xml);;Wszystkie pliki (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="372"/>
        <source>Load Style Sheet</source>
        <translation>Wczytaj arkusz stylów</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="372"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>Pliki CSS (*.css);;Wszystkie pliki (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="390"/>
        <source>Yaw - limit set</source>
        <translation>Yaw - limit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="396"/>
        <source>Yaw + limit set</source>
        <translation>Yaw + limit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="402"/>
        <source>Pitch + limit set</source>
        <translation>Pitch + limit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="408"/>
        <source>Pitch - limit set</source>
        <translation>Pitch - limit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="413"/>
        <source>Limits cleared</source>
        <translation>Limity usunięto</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="444"/>
        <source>Operation aborted</source>
        <translation>Operacje przerwano</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="434"/>
        <source>Goto initial position...</source>
        <translation>Przejdź do pozycji pierwotnej...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="448"/>
        <source>Initial position reached</source>
        <translation>Pozycję pierwotną osiągnięto</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="623"/>
        <source>Field of view set to user value</source>
        <translation>Pole widzenia ustawiono na wartość dobraną przez użytkownika</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="634"/>
        <source>Number of pictures set to user value</source>
        <translation>Liczbę zdjęć ustawiono na wartość dobraną przez użytkownika</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="656"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Trwa otwieranie okna konfiguracji, proszę czekać...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="689"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Trwa otwieranie panelu strzelania, proszę czekać...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="735"/>
        <source>Can&apos;t import preset file</source>
        <translation>Błąd przy importowaniu pliku ustawień</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="751"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Błąd przy ładowaniu arkuszu stylów</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="567"/>
        <source>Reference set at current position</source>
        <translation>Obecne położenie ustawiono jako położenie odniesienia</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="438"/>
        <source>Please wait...</source>
        <translation>Proszę czekać...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="438"/>
        <source>Goto initial position</source>
        <translation>Przejdź do pozycji pierwotnej</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="417"/>
        <source>Goto reference position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="419"/>
        <source>Goto reference position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="429"/>
        <source>Reference position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="639"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="814"/>
        <source>Starting connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="837"/>
        <source>Connection started</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="842"/>
        <source>Connection failed to start</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="854"/>
        <source>Stopping connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="867"/>
        <source>Connection stopped</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="511"/>
        <source>Yaw corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="519"/>
        <source>Pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="535"/>
        <source>Yaw corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="543"/>
        <source>Pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="503"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="527"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="406"/>
        <source>Mosaic</source>
        <translation>Mozaika</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="420"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="436"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="705"/>
        <source>Real overlap (%)</source>
        <translation>Prawdziwe zachodzenie na siebie (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="768"/>
        <source>Resolution (px)</source>
        <translation>Rozdzielczość (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="832"/>
        <source>Preset</source>
        <translation>Ustawienia</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="851"/>
        <source>Name</source>
        <translation>Nazwa</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="895"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Upewnij się, że wybrane ustawienia są kompatybilne z Twoim aparatem i rozmiarem obiektywu (kolizja).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Przesuń</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="329"/>
        <source>Configure...</source>
        <translation>Ustaw...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="352"/>
        <source>Shoot...</source>
        <translation>Strzelaj...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="937"/>
        <source>File</source>
        <translation>Plik</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="946"/>
        <source>Hardware</source>
        <translation>Sprzęt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="950"/>
        <source>Set Limit</source>
        <translation>Ustaw limit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="973"/>
        <source>Help</source>
        <translation>Pomoc</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="997"/>
        <source>Quit</source>
        <translation>Wyjdź</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1009"/>
        <source>Import Preset File...</source>
        <translation>Wczytaj plik ustawień...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1017"/>
        <source>Connect...</source>
        <translation>Połącz się...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1141"/>
        <source>Clear Limits</source>
        <translation>Usuń limity</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1026"/>
        <source>Yaw -</source>
        <translation>Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1035"/>
        <source>Yaw +</source>
        <translation>Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1044"/>
        <source>Pitch +</source>
        <translation>Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1053"/>
        <source>Pitch -</source>
        <translation>Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1062"/>
        <source>Manual</source>
        <translation>Podręcznik</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1071"/>
        <source>View Log...</source>
        <translation>Zobacz log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1080"/>
        <source>About Papywizard</source>
        <translation>O Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1089"/>
        <source>About Qt</source>
        <translation>O QT</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1098"/>
        <source>Load Style Sheet...</source>
        <translation>Wczytaj arkusz stylów...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1116"/>
        <source>Goto Initial...</source>
        <translation>Pozycja pierwotna...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1107"/>
        <source>Goto Reference...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1125"/>
        <source>Plugins...</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="583"/>
        <source>Total fov (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="644"/>
        <source>Nb picts</source>
        <translation>Ilość zdjęć</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="455"/>
        <source>Corner 0 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="522"/>
        <source>Corner 1 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1136"/>
        <source>Suspend Spy</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1150"/>
        <source>Set Reference</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1159"/>
        <source>Trigger Shutter</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="222"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Błąd przy skanowaniu Bluetooth</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="277"/>
        <source>Step</source>
        <translation>Krok</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="348"/>
        <source>Resume</source>
        <translation>Wznów</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="361"/>
        <source>Pause</source>
        <translation>Pauza</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="352"/>
        <source>Paused</source>
        <translation>Wstrzymane</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="373"/>
        <source>Finished</source>
        <translation>Zakończono</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="375"/>
        <source>Canceled</source>
        <translation>Anulowano</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="377"/>
        <source>Failed</source>
        <translation>Nie powiodło się</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="384"/>
        <source>Waiting</source>
        <translation>Poczekaj</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="430"/>
        <source>Moving</source>
        <translation>Namierzam</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="432"/>
        <source>Stabilization</source>
        <translation>Stabilizacja</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="434"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="437"/>
        <source>Shutter - Picture</source>
        <translation>Migawka - Obraz</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="579"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="379"/>
        <source>Finish</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="478"/>
        <source>Idle</source>
        <translation>Bezczynny</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="583"/>
        <source>Shutter failed while mirror locking up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="598"/>
        <source>Shutter failed while shooting</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="101"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="130"/>
        <source>Question</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>abstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="61"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>axisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="60"/>
        <source>Low limit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="61"/>
        <source>High limit</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Konfiguracja</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Strzelam</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Położenie głowicy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>góra</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="193"/>
        <source>left</source>
        <translation>lewo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="188"/>
        <source>right</source>
        <translation>prawo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>dół</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Położenie aparatu</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>portret</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>krajobraz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>dobrane</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Opóźnienie stabilizacyjne</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="204"/>
        <source>Mosaic</source>
        <translation>Mozaika</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="212"/>
        <source>Overlap</source>
        <translation>Zachodzenie</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>Start from</source>
        <translation>Zacznij od</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="290"/>
        <source>Initial direction</source>
        <translation>Pierwotny kierunek</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="307"/>
        <source>yaw</source>
        <translation>yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="312"/>
        <source>pitch</source>
        <translation>pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="320"/>
        <source>CR</source>
        <translation>Powrót karetki</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="355"/>
        <source>rectilinear</source>
        <translation>prostoliniowy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="360"/>
        <source>fisheye</source>
        <translation>rybie oko</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="680"/>
        <source>Data</source>
        <translation>Dane</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="688"/>
        <source>Data directory</source>
        <translation>Katalog danych</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="704"/>
        <source>Data file</source>
        <translation>Plik danych</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="904"/>
        <source>Enable</source>
        <translation>Włącz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="743"/>
        <source>Title</source>
        <translation>Tytuł</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="772"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="801"/>
        <source>Comment</source>
        <translation>Komentarz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="844"/>
        <source>Timer</source>
        <translation>Samowyzwalacz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="855"/>
        <source>Start after</source>
        <translation>Startuj po</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="878"/>
        <source>Repeat</source>
        <translation>Powtórz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="914"/>
        <source>Repeat every</source>
        <translation>Powtarzaj co</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="982"/>
        <source>Misc</source>
        <translation>Różne</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="990"/>
        <source>Logger level</source>
        <translation>Poziom Loggera</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1007"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1012"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1017"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1022"/>
        <source>warning</source>
        <translation>warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1027"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1032"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1037"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="416"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Matryca (współczynnik 35mm)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="381"/>
        <source>Sensor resolution</source>
        <translation>Rozdzielczość matrycy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="368"/>
        <source>Optical multiplier</source>
        <translation>Mnożnik optyczny</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="330"/>
        <source>Camera/lens</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="338"/>
        <source>Lens (type, focal)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="528"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="536"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="549"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="600"/>
        <source>Configure...</source>
        <translation>Ustaw...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="576"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="267"/>
        <source>top-left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="272"/>
        <source>top-right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>bottom-left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>bottom-right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="972"/>
        <source>Reverse direction before repeat</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="171"/>
        <source>Pitch arm side</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1045"/>
        <source>Shooting counter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1077"/>
        <source>Show</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>counterDialog</name>
    <message>
        <location filename="papywizard/view/ui/counterDialog.ui" line="14"/>
        <source>Counter</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>dslrRemoteProPlugins</name>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="89"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="91"/>
        <source>Camera</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="92"/>
        <source>Output directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="93"/>
        <source>Choose output directory...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="94"/>
        <source>File name prefix</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="95"/>
        <source>Camera exposure
compensation list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="84"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>eosUtilityPlugins</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="110"/>
        <source>new</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="113"/>
        <source>far</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="119"/>
        <source>medium</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="109"/>
        <source>old</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="114"/>
        <source>near</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="118"/>
        <source>small</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="120"/>
        <source>large</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="84"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>EOS Utility version</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="90"/>
        <source>Bracketing type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="93"/>
        <source>Bulb</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>Enable</source>
        <translation>Włącz</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="95"/>
        <source>Base exposure</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="99"/>
        <source>Direction</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="100"/>
        <source>Step</source>
        <translation>Krok</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="101"/>
        <source>Step count</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="102"/>
        <source>Nb picts</source>
        <translation>Ilość zdjęć</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="89"/>
        <source>Bracketing step</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>genericTetheredPlugins</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="80"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="81"/>
        <source>Mirror lockup command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="82"/>
        <source>Shoot command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="83"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="85"/>
        <source>Params</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="86"/>
        <source>Parameter &apos;p0&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="88"/>
        <source>Parameter &apos;p2&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="89"/>
        <source>Parameter &apos;p3&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="90"/>
        <source>Parameter &apos;p4&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="87"/>
        <source>Parameter &apos;p1&apos;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>gphotoBracketPlugins</name>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="93"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="94"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="95"/>
        <source>gphoto2 (gphoto2);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="96"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="97"/>
        <source>Bracketing step</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="98"/>
        <source>Exposure bias</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="99"/>
        <source>Resulting Ev list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="102"/>
        <source>Advanced</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="103"/>
        <source>Bracketing nb picts (+)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="104"/>
        <source>Bracketing step (+)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="105"/>
        <source>Bracketing nb picts (-)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="106"/>
        <source>Bracketing step (-)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="108"/>
        <source>Download</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="109"/>
        <source>Enable</source>
        <translation>Włącz</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="110"/>
        <source>Download directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="111"/>
        <source>Choose download directory...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="113"/>
        <source>Download after</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="114"/>
        <source>Each shot</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="115"/>
        <source>Bracketing sequence</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="116"/>
        <source>Delete camera picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>O programie Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>Ogólne</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard jest to program do kontroli głowicy panoramicznej, głównie stworzony do modelu Merlin/Orion ale współpracuje również z innymi głowicami astronomicznymi.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Podziękowania</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="190"/>
        <source>License</source>
        <translation>Licencja</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="196"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.￼

￼As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.￼

￼In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

￼The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lee Jeongyun (Gphoto Bracket plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (gnu/linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2010 Frédéric Mantegazza</source>
        <translation>© 2007-2010 Frédéric Mantegazza</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="14"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="145"/>
        <source>Clear log</source>
        <translation>Wyczyść logi</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="152"/>
        <source>Save log</source>
        <translation>Zapisz log</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Plugins selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>merlinOrionPlugins</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="83"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="84"/>
        <source>Alternate drive</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="86"/>
        <source>Inertia angle</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="85"/>
        <source>Alternate drive angle</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation>Ilość Zdjęć</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation>Ilość zdjęć</translation>
    </message>
</context>
<context>
    <name>nkRemotePlugins</name>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="84"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="89"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="91"/>
        <source>Camera</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="92"/>
        <source>Choose output directory...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="93"/>
        <source>File name prefix</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="94"/>
        <source>Camera exposure
compensation list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="233"/>
        <source>Output directory</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>panoduinoPlugins</name>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="120"/>
        <source>forward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="105"/>
        <source>Servo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="107"/>
        <source>Direction</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="109"/>
        <source>Neutral position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="121"/>
        <source>reverse</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="102"/>
        <source>Speed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="103"/>
        <source>Acceleration</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="106"/>
        <source>Channel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="108"/>
        <source>Angle for 1ms</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="112"/>
        <source>Shutter on</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="113"/>
        <source>Shutter off</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="110"/>
        <source>Additional delay</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pixOrbPlugins</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="82"/>
        <source>Speed index</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="84"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="85"/>
        <source>Axis with break</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="86"/>
        <source>Axis accuracy</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="26"/>
        <source>Plugin dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="46"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pluginsDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>Adres urządzenia Bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="212"/>
        <source>Serial port</source>
        <translation>Port szeregowy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="241"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="286"/>
        <source>Choose...</source>
        <translation>Wybierz...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="296"/>
        <source>Communication</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="304"/>
        <source>Timeout</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="342"/>
        <source>Retry</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pluginsStatusDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="14"/>
        <source>Plugins Status</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="49"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="65"/>
        <source>Init</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="81"/>
        <source>Connect</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Strzelam</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation>Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation>Bieżące</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation>Następne</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="341"/>
        <source>Idle</source>
        <translation>Bezczynny</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="428"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="514"/>
        <source>Data</source>
        <translation>Dane</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="543"/>
        <source>Timer</source>
        <translation>Samowyzwalacz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="569"/>
        <source>Step-by-step</source>
        <translation>Krok po kroku</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="602"/>
        <source>Start</source>
        <translation>Początek</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="631"/>
        <source>Pause</source>
        <translation>Pauza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="660"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
</context>
<context>
    <name>shutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="60"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="61"/>
        <source>Mirror lockup</source>
        <translation type="unfinished">Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="62"/>
        <source>Bulb</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="63"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="65"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="66"/>
        <source>Pulse width high</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="67"/>
        <source>Pulse width low</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>simulationPlugins</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="78"/>
        <source>Speed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="80"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="81"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="82"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>timelordPlugins</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="73"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="74"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="75"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="76"/>
        <source>LRD file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="77"/>
        <source>Choose LRD file...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="78"/>
        <source>LRD files (*.lrd);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation>Łączne Pole Widzenia</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation>Łączne pole widzenia</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ursaMinorBt2Plugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="102"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="103"/>
        <source>Enable</source>
        <translation>Włącz</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="104"/>
        <source>Pulse width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="105"/>
        <source>Maintain with shutter</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ursaMinorUsbPlugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="74"/>
        <source>Trigger line</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="75"/>
        <source>Line inverted</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
