<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="139"/>
        <source>Abort</source>
        <translation>Annuler</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="184"/>
        <source>Wrong value for camera orientation</source>
        <translation>Mauvaise valeur pour l&apos;orientation de l&apos;appareil</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="184"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Impossible de fixer l&apos;orientation de l&apos;appareil sur &apos;autre&apos; avec le mode &apos;mosaïque&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="198"/>
        <source>Wrong value for lens type</source>
        <translation>Mauvais type d&apos;objectif</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="198"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Impossible d&apos;utiliser un objectif type &apos;fisheye&apos; avec le mode &apos;mosaïque&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="242"/>
        <source>Choose Data Storage dir</source>
        <translation>Choisir répertoire stockage de données</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="346"/>
        <source>Here goes the title</source>
        <translation>Entrer le titre ici</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="350"/>
        <source>Here goes the location</source>
        <translation>Entrer les coordonnées ici</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="354"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Généré par Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="110"/>
        <source>Error</source>
        <translation>Erreur</translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="119"/>
        <source>Exception</source>
        <translation>Exception</translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="92"/>
        <source>Info</source>
        <translation>Info</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="316"/>
        <source>Manual speed set to slow</source>
        <translation>Vitesse manuelle fixée sur lente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="332"/>
        <source>Manual speed set to normal</source>
        <translation>Vitesse manuelle fixée sur normale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="338"/>
        <source>Manual speed set to fast</source>
        <translation>Vitesse manuelle fixée sur rapide</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="344"/>
        <source>About to Quit</source>
        <translation>Sur le point de quitter</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="344"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Êtes-vous sûr de vouloir quitter Papywizard ?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="360"/>
        <source>Import Preset File</source>
        <translation>Importer Fichier Preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="360"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>Fichiers XML (*.xml);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="369"/>
        <source>Load Style Sheet</source>
        <translation>Charger feuille de style</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="369"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>Fichiers CSS (*.css);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="387"/>
        <source>Yaw - limit set</source>
        <translation>Limite lacet - fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="393"/>
        <source>Yaw + limit set</source>
        <translation>Limite lacet + fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="399"/>
        <source>Pitch + limit set</source>
        <translation>Limite tangage + fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="405"/>
        <source>Pitch - limit set</source>
        <translation>Limite tangage - fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="410"/>
        <source>Limits cleared</source>
        <translation>Limites effacées</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="586"/>
        <source>Field of view set to user value</source>
        <translation>Angle de champ fixé à la valeur utilisateur</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="597"/>
        <source>Number of pictures set to user value</source>
        <translation>Nombre d&apos;images fixé à la valeur utilisateur</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="636"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre de configuration. Patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="670"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre de prise de vue. Patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="717"/>
        <source>Can&apos;t import preset file</source>
        <translation>Impossible d&apos;importer le fichier de preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="733"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Impossible de charger la feuille de style</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="530"/>
        <source>Reference set at current position</source>
        <translation>Référence fixée à la position courrante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="618"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre des plugins. Veuillez patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="794"/>
        <source>Starting connection. Please wait...</source>
        <translation>Démarrage de la connection. Merci de patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="818"/>
        <source>Connection started</source>
        <translation>Connection établie</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="823"/>
        <source>Connection failed to start</source>
        <translation>Problème de connection</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="835"/>
        <source>Stopping connection. Please wait...</source>
        <translation>Arrêt de la connection. Merci de patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="849"/>
        <source>Connection stopped</source>
        <translation>Connection arrétée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="474"/>
        <source>Yaw corner 0 set from current position</source>
        <translation>Coin 0 de lacet fixé depuis la position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="482"/>
        <source>Pitch corner 0 set from current position</source>
        <translation>Coin 0 de tangage fixé depuis la position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="498"/>
        <source>Yaw corner 1 set from current position</source>
        <translation>Coin 1 de lacet fixé depuis la position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="506"/>
        <source>Pitch corner 1 set from current position</source>
        <translation>Coin 1 de tangage fixé depuis la position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="466"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation>Coin 0 de lacet/tangage fixé depuis la position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="490"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation>Coin 1 de lacet/tangage fixé depuis la position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="602"/>
        <source>Opening goto dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre de déplacement. Patienter...</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="406"/>
        <source>Mosaic</source>
        <translation>Mosaïque</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="420"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="436"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="705"/>
        <source>Real overlap (%)</source>
        <translation>Recouvrement réel (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="768"/>
        <source>Resolution (px)</source>
        <translation>Résolution (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="832"/>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="851"/>
        <source>Name</source>
        <translation>Nom</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="895"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Attention à la compatibilité entre la présélection et la taille de l&apos;appareil et de l&apos;objectif (collision).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Déplacement</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="329"/>
        <source>Configure...</source>
        <translation>Configurer...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="352"/>
        <source>Shoot...</source>
        <translation>Prise de vue...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="937"/>
        <source>File</source>
        <translation>Fichier</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="957"/>
        <source>Hardware</source>
        <translation>Matériel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="961"/>
        <source>Set Limit</source>
        <translation>Fixer Limite</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="946"/>
        <source>Help</source>
        <translation>Aide</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="995"/>
        <source>Quit</source>
        <translation>Quitter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1007"/>
        <source>Import Preset File...</source>
        <translation>Importer Fichier Preset...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1015"/>
        <source>Connect...</source>
        <translation>Connecter...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1148"/>
        <source>Clear Limits</source>
        <translation>Effacer Limites</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1024"/>
        <source>Yaw -</source>
        <translation>Lacet -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1033"/>
        <source>Yaw +</source>
        <translation>Lacet +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1042"/>
        <source>Pitch +</source>
        <translation>Tangage +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1051"/>
        <source>Pitch -</source>
        <translation>Tangage -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1060"/>
        <source>Manual</source>
        <translation>Manuel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1069"/>
        <source>View Log...</source>
        <translation>Voir Log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1078"/>
        <source>About Papywizard</source>
        <translation>À propos de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1087"/>
        <source>About Qt</source>
        <translation>À propos de Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1096"/>
        <source>Load Style Sheet...</source>
        <translation>Charger feuille de style...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1114"/>
        <source>Goto Initial...</source>
        <translation>Vers Position Initiale...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1105"/>
        <source>Goto Reference...</source>
        <translation>Vers Position de Référence...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1132"/>
        <source>Plugins...</source>
        <translation>Plugins...</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="583"/>
        <source>Total fov (°)</source>
        <translation>Adc total (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="644"/>
        <source>Nb picts</source>
        <translation>Nb photos</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="455"/>
        <source>Corner 0 (°)</source>
        <translation>Coin 0 (°)</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="522"/>
        <source>Corner 1 (°)</source>
        <translation>Coin 1 (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1143"/>
        <source>Suspend Spy</source>
        <translation></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1157"/>
        <source>Set Reference</source>
        <translation>Fixe Référence</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1166"/>
        <source>Trigger Shutter</source>
        <translation>Prise de Vue</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1123"/>
        <source>Goto...</source>
        <translation>Vers position...</translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="210"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Impossible de scruter le bluetooth</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="277"/>
        <source>Step</source>
        <translation>Pas</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="348"/>
        <source>Resume</source>
        <translation>Reprendre</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="361"/>
        <source>Pause</source>
        <translation>Suspendre</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="352"/>
        <source>Paused</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="373"/>
        <source>Finished</source>
        <translation>Terminé</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="375"/>
        <source>Canceled</source>
        <translation>Annulé</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="377"/>
        <source>Failed</source>
        <translation>Échoué</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="384"/>
        <source>Waiting</source>
        <translation>Attente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="430"/>
        <source>Moving</source>
        <translation>Déplacement</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="432"/>
        <source>Stabilization</source>
        <translation>Stabilisation</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="434"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="437"/>
        <source>Shutter - Picture</source>
        <translation>Obturateur - Image</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="585"/>
        <source>Stop</source>
        <translation>Arrêter</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="379"/>
        <source>Finish</source>
        <translation>Terminer</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="478"/>
        <source>Idle</source>
        <translation>Repos</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="582"/>
        <source>Shutter failed while mirror locking up</source>
        <translation>L&apos;obturateur n&apos;a pas pur relever le mirroir</translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="597"/>
        <source>Shutter failed while shooting</source>
        <translation>L&apos;obturateur n&apos;a pas pu prendre la vue</translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Choisir programme...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>Fichiers EXE (*.exe);;Tous les fichiers (*)</translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="101"/>
        <source>Warning</source>
        <translation>Warning</translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="130"/>
        <source>Question</source>
        <translation>Question</translation>
    </message>
</context>
<context>
    <name>abstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="61"/>
        <source>Main</source>
        <translation>Principal</translation>
    </message>
</context>
<context>
    <name>axisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="60"/>
        <source>Low limit</source>
        <translation>Limite basse</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="61"/>
        <source>High limit</source>
        <translation>Limite haute</translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation>Choix Bluetooth</translation>
    </message>
</context>
<context>
    <name>claussPlugins</name>
    <message>
        <location filename="papywizard/plugins/claussPlugins.py" line="88"/>
        <source>Special</source>
        <translation>Spécial
</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/claussPlugins.py" line="89"/>
        <source>Auto Focus</source>
        <translation>Mise au point</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/claussPlugins.py" line="90"/>
        <source>Focus time</source>
        <translation>Temps de mise au point</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/claussPlugins.py" line="91"/>
        <source>Dual cameras</source>
        <translation>Double appereils</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/claussPlugins.py" line="92"/>
        <source>Time between shots</source>
        <translation>Temps entre prises de vues</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/claussPlugins.py" line="93"/>
        <source>Park position</source>
        <translation>Position de rangement</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Configuration</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Prise de vue</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Orientation tête</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>haut</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="193"/>
        <source>left</source>
        <translation>gauche</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="188"/>
        <source>right</source>
        <translation>droite</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>bas</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Orientation appareil</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>portrait</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>paysage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>personnalisé</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Délai de stabilisation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="204"/>
        <source>Mosaic</source>
        <translation>Mosaïque</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="212"/>
        <source>Overlap</source>
        <translation>Recouvrement</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>Start from</source>
        <translation>Commence depuis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="295"/>
        <source>Initial direction</source>
        <translation>Direction initiale</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="312"/>
        <source>yaw</source>
        <translation>lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="317"/>
        <source>pitch</source>
        <translation>tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="325"/>
        <source>CR</source>
        <translation>RC</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="360"/>
        <source>rectilinear</source>
        <translation>rectilinéaire</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="365"/>
        <source>fisheye</source>
        <translation>fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="685"/>
        <source>Data</source>
        <translation>Données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="693"/>
        <source>Data directory</source>
        <translation>Répertoire de données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="709"/>
        <source>Data file</source>
        <translation>Fichier de données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="912"/>
        <source>Enable</source>
        <translation>Actif</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="748"/>
        <source>Title</source>
        <translation>Titre</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="777"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="806"/>
        <source>Comment</source>
        <translation>Commentaire</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="849"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="860"/>
        <source>Start after</source>
        <translation>Commence après</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="883"/>
        <source>Repeat</source>
        <translation>Répétition</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="922"/>
        <source>Repeat every</source>
        <translation>Répète chaque</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="990"/>
        <source>Misc</source>
        <translation>Divers</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="998"/>
        <source>Logger level</source>
        <translation>Niveau de log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1015"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1020"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1025"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1030"/>
        <source>warning</source>
        <translation>warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1035"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1040"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1045"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="421"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Capteur (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="386"/>
        <source>Sensor resolution</source>
        <translation>Résolution capteur</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="373"/>
        <source>Optical multiplier</source>
        <translation>Multiplicateur optique</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="335"/>
        <source>Camera/lens</source>
        <translation>Appareil/objectif</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="343"/>
        <source>Lens (type, focal)</source>
        <translation>Objectif (type, focale)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="533"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="541"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="554"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="605"/>
        <source>Configure...</source>
        <translation>Configurer...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="581"/>
        <source>Shutter</source>
        <translation>Obturateur</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="267"/>
        <source>top-left</source>
        <translation>haut-gauche</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="272"/>
        <source>top-right</source>
        <translation>haut-droit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>bottom-left</source>
        <translation>bas-gauche</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>bottom-right</source>
        <translation>bas-droit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="980"/>
        <source>Reverse direction before repeat</source>
        <translation>Inverse direction avant répétition</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="171"/>
        <source>Pitch arm side</source>
        <translation>Côté bras tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1053"/>
        <source>Shooting counter</source>
        <translation>Compteur prise de vue</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1085"/>
        <source>Show</source>
        <translation>Affiche</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="287"/>
        <source>nearest-corner</source>
        <translation>plus-proche</translation>
    </message>
</context>
<context>
    <name>counterDialog</name>
    <message>
        <location filename="papywizard/view/ui/counterDialog.ui" line="14"/>
        <source>Counter</source>
        <translation>Compteur</translation>
    </message>
</context>
<context>
    <name>dslrRemoteProPlugins</name>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation>Liste compensation
exposition utilisateur</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="89"/>
        <source>Dry run</source>
        <translation>Mode test</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="91"/>
        <source>Camera</source>
        <translation>Appareil</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="92"/>
        <source>Output directory</source>
        <translation>Répertoire de sortie</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="93"/>
        <source>Choose output directory...</source>
        <translation>Choisir répertoire de sortie...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="94"/>
        <source>File name prefix</source>
        <translation>Préfixe fichiers</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="95"/>
        <source>Camera exposure
compensation list</source>
        <translation>Liste compensation
exposition appareil</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Programme</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Choisir programme...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>Fichiers EXE (*.exe);;Tous les fichiers (*)</translation>
    </message>
</context>
<context>
    <name>eosUtilityPlugins</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="110"/>
        <source>new</source>
        <translation>nouveau</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="113"/>
        <source>far</source>
        <translation>loin</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="119"/>
        <source>medium</source>
        <translation>moyen</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="109"/>
        <source>old</source>
        <translation>ancien</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="114"/>
        <source>near</source>
        <translation>proche</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="118"/>
        <source>small</source>
        <translation>petit</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="120"/>
        <source>large</source>
        <translation>grand</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Programme</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>EOS Utility version</source>
        <translation>Version EOS Utility</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>Bracketing nb picts</source>
        <translation>Nb photos multi-exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="90"/>
        <source>Bracketing type</source>
        <translation>Type multi-exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>Dry run</source>
        <translation>Mode test</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="93"/>
        <source>Bulb</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>Enable</source>
        <translation>Actif</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="95"/>
        <source>Base exposure</source>
        <translation>Base d&apos;exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>Focus</source>
        <translation>MaP</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="99"/>
        <source>Direction</source>
        <translation>Direction</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="100"/>
        <source>Step</source>
        <translation>Pas</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="101"/>
        <source>Step count</source>
        <translation>Nb pas</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="102"/>
        <source>Nb picts</source>
        <translation>Nb photos</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="89"/>
        <source>Bracketing step</source>
        <translation>Incrément d&apos;exposition</translation>
    </message>
</context>
<context>
    <name>genericTetheredPlugins</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="80"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="81"/>
        <source>Mirror lockup command</source>
        <translation>Commande verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="82"/>
        <source>Shoot command</source>
        <translation>Commande déclenchement</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="83"/>
        <source>Time value</source>
        <translation>Durée d&apos;exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="85"/>
        <source>Params</source>
        <translation></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="86"/>
        <source>Parameter &apos;p0&apos;</source>
        <translation>Paramètre &apos;p0&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="88"/>
        <source>Parameter &apos;p2&apos;</source>
        <translation>Paramètre &apos;p2&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="89"/>
        <source>Parameter &apos;p3&apos;</source>
        <translation>Paramètre &apos;p3&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="90"/>
        <source>Parameter &apos;p4&apos;</source>
        <translation>Paramètre &apos;p4&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="87"/>
        <source>Parameter &apos;p1&apos;</source>
        <translation>Paramètre &apos;p1&apos;</translation>
    </message>
</context>
<context>
    <name>gphotoBracketPlugins</name>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="93"/>
        <source>Program path</source>
        <translation>Programme</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="94"/>
        <source>Choose program path...</source>
        <translation>Choisir programme...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="95"/>
        <source>gphoto2 (gphoto2);;All files (*)</source>
        <translation>gphoto2 (gphoto2);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="96"/>
        <source>Bracketing nb picts</source>
        <translation>Nb photos multi-exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="97"/>
        <source>Bracketing step</source>
        <translation>Incrément d&apos;exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="98"/>
        <source>Exposure bias</source>
        <translation>Décalage d&apos;exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="99"/>
        <source>Resulting Ev list</source>
        <translation>Liste d&apos;expositions</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="102"/>
        <source>Advanced</source>
        <translation>Avancé</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="103"/>
        <source>Bracketing nb picts (+)</source>
        <translation>Nb photos multi-exposition (+)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="104"/>
        <source>Bracketing step (+)</source>
        <translation>Incrément d&apos;exposition (+)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="105"/>
        <source>Bracketing nb picts (-)</source>
        <translation>Nb photos multi-exposition (-)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="106"/>
        <source>Bracketing step (-)</source>
        <translation>Incrément d&apos;exposition (-)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="108"/>
        <source>Download</source>
        <translation>Télécharger</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="109"/>
        <source>Enable</source>
        <translation>Actif</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="110"/>
        <source>Download directory</source>
        <translation>Répertoire téléchargement</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="111"/>
        <source>Choose download directory...</source>
        <translation>Choisir répertoire téléchargement...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="113"/>
        <source>Download after</source>
        <translation>Télécharge après</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="114"/>
        <source>Each shot</source>
        <translation>Chaque déclenchement</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="115"/>
        <source>Bracketing sequence</source>
        <translation>Séquence</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="116"/>
        <source>Delete camera picts</source>
        <translation>Efface images de l&apos;appareil</translation>
    </message>
</context>
<context>
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>À propos de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>Général</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard est un logiciel de pilotage de tête panoramique principalement développé pour la tête astronomique Merlin/Orion mais utilisable pour d&apos;autres têtes.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Crédits</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="190"/>
        <source>License</source>
        <translation>Licence</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="196"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>Ce logiciel est régi par la licence CeCILL soumise au droit français et respectant les principes de diffusion des logiciels libres. Vous pouvez utiliser, modifier et/ou redistribuer ce programme sous les conditions de la licence CeCILL telle que diffusée par le CEA, le CNRS et l&apos;INRIA sur le site http://www.cecill.info.

En contrepartie de l&apos;accessibilité au code source et des droits de copie, de modification et de redistribution accordés par cette licence, il n&apos;est offert aux utilisateurs qu&apos;une garantie limitée.  Pour les mêmes raisons, seule une responsabilité restreinte pèse sur l&apos;auteur du programme, le titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l&apos;attention de l&apos;utilisateur est attirée sur les risques associés au chargement,  à l&apos;utilisation,  à la modification et/ou au développement et à la reproduction du logiciel par l&apos;utilisateur étant  donné sa spécificité de logiciel libre, qui peut le rendre complexe à manipuler et qui le réserve donc à des développeurs et des professionnels avertis possédant  des  connaissances  informatiques approfondies.  Les utilisateurs sont donc invités à charger  et  tester  l&apos;adéquation  du logiciel à leurs besoins dans des conditions permettant d&apos;assurer la sécurité de leurs systèmes et ou de leurs données et, plus généralement, à l&apos;utiliser et l&apos;exploiter dans les mêmes conditions de sécurité.

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez pris connaissance de la licence CeCILL, et que vous en avez accepté les termes.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lee Jeongyun (Gphoto Bracket plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (gnu/linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Écrit par :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (branche principale)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (plugin EOS Utility)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lee Jeongyun (plugin Gphoto Bracket)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Traduit par :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphismes de :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Binaires de :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (gnu/linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2010 Frédéric Mantegazza</source>
        <translation>© 2007-2010 Frédéric Mantegazza</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="14"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="145"/>
        <source>Clear log</source>
        <translation>Effacer log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="152"/>
        <source>Save log</source>
        <translation>Enregistrer log</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="229"/>
        <source>Plugins selection</source>
        <translation>Sélection des plugins</translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="229"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation>Avant de pouvoir utiliser Papywizard, vous devez choisir quels plugins utiliser pour piloter votre matériel.

Après fermeture de cette fenêtre, il vous sera demandé de sélectionner ces plugins. Une fois que cela sera fait, vous pourrez les configurer en utilisant la fenêtre de Configuration globale</translation>
    </message>
</context>
<context>
    <name>merlinOrionPlugins</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="83"/>
        <source>Hard</source>
        <translation>Matos</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="84"/>
        <source>Alternate drive</source>
        <translation>Positionnement alternatif</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="86"/>
        <source>Inertia angle</source>
        <translation>Angle d&apos;inertie</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="85"/>
        <source>Alternate drive angle</source>
        <translation>Angle alternatif</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation>Nb Photos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation>Nb photos</translation>
    </message>
</context>
<context>
    <name>nkRemotePlugins</name>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Programme</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Choisir programme...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>Fichiers EXE (*.exe);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation>Liste compensation
exposition utilisateur</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="89"/>
        <source>Dry run</source>
        <translation>Mode test</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="91"/>
        <source>Camera</source>
        <translation>Appareil</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="92"/>
        <source>Choose output directory...</source>
        <translation>Choisir répertoire de sortie...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="93"/>
        <source>File name prefix</source>
        <translation>Préfixe fichiers</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="94"/>
        <source>Camera exposure
compensation list</source>
        <translation>Liste compensation
exposition appareil</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="233"/>
        <source>Output directory</source>
        <translation>Répertoire de sortie</translation>
    </message>
</context>
<context>
    <name>panoduinoPlugins</name>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="120"/>
        <source>forward</source>
        <translation>avant</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="105"/>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="107"/>
        <source>Direction</source>
        <translation>Direction</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="109"/>
        <source>Neutral position</source>
        <translation>Position du neutre</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="121"/>
        <source>reverse</source>
        <translation>arrière</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="102"/>
        <source>Speed</source>
        <translation>Vitesse</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="103"/>
        <source>Acceleration</source>
        <translation>Accélération</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="106"/>
        <source>Channel</source>
        <translation>Canal</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="108"/>
        <source>Angle for 1ms</source>
        <translation>Angle pour 1ms</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="112"/>
        <source>Shutter on</source>
        <translation>Obturateur activé</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="113"/>
        <source>Shutter off</source>
        <translation>Obturateur désactivé</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="110"/>
        <source>Additional delay</source>
        <translation>Délai additionel</translation>
    </message>
</context>
<context>
    <name>pixOrbPlugins</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="82"/>
        <source>Speed index</source>
        <translation>Index vitesse</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="84"/>
        <source>Hard</source>
        <translation>Matos</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="85"/>
        <source>Axis with break</source>
        <translation>Axe avec frein</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="86"/>
        <source>Axis accuracy</source>
        <translation>Précision de l&apos;axe</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="26"/>
        <source>Plugin dialog</source>
        <translation>Fenêtre des plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="46"/>
        <source>Main</source>
        <translation>Principal</translation>
    </message>
</context>
<context>
    <name>pluginsDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation>Obturateur</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation>bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation>serial</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation>ethernet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation>Pilotes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>Adresse interface BT</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="241"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet hôte/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="286"/>
        <source>Choose...</source>
        <translation>Choisir...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="343"/>
        <source>Communication</source>
        <translation>Communication</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="351"/>
        <source>Timeout</source>
        <translation>Timeout</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="389"/>
        <source>Retry</source>
        <translation>Essais</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="212"/>
        <source>Serial port/baudrate</source>
        <translation>Port série nom/vitesse</translation>
    </message>
</context>
<context>
    <name>pluginsStatusDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="14"/>
        <source>Plugins Status</source>
        <translation>Status des plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="49"/>
        <source>Shutter</source>
        <translation>Obturateur</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="65"/>
        <source>Init</source>
        <translation>Initialisation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="81"/>
        <source>Connect</source>
        <translation>Connexion</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Prise de vue</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="111"/>
        <source>Total</source>
        <translation>Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="121"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="131"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="141"/>
        <source>Current</source>
        <translation>Courante</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="205"/>
        <source>Next</source>
        <translation>Suivante</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="353"/>
        <source>Idle</source>
        <translation>Repos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="440"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="526"/>
        <source>Data</source>
        <translation>Données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="555"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="581"/>
        <source>Step-by-step</source>
        <translation>Pas-à-pas</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="614"/>
        <source>Start</source>
        <translation>Démarrer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="643"/>
        <source>Pause</source>
        <translation>Suspendre</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="672"/>
        <source>Stop</source>
        <translation>Arrêter</translation>
    </message>
</context>
<context>
    <name>shutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="60"/>
        <source>Time value</source>
        <translation>Durée d&apos;exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="61"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="62"/>
        <source>Bulb</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="63"/>
        <source>Bracketing nb picts</source>
        <translation>Nb photos multi-exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="66"/>
        <source>Hard</source>
        <translation>Matos</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="67"/>
        <source>Pulse width high</source>
        <translation>Largeur impulsion haute</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/shutterPluginController.py" line="68"/>
        <source>Pulse width low</source>
        <translation>Largeur impulsion basse</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="84"/>
        <source>Trigger only once</source>
        <translation>Déclenchement unique</translation>
    </message>
</context>
<context>
    <name>simulationPlugins</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="79"/>
        <source>Speed</source>
        <translation>Vitesse</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="81"/>
        <source>Time value</source>
        <translation>Durée d&apos;exposition</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="82"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="83"/>
        <source>Bracketing nb picts</source>
        <translation>Nb photos multi-exposition</translation>
    </message>
</context>
<context>
    <name>timelordPlugins</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="73"/>
        <source>Program path</source>
        <translation>Programme</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="74"/>
        <source>Choose program path...</source>
        <translation>Choisir programme...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="75"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>Fichiers EXE (*.exe);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="76"/>
        <source>LRD file</source>
        <translation>Fichier LRD</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="77"/>
        <source>Choose LRD file...</source>
        <translation>Choisir fichier LRD...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="78"/>
        <source>LRD files (*.lrd);;All files (*)</source>
        <translation>Fichiers LRD (*.lrd);;Tous les fichiers (*)</translation>
    </message>
</context>
<context>
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation>Adc Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
<context>
    <name>ursaMinorBt2Plugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="102"/>
        <source>Focus</source>
        <translation>MaP</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="103"/>
        <source>Enable</source>
        <translation>Actif</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="104"/>
        <source>Pulse width</source>
        <translation>Largeur impulsion</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="105"/>
        <source>Maintain with shutter</source>
        <translation>Maintenir avec obturateur</translation>
    </message>
</context>
<context>
    <name>ursaMinorUsbPlugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="74"/>
        <source>Trigger line</source>
        <translation>Ligne déclenchement</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="75"/>
        <source>Line inverted</source>
        <translation>Ligne inversée</translation>
    </message>
</context>
</TS>
