<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="139"/>
        <source>Abort</source>
        <translation>Abort</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="178"/>
        <source>Wrong value for camera orientation</source>
        <translation>Wrong value for camera orientation</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="178"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="192"/>
        <source>Wrong value for lens type</source>
        <translation>Wrong value for lens type</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="192"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="236"/>
        <source>Choose Data Storage dir</source>
        <translation>Choose Data Storage dir</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="332"/>
        <source>Here goes the title</source>
        <translation>Here goes the title</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="336"/>
        <source>Here goes the location</source>
        <translation>Here goes the location</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="340"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Generated by Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="110"/>
        <source>Error</source>
        <translation>Error</translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="119"/>
        <source>Exception</source>
        <translation>Exception</translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="92"/>
        <source>Info</source>
        <translation>Info</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="317"/>
        <source>Manual speed set to slow</source>
        <translation>Manual speed set to slow</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="333"/>
        <source>Manual speed set to normal</source>
        <translation>Manual speed set to normal</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="339"/>
        <source>Manual speed set to fast</source>
        <translation>Manual speed set to fast</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="345"/>
        <source>About to Quit</source>
        <translation>About to Quit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="345"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Are you sure you want to quit Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="361"/>
        <source>Import Preset File</source>
        <translation>Import Preset File</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="361"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML files (*.xml);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="370"/>
        <source>Load Style Sheet</source>
        <translation>Load Style Sheet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="370"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS files (*.css);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="388"/>
        <source>Yaw - limit set</source>
        <translation>Yaw - limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="394"/>
        <source>Yaw + limit set</source>
        <translation>Yaw + limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="400"/>
        <source>Pitch + limit set</source>
        <translation>Pitch + limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="406"/>
        <source>Pitch - limit set</source>
        <translation>Pitch - limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="411"/>
        <source>Limits cleared</source>
        <translation>Limits cleared</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="442"/>
        <source>Operation aborted</source>
        <translation>Operation aborted</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="432"/>
        <source>Goto initial position...</source>
        <translation>Goto initial position...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="446"/>
        <source>Initial position reached</source>
        <translation>Initial position reached</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="615"/>
        <source>Field of view set to user value</source>
        <translation>Field of view set to user value</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="626"/>
        <source>Number of pictures set to user value</source>
        <translation>Number of pictures set to user value</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="648"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Opening configuration dialog. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="681"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Opening shoot dialog. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="727"/>
        <source>Can&apos;t import preset file</source>
        <translation>Can&apos;t import preset file</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="743"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Can&apos;t load style sheet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="559"/>
        <source>Reference set at current position</source>
        <translation>Reference set at current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="436"/>
        <source>Please wait...</source>
        <translation>Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="436"/>
        <source>Goto initial position</source>
        <translation>Goto initial position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="415"/>
        <source>Goto reference position...</source>
        <translation>Goto reference position...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="417"/>
        <source>Goto reference position</source>
        <translation>Goto reference position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="427"/>
        <source>Reference position reached</source>
        <translation>Reference position reached</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="631"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation>Opening plugins dialog. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="804"/>
        <source>Starting connection. Please wait...</source>
        <translation>Starting connection. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="827"/>
        <source>Connection started</source>
        <translation>Connection started</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="832"/>
        <source>Connection failed to start</source>
        <translation>Connection failed to start</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="844"/>
        <source>Stopping connection. Please wait...</source>
        <translation>Stopping connection. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="857"/>
        <source>Connection stopped</source>
        <translation>Connection stopped</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="503"/>
        <source>Yaw corner 0 set from current position</source>
        <translation>Yaw corner 0 set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="511"/>
        <source>Pitch corner 0 set from current position</source>
        <translation>Pitch corner 0 set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="527"/>
        <source>Yaw corner 1 set from current position</source>
        <translation>Yaw corner 1 set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="535"/>
        <source>Pitch corner 1 set from current position</source>
        <translation>Pitch corner 1 set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="495"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation>Yaw/pitch corner 0 set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="519"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation>Yaw/pitch corner 1 set from current position</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="438"/>
        <source>Mosaic</source>
        <translation>Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="452"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="468"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="737"/>
        <source>Real overlap (%)</source>
        <translation>Real overlap (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="800"/>
        <source>Resolution (px)</source>
        <translation>Resolution (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="864"/>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="883"/>
        <source>Name</source>
        <translation>Name</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="927"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Be sure that the preset used is compatible with your camera and lens size (collision).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Move</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="348"/>
        <source>Configure...</source>
        <translation>Configure...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="371"/>
        <source>Shoot...</source>
        <translation>Shoot...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="969"/>
        <source>File</source>
        <translation>File</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="978"/>
        <source>Hardware</source>
        <translation>Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="982"/>
        <source>Set Limit</source>
        <translation>Set Limit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1001"/>
        <source>Help</source>
        <translation>Help</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1025"/>
        <source>Quit</source>
        <translation>Quit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1037"/>
        <source>Import Preset File...</source>
        <translation>Import Preset File...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1045"/>
        <source>Connect...</source>
        <translation>Connect...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1169"/>
        <source>Clear Limits</source>
        <translation>Clear Limits</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1054"/>
        <source>Yaw -</source>
        <translation>Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1063"/>
        <source>Yaw +</source>
        <translation>Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1072"/>
        <source>Pitch +</source>
        <translation>Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1081"/>
        <source>Pitch -</source>
        <translation>Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1090"/>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1099"/>
        <source>View Log...</source>
        <translation>View Log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1108"/>
        <source>About Papywizard</source>
        <translation>About Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1117"/>
        <source>About Qt</source>
        <translation>About Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1126"/>
        <source>Load Style Sheet...</source>
        <translation>Load Style Sheet...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1144"/>
        <source>Goto Initial...</source>
        <translation>Goto Initial...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1135"/>
        <source>Goto Reference...</source>
        <translation>Goto Reference...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1153"/>
        <source>Plugins...</source>
        <translation></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="615"/>
        <source>Total fov (°)</source>
        <translation>Total fov (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="676"/>
        <source>Nb picts</source>
        <translation>Nb picts</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="487"/>
        <source>Corner 0 (°)</source>
        <translation>Corner 0 (°)</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="554"/>
        <source>Corner 1 (°)</source>
        <translation>Corner 1 (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1164"/>
        <source>Suspend Spy</source>
        <translation>Suspend Spy</translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="209"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Can&apos;t scan bluetooth</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="290"/>
        <source>Step</source>
        <translation>Step</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="361"/>
        <source>Resume</source>
        <translation>Resume</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="374"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="365"/>
        <source>Paused</source>
        <translation>Paused</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="386"/>
        <source>Finished</source>
        <translation>Finished</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="388"/>
        <source>Canceled</source>
        <translation>Canceled</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="390"/>
        <source>Failed</source>
        <translation>Failed</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="397"/>
        <source>Waiting</source>
        <translation>Waiting</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="443"/>
        <source>Moving</source>
        <translation>Moving</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="445"/>
        <source>Stabilization</source>
        <translation>Stabilization</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="447"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="450"/>
        <source>Shutter - Picture</source>
        <translation>Shutter - Picture</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="580"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="392"/>
        <source>Finish</source>
        <translation>Finish</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="491"/>
        <source>Idle</source>
        <translation>Idle</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="549"/>
        <source>Shutter failed while mirror locking up</source>
        <translation>Shutter failed while mirror locking up</translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="564"/>
        <source>Shutter failed while shooting</source>
        <translation>Shutter failed while shooting</translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Choose program path...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE files (*.exe);;All files (*)</translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="101"/>
        <source>Warning</source>
        <translation>Warning</translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="130"/>
        <source>Question</source>
        <translation>Question</translation>
    </message>
</context>
<context>
    <name>abstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="61"/>
        <source>Main</source>
        <translation>Main</translation>
    </message>
</context>
<context>
    <name>axisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="60"/>
        <source>Low limit</source>
        <translation>Low limit</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="61"/>
        <source>High limit</source>
        <translation>High limit</translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation>Bluetooth Chooser</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Configuration</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Shooting</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Head orientation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>up</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="193"/>
        <source>left</source>
        <translation>left</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="188"/>
        <source>right</source>
        <translation>right</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>down</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Camera orientation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>portrait</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>landscape</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>custom</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Stabilization delay</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="204"/>
        <source>Mosaic</source>
        <translation>Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="212"/>
        <source>Overlap</source>
        <translation>Overlap</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>Start from</source>
        <translation>Start from</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="290"/>
        <source>Initial direction</source>
        <translation>Initial direction</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="307"/>
        <source>yaw</source>
        <translation>yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="312"/>
        <source>pitch</source>
        <translation>pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="320"/>
        <source>CR</source>
        <translation>CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="355"/>
        <source>rectilinear</source>
        <translation>rectilinear</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="360"/>
        <source>fisheye</source>
        <translation>fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="680"/>
        <source>Data</source>
        <translation>Data</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="688"/>
        <source>Data directory</source>
        <translation>Data directory</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="704"/>
        <source>Data file</source>
        <translation>Data file</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="904"/>
        <source>Enable</source>
        <translation>Enable</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="743"/>
        <source>Title</source>
        <translation>Title</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="772"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="801"/>
        <source>Comment</source>
        <translation>Comment</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="844"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="855"/>
        <source>Start after</source>
        <translation>Start after</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="878"/>
        <source>Repeat</source>
        <translation>Repeat</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="914"/>
        <source>Repeat every</source>
        <translation>Repeat every</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="982"/>
        <source>Misc</source>
        <translation>Misc</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="990"/>
        <source>Logger level</source>
        <translation>Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1007"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1012"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1017"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1022"/>
        <source>warning</source>
        <translation>warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1027"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1032"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1037"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="416"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Sensor (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="381"/>
        <source>Sensor resolution</source>
        <translation>Sensor resolution</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="368"/>
        <source>Optical multiplier</source>
        <translation>Optical multiplier</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="330"/>
        <source>Camera/lens</source>
        <translation>Camera/lens</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="338"/>
        <source>Lens (type, focal)</source>
        <translation>Lens (type, focal)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="528"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="536"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="549"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="600"/>
        <source>Configure...</source>
        <translation>Configure...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="576"/>
        <source>Shutter</source>
        <translation>Shutter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="267"/>
        <source>top-left</source>
        <translation>top-left</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="272"/>
        <source>top-right</source>
        <translation>top-right</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>bottom-left</source>
        <translation>bottom-left</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>bottom-right</source>
        <translation>bottom-right</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="972"/>
        <source>Reverse direction before repeat</source>
        <translation>Reverse direction before repeat</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="171"/>
        <source>Pitch arm side</source>
        <translation>Pitch arm side</translation>
    </message>
</context>
<context>
    <name>dslrRemoteProPlugins</name>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation>User exposure
compensation list</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="89"/>
        <source>Dry run</source>
        <translation>Dry run</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="91"/>
        <source>Camera</source>
        <translation>Camera</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="92"/>
        <source>Output directory</source>
        <translation>Output directory</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="93"/>
        <source>Choose output directory...</source>
        <translation>Choose output directory...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="94"/>
        <source>File name prefix</source>
        <translation>File name prefix</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="95"/>
        <source>Camera exposure
compensation list</source>
        <translation>Camera exposure
compensation list</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Program path</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Choose program path...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE files (*.exe);;All files (*)</translation>
    </message>
</context>
<context>
    <name>eosUtilityPlugins</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="110"/>
        <source>new</source>
        <translation>new</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="113"/>
        <source>far</source>
        <translation>far</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="119"/>
        <source>medium</source>
        <translation>medium</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="109"/>
        <source>old</source>
        <translation>old</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="114"/>
        <source>near</source>
        <translation>near</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="118"/>
        <source>small</source>
        <translation>small</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="120"/>
        <source>large</source>
        <translation>large</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Program path</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>EOS Utility version</source>
        <translation>EOS Utility version</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>Bracketing nb picts</source>
        <translation>Bracketing nb picts</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="90"/>
        <source>Bracketing type</source>
        <translation>Bracketing type</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>Dry run</source>
        <translation>Dry run</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="93"/>
        <source>Bulb</source>
        <translation>Bulb</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>Enable</source>
        <translation>Enable</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="95"/>
        <source>Base exposure</source>
        <translation>Base exposure</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>Focus</source>
        <translation>Focus</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="99"/>
        <source>Direction</source>
        <translation>Direction</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="100"/>
        <source>Step</source>
        <translation>Step</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="101"/>
        <source>Step count</source>
        <translation>Step count</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="102"/>
        <source>Nb picts</source>
        <translation>Nb picts</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="89"/>
        <source>Bracketing step</source>
        <translation>Bracketing step</translation>
    </message>
</context>
<context>
    <name>genericTetheredPlugins</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="76"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="77"/>
        <source>Mirror lockup command</source>
        <translation>Mirror lockup command</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="80"/>
        <source>Shoot command</source>
        <translation>Shoot command</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="83"/>
        <source>Bracketing nb picts</source>
        <translation>Bracketing nb picts</translation>
    </message>
</context>
<context>
    <name>gphotoBracketPlugins</name>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="93"/>
        <source>Program path</source>
        <translation>Program path</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="94"/>
        <source>Choose program path...</source>
        <translation>Choose program path...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="95"/>
        <source>gphoto2 (gphoto2);;All files (*)</source>
        <translation></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="96"/>
        <source>Bracketing nb picts</source>
        <translation>Bracketing nb picts</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="97"/>
        <source>Bracketing step</source>
        <translation>Bracketing step</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="98"/>
        <source>Exposure bias</source>
        <translation>Exposure bias</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="99"/>
        <source>Resulting Ev list</source>
        <translation>Resulting Ev list</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="102"/>
        <source>Advanced</source>
        <translation>Advanced</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="103"/>
        <source>Bracketing nb picts (+)</source>
        <translation>Bracketing nb picts (+)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="104"/>
        <source>Bracketing step (+)</source>
        <translation>Bracketing step (+)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="105"/>
        <source>Bracketing nb picts (-)</source>
        <translation>Bracketing nb picts (-)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="106"/>
        <source>Bracketing step (-)</source>
        <translation>Bracketing step (-)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="108"/>
        <source>Download</source>
        <translation>Download</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="109"/>
        <source>Enable</source>
        <translation>Enable</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="110"/>
        <source>Download directory</source>
        <translation>Download directory</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="111"/>
        <source>Choose download directory...</source>
        <translation>Choose download directory...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="113"/>
        <source>Download after</source>
        <translation>Download after</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="114"/>
        <source>Each shot</source>
        <translation>Each shot</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="115"/>
        <source>Bracketing sequence</source>
        <translation>Bracketing sequence</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="116"/>
        <source>Delete camera picts</source>
        <translation>Delete camera picts</translation>
    </message>
</context>
<context>
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>About Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>General</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Credits</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="189"/>
        <source>License</source>
        <translation>License</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="195"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.￼

￼As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.￼

￼In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.￼

￼The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="14"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="145"/>
        <source>Clear log</source>
        <translation>Clear log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="152"/>
        <source>Save log</source>
        <translation>Save log</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Plugins selection</source>
        <translation>Plugins selection</translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</translation>
    </message>
</context>
<context>
    <name>merlinOrionPlugins</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="82"/>
        <source>Hard</source>
        <translation>Hard</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="83"/>
        <source>Alternate drive</source>
        <translation>Alternate drive</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="84"/>
        <source>Inertia angle</source>
        <translation>Inertia angle</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation># Picts</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation>Nb picts</translation>
    </message>
</context>
<context>
    <name>nkRemotePlugins</name>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Program path</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Choose program path...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE files (*.exe);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation>User exposure
compensation list</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="89"/>
        <source>Dry run</source>
        <translation>Dry run</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="91"/>
        <source>Camera</source>
        <translation>Camera</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="92"/>
        <source>Choose output directory...</source>
        <translation>Choose output directory...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="93"/>
        <source>File name prefix</source>
        <translation>File name prefix</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="94"/>
        <source>Camera exposure
compensation list</source>
        <translation>Camera exposure
compensation list</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="233"/>
        <source>Output directory</source>
        <translation>Output directory</translation>
    </message>
</context>
<context>
    <name>panoduinoPlugins</name>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="99"/>
        <source>forward</source>
        <translation>forward</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="82"/>
        <source>Speed</source>
        <translation>Speed</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="84"/>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="85"/>
        <source>Direction</source>
        <translation>Direction</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="86"/>
        <source>Neutral position</source>
        <translation>Neutral position</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="87"/>
        <source>Value off</source>
        <translation>Value off</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="88"/>
        <source>Value on</source>
        <translation>Value on</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="100"/>
        <source>reverse</source>
        <translation>reverse</translation>
    </message>
</context>
<context>
    <name>pixOrbPlugins</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="82"/>
        <source>Speed index</source>
        <translation>Speed index</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="84"/>
        <source>Hard</source>
        <translation>Hard</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="85"/>
        <source>Axis with break</source>
        <translation>Axis with break</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="86"/>
        <source>Axis accuracy</source>
        <translation>Axis accuracy</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="26"/>
        <source>Plugin dialog</source>
        <translation>Plugin dialog</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="46"/>
        <source>Main</source>
        <translation>Main</translation>
    </message>
</context>
<context>
    <name>pluginsDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation>Shutter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation>bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation>serial</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation>ethernet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation>Drivers</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>BT device address</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="212"/>
        <source>Serial port</source>
        <translation>Serial port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="241"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="286"/>
        <source>Choose...</source>
        <translation>Choose...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="296"/>
        <source>Communication</source>
        <translation>Communication</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="304"/>
        <source>Timeout</source>
        <translation>Timeout</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="342"/>
        <source>Retry</source>
        <translation>Retry</translation>
    </message>
</context>
<context>
    <name>pluginsStatusDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="14"/>
        <source>Plugins Status</source>
        <translation>Plugins Status</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="49"/>
        <source>Shutter</source>
        <translation>Shutter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="65"/>
        <source>Init</source>
        <translation>Init</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="81"/>
        <source>Connect</source>
        <translation>Connect</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Shooting</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation>Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation>Current</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation>Next</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="341"/>
        <source>Idle</source>
        <translation>Idle</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="428"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="514"/>
        <source>Data</source>
        <translation>Data</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="543"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="569"/>
        <source>Step-by-step</source>
        <translation>Step-by-step</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="602"/>
        <source>Start</source>
        <translation>Start</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="631"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="660"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
</context>
<context>
    <name>simulationPlugins</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="78"/>
        <source>Speed</source>
        <translation>Speed</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="80"/>
        <source>Time value</source>
        <translation>Time value</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="81"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="82"/>
        <source>Bracketing nb picts</source>
        <translation>Bracketing nb picts</translation>
    </message>
</context>
<context>
    <name>standardShutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="60"/>
        <source>Time value</source>
        <translation>Time value</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="61"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="63"/>
        <source>Bracketing nb picts</source>
        <translation>Bracketing nb picts</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="65"/>
        <source>Hard</source>
        <translation>Hard</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="66"/>
        <source>Pulse width high</source>
        <translation>Pulse width high</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="67"/>
        <source>Pulse width low</source>
        <translation>Pulse width low</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="62"/>
        <source>Bulb</source>
        <translation>Bulb</translation>
    </message>
</context>
<context>
    <name>timelordPlugins</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="73"/>
        <source>Program path</source>
        <translation>Program path</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="74"/>
        <source>Choose program path...</source>
        <translation>Choose program path...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="75"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE files (*.exe);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="76"/>
        <source>LRD file</source>
        <translation>LRD file</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="77"/>
        <source>Choose LRD file...</source>
        <translation>Choose LRD file...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="78"/>
        <source>LRD files (*.lrd);;All files (*)</source>
        <translation>LRD files (*.lrd);;All files (*)</translation>
    </message>
</context>
<context>
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation>Total Fov</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation>Total fov</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
<context>
    <name>ursaMinorBt2Plugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="74"/>
        <source>Focus</source>
        <translation>Focus</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="75"/>
        <source>Enable</source>
        <translation>Enable</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="76"/>
        <source>Pulse width</source>
        <translation>Pulse width</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="77"/>
        <source>Maintain focus</source>
        <translation>Maintain focus</translation>
    </message>
</context>
<context>
    <name>ursaMinorUsbPlugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="74"/>
        <source>Trigger line</source>
        <translation>Trigger line</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="75"/>
        <source>Line inverted</source>
        <translation>Line inverted</translation>
    </message>
</context>
</TS>
