<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="de">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="138"/>
        <source>Abort</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>AbstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="73"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>AxisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="66"/>
        <source>Low limit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="68"/>
        <source>High limit</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="176"/>
        <source>Wrong value for camera orientation</source>
        <translation>Falscher Wert für Kameraausrichtung</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="177"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Kameraausrichtung &apos;Eigene&apos; nicht wählbar im Rastermodus</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="190"/>
        <source>Wrong value for lens type</source>
        <translation>Falscher Wert für Objektiv-Typ</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="191"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Objektivtyp &apos;Fischauge&apos; nicht wählbar im Rastermodus</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="235"/>
        <source>Choose Data Storage dir</source>
        <translation>Datenverzeichnis wählen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="330"/>
        <source>Here goes the title</source>
        <translation>Titel hier eintragen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="334"/>
        <source>Here goes the location</source>
        <translation>Ortsangabe hier eintragen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="338"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Erstellt von Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>EOSUtilityShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>old</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>new</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="213"/>
        <source>Bulb</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="218"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>far</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="92"/>
        <source>near</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="96"/>
        <source>small</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>medium</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>large</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="198"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="203"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="207"/>
        <source>Bracketing stops</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="209"/>
        <source>Bracketing type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="219"/>
        <source>Enable</source>
        <translation>Aktivieren</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="216"/>
        <source>Base exposure</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="222"/>
        <source>Direction</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="225"/>
        <source>Step</source>
        <translation>Schritt</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="229"/>
        <source>Nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="227"/>
        <source>Step count</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="211"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="201"/>
        <source>EOS Utility version</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="109"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="118"/>
        <source>Exception</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>GenericTetheredShutterController</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="124"/>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="126"/>
        <source>Mirror lockup command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="128"/>
        <source>Shoot command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="130"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>GphotoShutterController</name>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="159"/>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="161"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="163"/>
        <source>Bracketing step</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="91"/>
        <source>Info</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="364"/>
        <source>Manual speed set to slow</source>
        <translation>Geschwindigkeit langsam</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="382"/>
        <source>Manual speed set to normal</source>
        <translation>Geschwindigkeit normal</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="392"/>
        <source>Manual speed set to fast</source>
        <translation>Geschwindigkeit schnell</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="421"/>
        <source>About to Quit</source>
        <translation>Anwendung beenden</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="421"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Papywizard wirklich beenden?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="481"/>
        <source>Import Preset File</source>
        <translation>Import Datei Voreinstellungen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="483"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML Dateien (*.xml);;Alle Dateien (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="490"/>
        <source>Load Style Sheet</source>
        <translation>Lade Style sheet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="492"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS Dateien (*.css);;All Dateien (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="507"/>
        <source>Yaw - limit set</source>
        <translation>Drehung - Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="513"/>
        <source>Yaw + limit set</source>
        <translation>Drehung + Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="519"/>
        <source>Pitch + limit set</source>
        <translation>Neigung + Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="525"/>
        <source>Pitch - limit set</source>
        <translation>Neigung - Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="530"/>
        <source>Limits cleared</source>
        <translation>Limits gelöscht</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="564"/>
        <source>Operation aborted</source>
        <translation>Vorgang abgebrochen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="553"/>
        <source>Goto initial position...</source>
        <translation>Gehe zu Ausgangsposition...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="568"/>
        <source>Initial position reached</source>
        <translation>Ausgangsposition erreicht</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="756"/>
        <source>Field of view set to user value</source>
        <translation>FOV auf Benutzerwert gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="769"/>
        <source>Number of pictures set to user value</source>
        <translation>Anzahl Aufnahmen auf Benutzerwert gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="793"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Einstelldialog öffnen. Bitte warten...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="828"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Aufnahmedialog öffnen. Bitte warten...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="877"/>
        <source>Can&apos;t import preset file</source>
        <translation>Datei mit Voreinstellungen kann nicht importiert werden</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="895"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Style sheet kann nicht geladen werden</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="674"/>
        <source>Reference set at current position</source>
        <translation>Aktuelle Position als Nullpunkt gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="557"/>
        <source>Please wait...</source>
        <translation>Bitte warten...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="557"/>
        <source>Goto initial position</source>
        <translation>Gehe zu Ausgangsposition</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="534"/>
        <source>Goto reference position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="536"/>
        <source>Goto reference position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="547"/>
        <source>Reference position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="774"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="937"/>
        <source>Starting connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="956"/>
        <source>Connection started</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="961"/>
        <source>Connection failed to start</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="975"/>
        <source>Stopping connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="988"/>
        <source>Connection stopped</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="621"/>
        <source>Yaw corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="628"/>
        <source>Pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="635"/>
        <source>Yaw corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="642"/>
        <source>Pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="735"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="743"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="438"/>
        <source>Mosaic</source>
        <translation>Raster</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="933"/>
        <source>Yaw</source>
        <translation>Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="949"/>
        <source>Pitch</source>
        <translation>Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1057"/>
        <source>--</source>
        <translation>--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="703"/>
        <source>Real overlap (%)</source>
        <translation>Überlappung (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="766"/>
        <source>Resolution (px)</source>
        <translation>Auflösung (pixel)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="830"/>
        <source>Preset</source>
        <translation>Vorlage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="849"/>
        <source>Name</source>
        <translation>Name</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="893"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Sicherstellen dass Voreinstellung kompatibel mit Kamera und Objektiv ist (Kollision mit Merlin).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="919"/>
        <source>Timelapse</source>
        <translation>Zeitraffer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Move</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="312"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="348"/>
        <source>Configure...</source>
        <translation>Einstellungen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="371"/>
        <source>Shoot...</source>
        <translation>Aufnahme...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1100"/>
        <source>File</source>
        <translation>Datei</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1109"/>
        <source>Hardware</source>
        <translation>Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1113"/>
        <source>Set Limit</source>
        <translation>Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1134"/>
        <source>Help</source>
        <translation>Hilfe</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1158"/>
        <source>Quit</source>
        <translation>Quit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1161"/>
        <source>Ctrl+Q</source>
        <translation>Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1170"/>
        <source>Import Preset File...</source>
        <translation>Import Datei Voreinstellungen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1178"/>
        <source>Connect...</source>
        <translation>Verbinden...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1302"/>
        <source>Clear Limits</source>
        <translation>Limits löschen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1187"/>
        <source>Yaw -</source>
        <translation>Drehung -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1196"/>
        <source>Yaw +</source>
        <translation>Drehung +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1205"/>
        <source>Pitch +</source>
        <translation>Neigung +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1214"/>
        <source>Pitch -</source>
        <translation>Neigung -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1223"/>
        <source>Manual</source>
        <translation>Anleitung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1232"/>
        <source>View Log...</source>
        <translation>Log anzeigen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1241"/>
        <source>About Papywizard</source>
        <translation>Über Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1250"/>
        <source>About Qt</source>
        <translation>Über Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1259"/>
        <source>Load Style Sheet...</source>
        <translation>Lade Style Sheet...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1277"/>
        <source>Goto Initial...</source>
        <translation>Gehe zur Ausgangsposition...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1268"/>
        <source>Goto Reference...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1286"/>
        <source>Plugins...</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="589"/>
        <source>Total fov (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="646"/>
        <source>Nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="484"/>
        <source>Corner 0 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="538"/>
        <source>Corner 1 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="965"/>
        <source>Start (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="1019"/>
        <source>End (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1297"/>
        <source>Suspend Spy</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MerlinOrionAxisController</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="483"/>
        <source>Alternate drive</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="485"/>
        <source>Inertia angle</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="482"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PixOrbAxisController</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="408"/>
        <source>Speed table index</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="410"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="411"/>
        <source>Axis with break</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="203"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Bluetooth nicht erkannt</translation>
    </message>
</context>
<context>
    <name>PololuServoAxisController</name>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="443"/>
        <source>Speed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="445"/>
        <source>Servo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="446"/>
        <source>Channel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="449"/>
        <source>Direction</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="451"/>
        <source>Angle for 1ms</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="453"/>
        <source>Neutral position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="94"/>
        <source>forward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="95"/>
        <source>reverse</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PololuServoShutterController</name>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="510"/>
        <source>Servo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="511"/>
        <source>Channel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="513"/>
        <source>Value off</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="515"/>
        <source>Value on</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="387"/>
        <source>Step</source>
        <translation>Schritt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="458"/>
        <source>Resume</source>
        <translation>Fortsetzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="471"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="462"/>
        <source>Paused</source>
        <translation>pausiert</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="483"/>
        <source>Finished</source>
        <translation>Beendet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="485"/>
        <source>Canceled</source>
        <translation>Abgebrochen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="487"/>
        <source>Failed</source>
        <translation>Fehlgeschlagen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="494"/>
        <source>Waiting</source>
        <translation>Warte</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="540"/>
        <source>Moving</source>
        <translation>Kopf fährt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="542"/>
        <source>Stabilization</source>
        <translation>Stabilisierung</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="544"/>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="547"/>
        <source>Shutter - Picture</source>
        <translation>Auslöser - Bild</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="678"/>
        <source>Stop</source>
        <translation type="unfinished">Stop</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="489"/>
        <source>Finish</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="588"/>
        <source>Idle</source>
        <translation type="unfinished">Warte</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="548"/>
        <source>Shutter failed while mirror locking up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="563"/>
        <source>Shutter failed while shooting</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SimulationAxisController</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="220"/>
        <source>Speed</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SimulationShutterController</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="265"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="267"/>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="269"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>StandardShutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="63"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="65"/>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="67"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="69"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="70"/>
        <source>Pulse width high</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="72"/>
        <source>Pulse width low</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="125"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="127"/>
        <source>LRD file path</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>UrsaMinorBt2ShutterController</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="153"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="158"/>
        <source>Maintain focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="154"/>
        <source>Enable</source>
        <translation type="unfinished">Aktivieren</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="156"/>
        <source>Pulse width</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>UrsaMinorUsbShutterController</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="116"/>
        <source>Trigger line</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="118"/>
        <source>Line inverted</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="100"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="129"/>
        <source>Question</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation>Bluetooth Auswahl</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Konfiguration</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Aufnahme</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Geräte-Ausrichtung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>hoch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation>links</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation>rechts</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>runter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Ausrichtung der Kamera</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>Hoch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>Quer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>Eigene</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Stab. Pause</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="152"/>
        <source> s</source>
        <translation> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation>Raster</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation>Überlappung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="195"/>
        <source> %</source>
        <translation> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="217"/>
        <source>Start from</source>
        <translation>Start bei</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="260"/>
        <source>Initial direction</source>
        <translation>Anfangsrichtung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>yaw</source>
        <translation>drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>pitch</source>
        <translation>neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="290"/>
        <source>CR</source>
        <translation>CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="473"/>
        <source> x</source>
        <translation> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="403"/>
        <source>3:2</source>
        <translation>3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="408"/>
        <source>4:3</source>
        <translation>4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="413"/>
        <source>5:4</source>
        <translation>5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="418"/>
        <source>16:9</source>
        <translation>16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="426"/>
        <source> Mpx</source>
        <translation> Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="325"/>
        <source>rectilinear</source>
        <translation>rechtwinklig</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="330"/>
        <source>fisheye</source>
        <translation>rischauge</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="448"/>
        <source> mm</source>
        <translation> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="650"/>
        <source>Data</source>
        <translation>Daten</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="658"/>
        <source>Data directory</source>
        <translation>Daten-Verzeichnis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="674"/>
        <source>Data file</source>
        <translation>Datei</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="690"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation>%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="884"/>
        <source>Enable</source>
        <translation>Aktivieren</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="713"/>
        <source>Title</source>
        <translation>Titel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="742"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="771"/>
        <source>Comment</source>
        <translation>Bemerkung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="824"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="835"/>
        <source>Start after</source>
        <translation>Start nach</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="858"/>
        <source>Repeat</source>
        <translation>Wiederhole</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="894"/>
        <source>Repeat every</source>
        <translation>Wiederhole alle</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="939"/>
        <source>HH:mm:ss</source>
        <translation>HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="962"/>
        <source>Misc</source>
        <translation>Verschiedenes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="970"/>
        <source>Logger level</source>
        <translation>Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="987"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="992"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="997"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1002"/>
        <source>warning</source>
        <translation>warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1007"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1012"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1017"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="386"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Sensor (Faktor, Verhältnis)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="351"/>
        <source>Sensor resolution</source>
        <translation>Sensorauflösung MP</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="338"/>
        <source>Optical multiplier</source>
        <translation>Optischer Faktor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="300"/>
        <source>Camera/lens</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="308"/>
        <source>Lens (type, focal)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="498"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="506"/>
        <source>Yaw</source>
        <translation>Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="519"/>
        <source>Pitch</source>
        <translation>Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="570"/>
        <source>Configure...</source>
        <translation type="unfinished">Einstellungen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="546"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="237"/>
        <source>top-left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="242"/>
        <source>top-right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>bottom-left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="252"/>
        <source>bottom-right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="952"/>
        <source>Reverse direction before repeat</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>Über Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>Allgemein</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="72"/>
        <source>Papywizard x.x.x</source>
        <translation>Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard ist eine Panoramakopf-kontrollsoftware, entwickelt für den Merlin/Orion-Astronomie-Kopfaber auch für andere.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation>© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="130"/>
        <source>http://www.papywizard.org</source>
        <translation>http://www.papywizard.org</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Mitarbeit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="189"/>
        <source>License</source>
        <translation>Lizenz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="195"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.￼

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.￼

￼In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.￼

￼The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation>Logdateien löschen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation>Log anzeigen</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="219"/>
        <source>Plugins selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation>Anz. Aufnahmen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation type="unfinished">Anz. aufnahmen</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="14"/>
        <source>Plugin dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="34"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pluginsStatusDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="14"/>
        <source>Plugins Status</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished">Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished">Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="49"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="65"/>
        <source>Init</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="81"/>
        <source>Connect</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>BT Geräteadresse</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="199"/>
        <source>00:50:C2:58:55:B9</source>
        <translation>00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="209"/>
        <source>Choose...</source>
        <translation>Wähle...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="219"/>
        <source>Serial port</source>
        <translation>Serieller Anschluss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="235"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="248"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="264"/>
        <source>locahost</source>
        <translation>localhost</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Aufnahme</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation>Gesamt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation>Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation>Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation>Aktuell</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="259"/>
        <source>--/--</source>
        <translation>--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation>Nächste</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="341"/>
        <source>Idle</source>
        <translation>Warte</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="428"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="471"/>
        <source>%p%</source>
        <translation>%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="511"/>
        <source>Data</source>
        <translation>Daten</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="540"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="566"/>
        <source>Step-by-step</source>
        <translation>Einzelschritt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="599"/>
        <source>Start</source>
        <translation>Start</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="628"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="657"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation>Gesamt Fov</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation>Gesamt fov</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
</TS>
