<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="it">
<defaultcodec></defaultcodec>
<context>
    <name>BluetoothChooserController</name>
    <message>
        <location filename="papywizard/controller/bluetoothChooserController.py" line="139"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Bluetooth non rilevato</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="179"/>
        <source>Wrong value for camera orientation</source>
        <translation>Valore errato dell&apos;orientamento della camera</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="180"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Impossibile impostare l&apos;orientamento della fotocamera a &apos;personalizzato&apos; mentre sei in modo &apos;mosaico&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="203"/>
        <source>Wrong value for lens type</source>
        <translation>Valore errato del tipo di obbiettivo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="204"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Impossibile impostare il tipo di obbiettivo a &apos;fisheye&apos; mentre sei in modo &apos;mosaico&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="279"/>
        <source>Choose Data Storage dir</source>
        <translation>Scegli Dir per salvataggio dati</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="348"/>
        <source>Here goes the title</source>
        <translation>Ecco il titolo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="352"/>
        <source>Here goes the location</source>
        <translation>Ecco la posizione</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="356"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Generato da Papywizard %(version)s</translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>Dialog</name>
    <message>
        <location filename="papywizard/view/bluetoothChooserDialog.ui" line="13"/>
        <source>Bluetooth chooser</source>
        <translation>Scelta Bluetooth</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/totalFovDialog.ui" line="68"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="13"/>
        <source>About Papywizard</source>
        <translation>Info Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="30"/>
        <source>General</source>
        <translation>Generale</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="71"/>
        <source>Papywizard x.x.x</source>
        <translation>Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="83"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard è un software per gestire una testa panoramica, principalmente sviluppato per la testa astronomica Merlin/Orion, ma utilizzabile anche con altre teste panoramiche.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/helpAboutDialog.ui" line="107"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation>© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="129"/>
        <source>http://trac.gbiloba.org/papywizard</source>
        <translation>http://trac.gbiloba.org/papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="145"/>
        <source>Credits</source>
        <translation>Crediti</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="153"/>
        <source>Written by</source>
        <translation>Scritto da</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/helpAboutDialog.ui" line="178"/>
        <source>Frédéric Mantegazza</source>
        <translation>Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="188"/>
        <source>Translated by</source>
        <translation>Tradotto da</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/helpAboutDialog.ui" line="207"/>
        <source>Frédéric Mantegazza (fr)
Jo Lutum (de)
Maciej Dworak (pl)
Antonio Bruno (it)</source>
        <translation>Frédéric Mantegazza (fr)
Jo Lutum (de)
Maciej Dworak (pl)
Antonio Bruno (it)</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="220"/>
        <source>Graphics by</source>
        <translation>Grafica</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/helpAboutDialog.ui" line="239"/>
        <source>Hubert Pawlowski
Frédéric Mantegazza</source>
        <translation>Hubert Pawlowski
Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="253"/>
        <source>License</source>
        <translation>Licenza</translation>
    </message>
    <message>
        <location filename="papywizard/view/helpAboutDialog.ui" line="259"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message>
        <location filename="papywizard/view/totalFovDialog.ui" line="48"/>
        <source>Total Fov</source>
        <translation>Fov totale</translation>
    </message>
    <message>
        <location filename="papywizard/view/totalFovDialog.ui" line="28"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/totalFovDialog.ui" line="38"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="357"/>
        <source>Manual speed set to slow</source>
        <translation>Velocità manuale settata lenta</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="375"/>
        <source>Manual speed set to normal</source>
        <translation>Velocità manuale settata normale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="378"/>
        <source>Fast manual speed</source>
        <translation>Velocità manuale rapida</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="378"/>
        <source>This can be dangerous for the hardware!</source>
        <translation>Può danneggiare l&apos;hardware!</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="385"/>
        <source>Manual speed set to fast</source>
        <translation>Velocità manuale settata &apos;rapida&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="414"/>
        <source>About to Quit</source>
        <translation>In chiusura</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="414"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Sei sicuro di volere chiudere Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="473"/>
        <source>Import Preset File</source>
        <translation>Importa file di preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="475"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML files (*.xml);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="482"/>
        <source>Load Style Sheet</source>
        <translation>Carica foglio di stile</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="484"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS files (*.css);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="499"/>
        <source>Yaw - limit set</source>
        <translation>Limite fissato Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="505"/>
        <source>Yaw + limit set</source>
        <translation>Limite fissato Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="511"/>
        <source>Pitch + limit set</source>
        <translation>Limite fissato Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="517"/>
        <source>Pitch - limit set</source>
        <translation>Limite fissato Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="522"/>
        <source>Limits cleared</source>
        <translation>Limiti azzerati</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="526"/>
        <source>Goto home position...</source>
        <translation>Vai alla posizione di partenza...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="555"/>
        <source>Operation aborted</source>
        <translation>Operazione abortita</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="539"/>
        <source>Home position reached</source>
        <translation> Posizione di partenza raggiunta</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="545"/>
        <source>Goto initial position...</source>
        <translation>Vai alla posizione iniziale...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="559"/>
        <source>Initial position reached</source>
        <translation>Posizione iniziale raggiunta</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="608"/>
        <source>Yaw start set from current position</source>
        <translation>Inizio Yaw da posizione corrente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="615"/>
        <source>Pitch start set from current position</source>
        <translation>Inizio Pitch da posizione corrente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="622"/>
        <source>Yaw end set from current position</source>
        <translation>Fine Yaw da posizione corrente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="629"/>
        <source>Pitch end set from current position</source>
        <translation>Fine Pitch da posizione corrente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="727"/>
        <source>Yaw/pitch start set from current position</source>
        <translation>Inizio Yaw/pitch fissato da posizione attuale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="735"/>
        <source>Yaw/pitch end set from current position</source>
        <translation>Fine Yaw/pitch fissata da posizione attuale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="748"/>
        <source>Field of view set to user value</source>
        <translation>Ampiezza campo visivo impostata dall&apos;utente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="761"/>
        <source>Number of pictures set to user value</source>
        <translation>Numero di immagini impostato dall&apos;utente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="769"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Sto aprendo il menu di configurazione. Attendere prego...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="804"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Sto preparandomi a scattare. Attendere prego...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="848"/>
        <source>Can&apos;t import preset file</source>
        <translation>Impossibile importare il file di preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="866"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Impossibile caricare il foglio di stile</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="876"/>
        <source>Connecting to real hardware...</source>
        <translation>Sto connettendomi all&apos;hardware...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="897"/>
        <source>Now connected to real hardware</source>
        <translation>Ora connesso all&apos;hardware</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="901"/>
        <source>Connect to hardware failed</source>
        <translation>Connessione all&apos;hardware non riuscita</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="902"/>
        <source>Can&apos;t connect to hardware</source>
        <translation>Non riesco a connettere l&apos;hardware</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="915"/>
        <source>Now in simulation mode</source>
        <translation>Ora sei in modo simulazione</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="661"/>
        <source>Reference set at current position</source>
        <translation>Origine fissata a posizione attuale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="528"/>
        <source>Goto home position</source>
        <translation>Vai alla  posizione di partenza</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="548"/>
        <source>Please wait...</source>
        <translation>Prego attendi...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="548"/>
        <source>Goto initial position</source>
        <translation>Vai alla posizione iniziale</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="22"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="75"/>
        <source>Mosaic</source>
        <translation>Mosaico</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="633"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="649"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/mainWindow.ui" line="125"/>
        <source>Start (°)</source>
        <translation>Partenza (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="681"/>
        <source>--</source>
        <translation>--</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/mainWindow.ui" line="179"/>
        <source>End (°)</source>
        <translation>Fine (°)</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/mainWindow.ui" line="230"/>
        <source>Total Fov (°)</source>
        <translation>Fov totale (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="287"/>
        <source>Nb Picts</source>
        <translation>N° immagini</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="344"/>
        <source>Real overlap (%)</source>
        <translation>Sovrapposizione reale (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="407"/>
        <source>Resolution (px)</source>
        <translation>Risoluzione (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="467"/>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="490"/>
        <source>Name</source>
        <translation>Nome</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="534"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Assicurati che il preset selezionato sia compatibile con la tua camera e focale dell&apos;obiettivo (Errore).</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="556"/>
        <source>Timelapse</source>
        <translation>Timelapse (foto in successione)</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="566"/>
        <source>Not yet implemented</source>
        <translation>Non ancora implementato</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="595"/>
        <source>Move</source>
        <translation>Muovi</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="847"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="883"/>
        <source>Configure...</source>
        <translation>Configura...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="906"/>
        <source>Shoot...</source>
        <translation>Scatto...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="942"/>
        <source>File</source>
        <translation>File</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="951"/>
        <source>Hardware</source>
        <translation>Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="955"/>
        <source>Set Limit</source>
        <translation>Imposta limiti</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="972"/>
        <source>Help</source>
        <translation>Aiuto</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="996"/>
        <source>Quit</source>
        <translation>Quit / Spegni</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="999"/>
        <source>Ctrl+Q</source>
        <translation>Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1008"/>
        <source>Import Preset File...</source>
        <translation>Importa file di preset...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1016"/>
        <source>Connect...</source>
        <translation>Connessione...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1025"/>
        <source>Clear Limits</source>
        <translation>Azzara limiti</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1034"/>
        <source>Yaw -</source>
        <translation>Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1043"/>
        <source>Yaw +</source>
        <translation>Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1052"/>
        <source>Pitch +</source>
        <translation>Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1061"/>
        <source>Pitch -</source>
        <translation>Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1070"/>
        <source>Manual</source>
        <translation>Manuale</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1079"/>
        <source>View Log...</source>
        <translation>Guarda log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1088"/>
        <source>About Papywizard</source>
        <translation>Info Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1097"/>
        <source>About Qt</source>
        <translation>Info Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1106"/>
        <source>Load Style Sheet...</source>
        <translation>Carico il foglio di stile...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1115"/>
        <source>Goto Home...</source>
        <translation>Torna  alla posizione di partenza...</translation>
    </message>
    <message>
        <location filename="papywizard/view/mainWindow.ui" line="1124"/>
        <source>Goto Initial...</source>
        <translation>Torna alla posizione iniziale...</translation>
    </message>
</context>
<context>
    <name>SerialDriver</name>
    <message>
        <location filename="papywizard/hardware/serialDriver.py" line="100"/>
        <source>SerialDriver not initialized</source>
        <translation>Driver Seriale non inizializzato</translation>
    </message>
    <message>
        <location filename="papywizard/hardware/serialDriver.py" line="120"/>
        <source>Timeout while reading on serial bus</source>
        <translation>Timeout durante la lettura del bus seriale</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="404"/>
        <source>Step</source>
        <translation>Passo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="499"/>
        <source>Resume</source>
        <translation>Ripristina</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="512"/>
        <source>Pause</source>
        <translation>Pausa</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="503"/>
        <source>Paused</source>
        <translation>In pausa</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="524"/>
        <source>Finished</source>
        <translation>Finito</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="526"/>
        <source>Canceled</source>
        <translation>Cancellato</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="528"/>
        <source>Failed</source>
        <translation>Fallito, non riuscito</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="538"/>
        <source>Waiting</source>
        <translation>Attenzione</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="583"/>
        <source>Moving</source>
        <translation>In movimento</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="585"/>
        <source>Stabilization</source>
        <translation>Stabilizzazione</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="587"/>
        <source>Mirror lockup</source>
        <translation>Blocco dello specchio </translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="590"/>
        <source>Shutter - Picture</source>
        <translation>Scatto - Immagine</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="16"/>
        <source>Configuration</source>
        <translation>Configuazione</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="36"/>
        <source>Shooting</source>
        <translation>Scatto</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="44"/>
        <source>Head orientation</source>
        <translation>Orientamento testa</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="61"/>
        <source>up</source>
        <translation>su</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="66"/>
        <source>left</source>
        <translation>sinistra</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="71"/>
        <source>right</source>
        <translation>destrat</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="76"/>
        <source>down</source>
        <translation>giu</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="84"/>
        <source>Camera orientation</source>
        <translation>Orientamento camera</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="101"/>
        <source>portrait</source>
        <translation>portrait</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="106"/>
        <source>landscape</source>
        <translation>landscape</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="111"/>
        <source>custom</source>
        <translation>personale</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/configDialog.ui" line="122"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="138"/>
        <source>Stabilization delay</source>
        <translation>Tempo di stabilizzazione</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="307"/>
        <source> s</source>
        <translation> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="173"/>
        <source>Mosaic</source>
        <translation>Mosaico</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="181"/>
        <source>Overlap</source>
        <translation>Sovrapposizione</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="194"/>
        <source> %</source>
        <translation> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="213"/>
        <source>Start from</source>
        <translation>Parti da</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="230"/>
        <source>start</source>
        <translation>Partenza</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="235"/>
        <source>end</source>
        <translation>fine</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="243"/>
        <source>Initial direction</source>
        <translation>Dirazione iniziale</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="260"/>
        <source>yaw</source>
        <translation>yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="265"/>
        <source>pitch</source>
        <translation>pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="273"/>
        <source>CR</source>
        <translation>CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="283"/>
        <source>Camera</source>
        <translation>Camera</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="294"/>
        <source>Time value</source>
        <translation>Tempo</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="326"/>
        <source>Bracketing</source>
        <translation>Bracketing</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="353"/>
        <source>exposure</source>
        <translation>Esposizione</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="358"/>
        <source>focus</source>
        <translation>fuoco</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="363"/>
        <source>white balance</source>
        <translation>bilanciamento del bianco</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="368"/>
        <source>movement</source>
        <translation>movimento</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="623"/>
        <source> x</source>
        <translation> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="415"/>
        <source>3:2</source>
        <translation>3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="420"/>
        <source>4:3</source>
        <translation>4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="425"/>
        <source>5:4</source>
        <translation>5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="430"/>
        <source>16:9</source>
        <translation>16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="502"/>
        <source> Mpx</source>
        <translation> Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="463"/>
        <source> ms</source>
        <translation> ms</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="482"/>
        <source>Pulse width (high/low)</source>
        <translation>Larghezza di impulso (alta/bassa) </translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="495"/>
        <source>Mirror lockup</source>
        <translation>Blocco dello specchio </translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="534"/>
        <source>Lens</source>
        <translation>Obiettivo</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="542"/>
        <source>Type</source>
        <translation>Tipo</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="559"/>
        <source>rectilinear</source>
        <translation>rettilineare</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="564"/>
        <source>fisheye</source>
        <translation>fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="572"/>
        <source>Focal</source>
        <translation>Lunghezza focale</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="585"/>
        <source> mm</source>
        <translation> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="648"/>
        <source>Hardware</source>
        <translation>Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="656"/>
        <source>Driver</source>
        <translation>Driver</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="673"/>
        <source>bluetooth</source>
        <translation>bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="678"/>
        <source>serial</source>
        <translation>seriale</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="683"/>
        <source>ethernet</source>
        <translation>ethernet</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="691"/>
        <source>BT device address</source>
        <translation>Indirizzo del BT</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="704"/>
        <source>00:50:C2:58:55:B9</source>
        <translation>00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="714"/>
        <source>Choose...</source>
        <translation>Scegli...</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="724"/>
        <source>Serial port</source>
        <translation>Porta seriale</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="740"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="753"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="769"/>
        <source>locahost</source>
        <translation>locahost</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="795"/>
        <source>Auto-connect</source>
        <translation>Connessione Automatica</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="805"/>
        <source>Data</source>
        <translation>Dati</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="813"/>
        <source>Data directory</source>
        <translation>Cartella dati</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="826"/>
        <source>Data file</source>
        <translation>File di dati</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="839"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation>%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1003"/>
        <source>Enable</source>
        <translation>Abilita</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="856"/>
        <source>Title</source>
        <translation>Titolo</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="879"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="902"/>
        <source>Comment</source>
        <translation>Commento</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="952"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="960"/>
        <source>Start after</source>
        <translation>Parti dopo</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="980"/>
        <source>Repeat</source>
        <translation>Ripeti</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1010"/>
        <source>Repeat every</source>
        <translation>Ripeti ogni</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1049"/>
        <source>HH:mm:ss</source>
        <translation>HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1062"/>
        <source>Misc</source>
        <translation>Misc</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1070"/>
        <source>Logger level</source>
        <translation>Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1087"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1092"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1097"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1102"/>
        <source>warning</source>
        <translation>avvertimento</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1107"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1112"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="1117"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="376"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Sensore (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="518"/>
        <source>Sensor resolution</source>
        <translation>Risoluzione sensore</translation>
    </message>
    <message>
        <location filename="papywizard/view/configDialog.ui" line="607"/>
        <source>Optical multiplier</source>
        <translation>Fattore di moltiplicazione ottica</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/loggerDialog.ui" line="141"/>
        <source>Clear log</source>
        <translation>Azzera log</translation>
    </message>
    <message>
        <location filename="papywizard/view/loggerDialog.ui" line="148"/>
        <source>Save log</source>
        <translation>Salva log</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/nbPictsDialog.ui" line="48"/>
        <source>Nb Picts</source>
        <translation>N° immagini</translation>
    </message>
    <message>
        <location filename="papywizard/view/nbPictsDialog.ui" line="28"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/nbPictsDialog.ui" line="38"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="16"/>
        <source>Shooting</source>
        <translation>Scatto</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="104"/>
        <source>Total</source>
        <translation>Totale</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="114"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="124"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="134"/>
        <source>Current</source>
        <translation>Attuale</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="258"/>
        <source>--/--</source>
        <translation>--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="198"/>
        <source>Next</source>
        <translation>Prossimo</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="337"/>
        <source>Idle</source>
        <translation>Idle</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="424"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="467"/>
        <source>%p%</source>
        <translation>%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="507"/>
        <source>Data</source>
        <translation>Dati</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="536"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="562"/>
        <source>Step-by-step</source>
        <translation>Passo passo</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="595"/>
        <source>Start</source>
        <translation>Inizia</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="624"/>
        <source>Pause</source>
        <translation>Pausa</translation>
    </message>
    <message>
        <location filename="papywizard/view/shootDialog.ui" line="653"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
</context>
</TS>
