<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="cs_CZ">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="139"/>
        <source>Abort</source>
        <translation>Zrušit</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="177"/>
        <source>Wrong value for camera orientation</source>
        <translation>Špatná hodnota pro orientaci fotoaparátu</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="177"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>V režimu &apos;Mosaika&apos; nelze nastavit orientaci fotoaparátu na &apos;vlastní&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="191"/>
        <source>Wrong value for lens type</source>
        <translation>Špatný typ objektivu</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="191"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>V režimu &apos;Mosaika&apos; nelze nastavit typ objektivu na rybí oko</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="235"/>
        <source>Choose Data Storage dir</source>
        <translation>Vyberte adresář pro ukládání souborů</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="330"/>
        <source>Here goes the title</source>
        <translation>Sem přijde nadpis</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="334"/>
        <source>Here goes the location</source>
        <translation>Sem přijde umístění</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="338"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Uložil Papywizard %(verze)s</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="110"/>
        <source>Error</source>
        <translation>Chyba</translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="119"/>
        <source>Exception</source>
        <translation>Vyjímka</translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="92"/>
        <source>Info</source>
        <translation>Informace</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="317"/>
        <source>Manual speed set to slow</source>
        <translation>Manuální rychlost je pomalá</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="333"/>
        <source>Manual speed set to normal</source>
        <translation>Manuální rychlost je bežná</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="339"/>
        <source>Manual speed set to fast</source>
        <translation>Manuální rychlost je velká</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="345"/>
        <source>About to Quit</source>
        <translation>Ukončení</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="345"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Opravdu chcete ukončit Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="361"/>
        <source>Import Preset File</source>
        <translation>Importovat soubor předvoleb</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="361"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML soubory (*.xml);;Všechny soubory (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="370"/>
        <source>Load Style Sheet</source>
        <translation>Nahrát styl</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="370"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS soubory (*.css);;Všechny soubory (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="388"/>
        <source>Yaw - limit set</source>
        <translation>Natočení:záporný limit nastaven</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="394"/>
        <source>Yaw + limit set</source>
        <translation>Natočení:kladný limit nastaven</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="400"/>
        <source>Pitch + limit set</source>
        <translation>Naklonění:kladný limit nastaven</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="406"/>
        <source>Pitch - limit set</source>
        <translation>Naklonění:záporný limit nastaven</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="411"/>
        <source>Limits cleared</source>
        <translation>Limity odstraněny</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="415"/>
        <source>Goto reference position...</source>
        <translation>Jít na referenční bod...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="417"/>
        <source>Goto reference position</source>
        <translation>Jde na referenční bod</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="436"/>
        <source>Please wait...</source>
        <translation>Vyčkejte prosím...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="442"/>
        <source>Operation aborted</source>
        <translation>Akce zrušena</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="427"/>
        <source>Reference position reached</source>
        <translation>Referenční bod dosažen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="432"/>
        <source>Goto initial position...</source>
        <translation>Jít na výchozí bod...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="436"/>
        <source>Goto initial position</source>
        <translation>Jde na výchozí bod</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="446"/>
        <source>Initial position reached</source>
        <translation>Výchozí bod dosažen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="503"/>
        <source>Yaw corner 0 set from current position</source>
        <translation>Natočení rohu 0 nastaveno dle současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="511"/>
        <source>Pitch corner 0 set from current position</source>
        <translation>Naklonění rohu 0 nastaveno dle současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="527"/>
        <source>Yaw corner 1 set from current position</source>
        <translation>Natočení rohu 1 nastaveno dle současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="535"/>
        <source>Pitch corner 1 set from current position</source>
        <translation>Naklonění rohu 1 nastaveno dle současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="559"/>
        <source>Reference set at current position</source>
        <translation>Referenční bod nastaven dle současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="495"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation>Natočení/naklonění rohu 0 nastaveny ze současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="519"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation>Natočení/naklonění rohu 1 nastaveny ze současné pozice</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="615"/>
        <source>Field of view set to user value</source>
        <translation>Zorný úhel nastaven na hodnotu od uživatele</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="626"/>
        <source>Number of pictures set to user value</source>
        <translation>Počet obrázků nastavenna hodnotu od uživatele</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="631"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation>Otvírám okno rozšíření. Vyčkejte prosím...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="648"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Otvírám konfigurační dialog. Vyčkejte prosím...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="681"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Otvírám okno snímání. Vyčkejte prosím...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="727"/>
        <source>Can&apos;t import preset file</source>
        <translation>Nemohu importovat předvolby</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="743"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Nemohu nahrát styl</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="804"/>
        <source>Starting connection. Please wait...</source>
        <translation>Připojuji se. Vyčkejte prosím...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="827"/>
        <source>Connection started</source>
        <translation>Připojeno</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="832"/>
        <source>Connection failed to start</source>
        <translation>Připojení se nezdařilo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="844"/>
        <source>Stopping connection. Please wait...</source>
        <translation>Zastavuji připojení. Vyčkejte prosím...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="857"/>
        <source>Connection stopped</source>
        <translation>Připojení zastaveno</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Posun</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="452"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="468"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="348"/>
        <source>Configure...</source>
        <translation>Nastavit...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="371"/>
        <source>Shoot...</source>
        <translation>Fotografovat...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="438"/>
        <source>Mosaic</source>
        <translation>Mosaika</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="487"/>
        <source>Corner 0 (°)</source>
        <translation>Roh 0 (°)</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="554"/>
        <source>Corner 1 (°)</source>
        <translation>Roh 1 (°)</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="615"/>
        <source>Total fov (°)</source>
        <translation>Zorný úhel (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="676"/>
        <source>Nb picts</source>
        <translation>Počet obrázků</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="737"/>
        <source>Real overlap (%)</source>
        <translation>Překryv (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="800"/>
        <source>Resolution (px)</source>
        <translation>Rozlišení (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="864"/>
        <source>Preset</source>
        <translation>Předvolba</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="883"/>
        <source>Name</source>
        <translation>Název</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="927"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Ujistěte se, že předvolby odpovídají vašemu fotoaparátu a objektivu.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="969"/>
        <source>File</source>
        <translation>Soubor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="978"/>
        <source>Hardware</source>
        <translation>Zařízení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="982"/>
        <source>Set Limit</source>
        <translation>Nastavit limity</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1001"/>
        <source>Help</source>
        <translation>Nápověda
</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1025"/>
        <source>Quit</source>
        <translation>Ukončit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1037"/>
        <source>Import Preset File...</source>
        <translation>Přidat sooubor předvoleb...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1045"/>
        <source>Connect...</source>
        <translation>Připojit...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1169"/>
        <source>Clear Limits</source>
        <translation>Odebrat limity</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1054"/>
        <source>Yaw -</source>
        <translation>Natočení -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1063"/>
        <source>Yaw +</source>
        <translation>Natočení +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1072"/>
        <source>Pitch +</source>
        <translation>Naklonění +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1081"/>
        <source>Pitch -</source>
        <translation>Naklonění -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1090"/>
        <source>Manual</source>
        <translation>Návod</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1099"/>
        <source>View Log...</source>
        <translation>Zobrazit záznamy...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1108"/>
        <source>About Papywizard</source>
        <translation>Co je Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1117"/>
        <source>About Qt</source>
        <translation>Co je Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1126"/>
        <source>Load Style Sheet...</source>
        <translation>Nahrát styl...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1135"/>
        <source>Goto Reference...</source>
        <translation>Jít na referenční bod...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1144"/>
        <source>Goto Initial...</source>
        <translation>Jít na výchozí bod...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1153"/>
        <source>Plugins...</source>
        <translation>Rozšíření...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1164"/>
        <source>Suspend Spy</source>
        <translation>Pozastavit a prozkoumat</translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="209"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Nemohu prohledat bluetooth</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="290"/>
        <source>Step</source>
        <translation>Krok</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="361"/>
        <source>Resume</source>
        <translation>Obnovit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="374"/>
        <source>Pause</source>
        <translation>Počkat</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="365"/>
        <source>Paused</source>
        <translation>Čeká</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="386"/>
        <source>Finished</source>
        <translation>Ukončeno</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="388"/>
        <source>Canceled</source>
        <translation>Zrušeno</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="390"/>
        <source>Failed</source>
        <translation>Selhalo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="392"/>
        <source>Finish</source>
        <translation>Ukončit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="397"/>
        <source>Waiting</source>
        <translation>Čeká</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="443"/>
        <source>Moving</source>
        <translation>Přesouvá se</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="445"/>
        <source>Stabilization</source>
        <translation>Stabilizuje se</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="447"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="450"/>
        <source>Shutter - Picture</source>
        <translation>Spoušť - snímá se</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="491"/>
        <source>Idle</source>
        <translation>Nečinný</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="580"/>
        <source>Stop</source>
        <translation>Zastaveno</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="549"/>
        <source>Shutter failed while mirror locking up</source>
        <translation>Fotografování selhalo při předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="564"/>
        <source>Shutter failed while shooting</source>
        <translation>Fotografování selhalo během snímání</translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Vyberte cestu k programu...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE soubory (*.exe);;Všechny soubory (*)</translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="101"/>
        <source>Warning</source>
        <translation>Varování</translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="130"/>
        <source>Question</source>
        <translation>Dotaz</translation>
    </message>
</context>
<context>
    <name>abstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="61"/>
        <source>Main</source>
        <translation>Hlavní</translation>
    </message>
</context>
<context>
    <name>axisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="60"/>
        <source>Low limit</source>
        <translation>Nejnižší hodnota</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="61"/>
        <source>High limit</source>
        <translation>Nejvyšší hodnota</translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation>Výběr Bluetooth</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Fotografování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Orientace hlavy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>nahoru</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation>doleva</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation>doprava</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>dolů</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Orientace fotoaparátu</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>portrét</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>krajina</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>jiné</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Čas pro stabilizaci</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation>Mozaika</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation>Překryv</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="217"/>
        <source>Start from</source>
        <translation>Začít od</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="237"/>
        <source>top-left</source>
        <translation>levý horní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="242"/>
        <source>top-right</source>
        <translation>pravý horní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>bottom-left</source>
        <translation>levý dolní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="252"/>
        <source>bottom-right</source>
        <translation>pravý dolní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="260"/>
        <source>Initial direction</source>
        <translation>Výchozí pohyb</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>yaw</source>
        <translation>natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>pitch</source>
        <translation>naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="290"/>
        <source>CR</source>
        <translation>obracet se</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="300"/>
        <source>Camera/lens</source>
        <translation>Fotoaparát/objektiv</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="308"/>
        <source>Lens (type, focal)</source>
        <translation>Objektiv(typ, ohnisko)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="325"/>
        <source>rectilinear</source>
        <translation>rectilineární</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="330"/>
        <source>fisheye</source>
        <translation>rybí oko</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="338"/>
        <source>Optical multiplier</source>
        <translation>Optické zvětšení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="351"/>
        <source>Sensor resolution</source>
        <translation>Rozlišení senzoru</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="386"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Snímač(ořez, poměr)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="498"/>
        <source>Plugins</source>
        <translation>Rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="506"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="519"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="570"/>
        <source>Configure...</source>
        <translation>Nastavit...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="546"/>
        <source>Shutter</source>
        <translation>Spoušť</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="650"/>
        <source>Data</source>
        <translation>Soubory</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="658"/>
        <source>Data directory</source>
        <translation>Výchozí adresář</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="674"/>
        <source>Data file</source>
        <translation>Soubor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="874"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="713"/>
        <source>Title</source>
        <translation>Nadpis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="742"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="771"/>
        <source>Comment</source>
        <translation>Komentář</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="814"/>
        <source>Timer</source>
        <translation>Časovač</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="825"/>
        <source>Start after</source>
        <translation>Začít za</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="848"/>
        <source>Repeat</source>
        <translation>Opakovat</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="884"/>
        <source>Repeat every</source>
        <translation>Opakovat po</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="942"/>
        <source>Reverse direction before repeat</source>
        <translation>Obrátit směr před opakováním</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="952"/>
        <source>Misc</source>
        <translation>Pomocné</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="960"/>
        <source>Logger level</source>
        <translation>Množství hlášení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="977"/>
        <source>trace</source>
        <translation>sledování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="982"/>
        <source>debug</source>
        <translation>kontrolování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="987"/>
        <source>info</source>
        <translation>informace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="992"/>
        <source>warning</source>
        <translation>varování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="997"/>
        <source>error</source>
        <translation>chyby</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1002"/>
        <source>exception</source>
        <translation>vyjímky</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1007"/>
        <source>critical</source>
        <translation>kritické chyby</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
<context>
    <name>dslrRemoteProPlugins</name>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation>Používat seznam
kompenzace expozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="89"/>
        <source>Dry run</source>
        <translation>Ukázkový běh</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="91"/>
        <source>Camera</source>
        <translation>Fotoaparát</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="92"/>
        <source>Output directory</source>
        <translation>Výstupní adresář</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="93"/>
        <source>Choose output directory...</source>
        <translation>Vyberte výstupní adresář...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="94"/>
        <source>File name prefix</source>
        <translation>Předřazená část názvu souborů</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="95"/>
        <source>Camera exposure
compensation list</source>
        <translation>Seznam korekcí expozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Cesta k programu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Vyberte cestu k programu...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE soubory (*.exe);;Všechny soubory (*)</translation>
    </message>
</context>
<context>
    <name>eosUtilityPlugins</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="110"/>
        <source>new</source>
        <translation>nový</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="113"/>
        <source>far</source>
        <translation>vzdálený</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="119"/>
        <source>medium</source>
        <translation>střední</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="109"/>
        <source>old</source>
        <translation>starý</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="114"/>
        <source>near</source>
        <translation>blízký</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="118"/>
        <source>small</source>
        <translation>malý</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="120"/>
        <source>large</source>
        <translation>velký</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Cesta k programu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>EOS Utility version</source>
        <translation>Verze EOS Utility</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="90"/>
        <source>Bracketing type</source>
        <translation>Typ braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>Dry run</source>
        <translation>Ukázkový běh</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="93"/>
        <source>Bulb</source>
        <translation>Dlouhý čas(drženo)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="95"/>
        <source>Base exposure</source>
        <translation>Základní expozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>Focus</source>
        <translation>Ostření</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="99"/>
        <source>Direction</source>
        <translation>Směr</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="100"/>
        <source>Step</source>
        <translation>Krok</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="101"/>
        <source>Step count</source>
        <translation>Počet kroků</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="102"/>
        <source>Nb picts</source>
        <translation>Počet obrázků</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="89"/>
        <source>Bracketing step</source>
        <translation>Krok při braketingu</translation>
    </message>
</context>
<context>
    <name>genericTetheredPlugins</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="76"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="77"/>
        <source>Mirror lockup command</source>
        <translation>Příkaz předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="80"/>
        <source>Shoot command</source>
        <translation>Příkaz fotografování</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="83"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
</context>
<context>
    <name>gphotoBracketPlugins</name>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="91"/>
        <source>Program path</source>
        <translation>Cesta k programu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="92"/>
        <source>Choose program path...</source>
        <translation>Vyberte cestu k programu...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="93"/>
        <source>gphoto2 (gphoto2);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="94"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="95"/>
        <source>Bracketing step</source>
        <translation>Krok při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="96"/>
        <source>Exposure bias</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="97"/>
        <source>Resulting Ev list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="100"/>
        <source>Advanced</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="101"/>
        <source>Bracketing nb picts (+)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="102"/>
        <source>Bracketing step (+)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="103"/>
        <source>Bracketing nb picts (-)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="104"/>
        <source>Bracketing step (-)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="106"/>
        <source>Download</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="107"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="108"/>
        <source>Download directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="109"/>
        <source>Choose download directory...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="111"/>
        <source>Download after</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="112"/>
        <source>Each shot</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="113"/>
        <source>Bracketing sequence</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoBracketPlugins.py" line="114"/>
        <source>Delete camera picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>gphotoPlugins</name>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="160"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="162"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="164"/>
        <source>Bracketing step</source>
        <translation>Krok při braketingu</translation>
    </message>
</context>
<context>
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>Co je Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>Obecné</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard je nástroj pro kontrolu  panoramatických hlav, vyvýjený zejména pro použití astronomických montáží Merlin/Orion, ale využitelný i s jinými hlavami.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Autoři</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="189"/>
        <source>License</source>
        <translation>Licence</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="195"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Napsal:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (jádro)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (rozšíření EOS Utility)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Překlad:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Grafika:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Instalační balíčky:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="14"/>
        <source>Logger</source>
        <translation>Sledování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="145"/>
        <source>Clear log</source>
        <translation>Vymazat záznamy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="152"/>
        <source>Save log</source>
        <translation>Uložit záznamy</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="228"/>
        <source>Plugins selection</source>
        <translation>Výběr rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="228"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation>Než budete moci začít používat Pappywizard, musíte vybrat, jak budete ovládat vaše zařízení.

Po zavření tohoto dialogu budete vyzváni k výběru těchto rozšíření. Jakmile to bude hotové, můžete je nastavit v hlavním dialogu Nastavení</translation>
    </message>
</context>
<context>
    <name>merlinOrionPlugins</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="82"/>
        <source>Hard</source>
        <translation>Pevný</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="83"/>
        <source>Alternate drive</source>
        <translation>Alternativní pohon</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="84"/>
        <source>Inertia angle</source>
        <translation>Neutrální úhel</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation>Počet obrázků</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation>Počet obrázků</translation>
    </message>
</context>
<context>
    <name>nkRemotePlugins</name>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="84"/>
        <source>Program path</source>
        <translation>Cesta k programu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="85"/>
        <source>Choose program path...</source>
        <translation>Vyberte cestu k programu...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="86"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE soubory (*.exe);;Všechny soubory (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="87"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="88"/>
        <source>User exposure
compensation list</source>
        <translation>Používat seznam
kompenzace expozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="89"/>
        <source>Dry run</source>
        <translation>Ukázkový běh</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="91"/>
        <source>Camera</source>
        <translation>Fotoaparát</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="92"/>
        <source>Choose output directory...</source>
        <translation>Vyberte výstupní adresář...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="93"/>
        <source>File name prefix</source>
        <translation>Předřazená část názvu souborů</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="94"/>
        <source>Camera exposure
compensation list</source>
        <translation>Seznam korekcí expozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/nkRemotePlugins.py" line="233"/>
        <source>Output directory</source>
        <translation>Výstupní adresář</translation>
    </message>
</context>
<context>
    <name>panoduinoPlugins</name>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="99"/>
        <source>forward</source>
        <translation>vpřed</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="82"/>
        <source>Speed</source>
        <translation>Rychlost</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="84"/>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="85"/>
        <source>Direction</source>
        <translation>Směr</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="86"/>
        <source>Neutral position</source>
        <translation>Neutrální pozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="87"/>
        <source>Value off</source>
        <translation>Hodnota vypnuta</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="88"/>
        <source>Value on</source>
        <translation>Hodnota zapnuta</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/panoduinoPlugins.py" line="100"/>
        <source>reverse</source>
        <translation>zpět</translation>
    </message>
</context>
<context>
    <name>pixOrbPlugins</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="82"/>
        <source>Speed index</source>
        <translation>Stupeň rychlosti</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="84"/>
        <source>Hard</source>
        <translation>Pevný</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="85"/>
        <source>Axis with break</source>
        <translation>Osa s brzdou</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="86"/>
        <source>Axis accuracy</source>
        <translation>Přesnost osy</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="26"/>
        <source>Plugin dialog</source>
        <translation>Nastavení rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="46"/>
        <source>Main</source>
        <translation>Hlavní</translation>
    </message>
</context>
<context>
    <name>pluginsDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation>Rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation>Spoušť</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation>bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation>sériový port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation>ethernet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation>Ovladače</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>Adresa BT zařízení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="212"/>
        <source>Serial port</source>
        <translation>Sériový port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="241"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet adresa/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="286"/>
        <source>Choose...</source>
        <translation>Vybrat...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="296"/>
        <source>Communication</source>
        <translation>Komunikace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="304"/>
        <source>Timeout</source>
        <translation>Časový limit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="342"/>
        <source>Retry</source>
        <translation>Opakování</translation>
    </message>
</context>
<context>
    <name>pluginsStatusDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="14"/>
        <source>Plugins Status</source>
        <translation>Stav rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="49"/>
        <source>Shutter</source>
        <translation>Spoušť</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="65"/>
        <source>Init</source>
        <translation>Spustit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="81"/>
        <source>Connect</source>
        <translation>Připojit</translation>
    </message>
</context>
<context>
    <name>pololuServoPlugins</name>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="92"/>
        <source>forward</source>
        <translation>vpřed</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="93"/>
        <source>reverse</source>
        <translation>zpět</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="240"/>
        <source>Speed</source>
        <translation>Rychlost</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="305"/>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="244"/>
        <source>Direction</source>
        <translation>Směr</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="246"/>
        <source>Angle for 1ms</source>
        <translation>Úhel za 1 ms</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="248"/>
        <source>Neutral position</source>
        <translation>Neutrální pozice</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="306"/>
        <source>Value off</source>
        <translation>Hodnota vypnuta</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="308"/>
        <source>Value on</source>
        <translation>Hodnota zapnuta</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Snímání</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation>Celkem</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation>Nyní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation>Další</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="341"/>
        <source>Idle</source>
        <translation>Nečinný</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="428"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="514"/>
        <source>Data</source>
        <translation>Ukládání</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="543"/>
        <source>Timer</source>
        <translation>Časovač</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="569"/>
        <source>Step-by-step</source>
        <translation>Krok za krokem</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="602"/>
        <source>Start</source>
        <translation>Začít</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="631"/>
        <source>Pause</source>
        <translation>Počkat</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="660"/>
        <source>Stop</source>
        <translation>Ukončit</translation>
    </message>
</context>
<context>
    <name>simulationPlugins</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="78"/>
        <source>Speed</source>
        <translation>Rychlost</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="80"/>
        <source>Time value</source>
        <translation>Čas</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="81"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="82"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
</context>
<context>
    <name>standardShutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="60"/>
        <source>Time value</source>
        <translation>Čas</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="61"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="62"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="64"/>
        <source>Hard</source>
        <translation>Pevný</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="65"/>
        <source>Pulse width high</source>
        <translation>Délka pulsu - horní</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="66"/>
        <source>Pulse width low</source>
        <translation>Délka pulzu - spodní</translation>
    </message>
</context>
<context>
    <name>timelordPlugins</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="73"/>
        <source>Program path</source>
        <translation>Cesta k programu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="74"/>
        <source>Choose program path...</source>
        <translation>Vyberte cestu k programu...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="75"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE soubory (*.exe);;Všechny soubory (*)</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="76"/>
        <source>LRD file</source>
        <translation>LRD soubor</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="77"/>
        <source>Choose LRD file...</source>
        <translation>Vyberte LRD soubor...</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="78"/>
        <source>LRD files (*.lrd);;All files (*)</source>
        <translation>LRD soubory (*.lrd);;Všechny soubory (*)</translation>
    </message>
</context>
<context>
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation>Celkový zorný úhel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Natočení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Naklonění</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation>Zorný úhel</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
<context>
    <name>ursaMinorBt2Plugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="74"/>
        <source>Focus</source>
        <translation>Ostření</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="75"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="76"/>
        <source>Pulse width</source>
        <translation>Délka pulsu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="77"/>
        <source>Maintain focus</source>
        <translation>Zachová zaostření</translation>
    </message>
</context>
<context>
    <name>ursaMinorUsbPlugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="74"/>
        <source>Trigger line</source>
        <translation>Spouštěná linka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="75"/>
        <source>Line inverted</source>
        <translation>Linka invertovaná</translation>
    </message>
</context>
</TS>
