<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr">
<context>
    <name></name>
    <message>
        <location filename="papywizard/scripts/main.py" line="210"/>
        <source>Plugins selection</source>
        <translation>Sélection des plugins</translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="215"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation>Avant de pouvoir utiliser Papywizard, vous devez choisir quels plugins utiliser pour piloter votre matériel.

Après fermeture de cette fenêtre, il vous sera demandé de sélectionner ces plugins. Une fois que cela sera fait, vous pourrez les configurer en utilisant la fenêtre de Configuration globale.</translation>
    </message>
</context>
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="139"/>
        <source>Abort</source>
        <translation>Annuler</translation>
    </message>
</context>
<context>
    <name>BluetoothChooserController</name>
    <message>
        <location filename="papywizard/controller/bluetoothChooserController.py" line="137"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Impossible de scruter le bluetooth</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="167"/>
        <source>Wrong value for camera orientation</source>
        <translation>Mauvaise valeur pour l&apos;orientation de l&apos;appareil</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="168"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Impossible de fixer l&apos;orientation de l&apos;appareil sur &apos;autre&apos; avec le mode &apos;mosaïque&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="183"/>
        <source>Wrong value for lens type</source>
        <translation>Mauvais type d&apos;objectif</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="184"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Impossible d&apos;utiliser un objectif type &apos;fisheye&apos; avec le mode &apos;mosaïque&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="230"/>
        <source>Choose Data Storage dir</source>
        <translation>Choisir répertoire stockage de données</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="289"/>
        <source>Here goes the title</source>
        <translation>Entrer le titre ici</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="293"/>
        <source>Here goes the location</source>
        <translation>Entrer les coordonnées ici</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="297"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Généré par Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>Dialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth chooser</source>
        <translation>Sélection bluetooth</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>À propos de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>Général</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="72"/>
        <source>Papywizard x.x.x</source>
        <translation>Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard est un logiciel de pilotage de tête panoramique principalement développé pour la tête astronomique Merlin/Orion mais utilisable pour d&apos;autres têtes.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation>© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Crédits</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="188"/>
        <source>License</source>
        <translation>License</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="194"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>Ce logiciel est régi par la licence CeCILL soumise au droit français et respectant les principes de diffusion des logiciels libres. Vous pouvez utiliser, modifier et/ou redistribuer ce programme sous les conditions de la licence CeCILL telle que diffusée par le CEA, le CNRS et l&apos;INRIA sur le site http://www.cecill.info.

En contrepartie de l&apos;accessibilité au code source et des droits de copie, de modification et de redistribution accordés par cette licence, il n&apos;est offert aux utilisateurs qu&apos;une garantie limitée.  Pour les mêmes raisons, seule une responsabilité restreinte pèse sur l&apos;auteur du programme, le titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l&apos;attention de l&apos;utilisateur est attirée sur les risques associés au chargement,  à l&apos;utilisation,  à la modification et/ou au développement et à la reproduction du logiciel par l&apos;utilisateur étant  donné sa spécificité de logiciel libre, qui peut le rendre complexe à manipuler et qui le réserve donc à des développeurs et des professionnels avertis possédant  des  connaissances  informatiques approfondies.  Les utilisateurs sont donc invités à charger  et  tester  l&apos;adéquation  du logiciel à leurs besoins dans des conditions permettant d&apos;assurer la sécurité de leurs systèmes et ou de leurs données et, plus généralement, à l&apos;utiliser et l&apos;exploiter dans les mêmes conditions de sécurité.

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez pris connaissance de la licence CeCILL, et que vous en avez accepté les termes.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total Fov</source>
        <translation>Adc total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="130"/>
        <source>http://www.papywizard.org</source>
        <translation>http://www.papywizard.org</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Développé par :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (coeur)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (Plugin EOS Utility)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Traduit par :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphismes de :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Distribué par :&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="110"/>
        <source>Error</source>
        <translation>Erreur</translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="119"/>
        <source>Exception</source>
        <translation>Exception</translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="92"/>
        <source>Info</source>
        <translation>Info</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="357"/>
        <source>Manual speed set to slow</source>
        <translation>Vitesse manuelle fixée sur lente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="375"/>
        <source>Manual speed set to normal</source>
        <translation>Vitesse manuelle fixée sur normale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="385"/>
        <source>Manual speed set to fast</source>
        <translation>Vitesse manuelle fixée sur rapide</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="414"/>
        <source>About to Quit</source>
        <translation>Sur le point de quitter</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="414"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Êtes-vous sûr de vouloir quitter Papywizard ?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="474"/>
        <source>Import Preset File</source>
        <translation>Importer Fichier Preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="476"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>Fichiers XML (*.xml);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="483"/>
        <source>Load Style Sheet</source>
        <translation>Charger feuille de style</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="485"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>Fichiers CSS (*.css);;Tous les fichiers (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="500"/>
        <source>Yaw - limit set</source>
        <translation>Limite lacet - fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="506"/>
        <source>Yaw + limit set</source>
        <translation>Limite lacet + fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="512"/>
        <source>Pitch + limit set</source>
        <translation>Limite tangage + fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="518"/>
        <source>Pitch - limit set</source>
        <translation>Limite tangage - fixée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="523"/>
        <source>Limits cleared</source>
        <translation>Limites effacées</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="556"/>
        <source>Operation aborted</source>
        <translation>Opération annulée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="546"/>
        <source>Goto initial position...</source>
        <translation>Aller à la position initiale...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="560"/>
        <source>Initial position reached</source>
        <translation>Position initial atteinte</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="613"/>
        <source>Yaw start set from current position</source>
        <translation>Début de lacet fixé depuis position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="620"/>
        <source>Pitch start set from current position</source>
        <translation>Début de tangage fixé depuis position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="627"/>
        <source>Yaw end set from current position</source>
        <translation>Fin de lacet fixée depuis position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="634"/>
        <source>Pitch end set from current position</source>
        <translation>Fin de tangage fixée depuis position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="732"/>
        <source>Yaw/pitch start set from current position</source>
        <translation>Début de lacet/tangage fixé depuis position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="740"/>
        <source>Yaw/pitch end set from current position</source>
        <translation>Fin de lacet/tangage fixée depuis position courante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="753"/>
        <source>Field of view set to user value</source>
        <translation>Angle de champ fixé à la valeur utilisateur</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="766"/>
        <source>Number of pictures set to user value</source>
        <translation>Nombre d&apos;images fixé à la valeur utilisateur</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="792"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre de configuration. Patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="827"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre de prise de vue. Patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="871"/>
        <source>Can&apos;t import preset file</source>
        <translation>Impossible d&apos;importer le fichier de preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="889"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Impossible de charger la feuille de style</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="666"/>
        <source>Reference set at current position</source>
        <translation>Référence fixée à la position courrante</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="549"/>
        <source>Please wait...</source>
        <translation>Veuillez patienter...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="549"/>
        <source>Goto initial position</source>
        <translation>Déplacement vers la position initiale</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="527"/>
        <source>Goto reference position...</source>
        <translation>Aller à la position de référence...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="529"/>
        <source>Goto reference position</source>
        <translation>Déplacement vers la position de référence</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="540"/>
        <source>Reference position reached</source>
        <translation>Position de référence atteinte</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="970"/>
        <source>Establishing connection...</source>
        <translation>Établissement de la connexion...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="992"/>
        <source>Connection established</source>
        <translation>Connexion établie</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="998"/>
        <source>Connection failed</source>
        <translation>La connection a échoué</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="999"/>
        <source>Can&apos;t establish connection</source>
        <translation>Impossible d&apos;établir la connexion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1044"/>
        <source>One or more plugin failed to shutdown</source>
        <translation>Un ou plusieurs plugins n&apos;ont pas pu se déconnecter :
%s</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1054"/>
        <source>Connection shutdown</source>
        <translation>Connexion terminée</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="967"/>
        <source>One or more plugin failed to connect:
%s</source>
        <translation>Un ou plusieurs plugins n&apos;ont pas pu se connecter :
%s</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1045"/>
        <source>One or more plugin failed to shutdown:
%s</source>
        <translation>Un ou plusieurs plugins n&apos;ont pas pu se déconnecter :
%s</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1046"/>
        <source>Can&apos;t shutdown connection</source>
        <translation>Impossible de terminer la connexion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="773"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation>Ouverture de la fenêtre des plugins. Veuillez patienter...</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="80"/>
        <source>Mosaic</source>
        <translation>Mosaïque</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="824"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="840"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="126"/>
        <source>Start (°)</source>
        <translation>Début (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="872"/>
        <source>--</source>
        <translation>--</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="180"/>
        <source>End (°)</source>
        <translation>Fin (°)</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="231"/>
        <source>Total Fov (°)</source>
        <translation>Adc Total (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="288"/>
        <source>Nb Picts</source>
        <translation>Nb photos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="345"/>
        <source>Real overlap (%)</source>
        <translation>Recouvrement réel (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="408"/>
        <source>Resolution (px)</source>
        <translation>Résolution (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="472"/>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="491"/>
        <source>Name</source>
        <translation>Nom</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="535"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Attention à la compatibilité entre la présélection et la taille de l&apos;appareil et de l&apos;objectif (collision).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="561"/>
        <source>Timelapse</source>
        <translation>Timelapse</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="786"/>
        <source>Move</source>
        <translation>Déplacement</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1038"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1074"/>
        <source>Configure...</source>
        <translation>Configurer...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1097"/>
        <source>Shoot...</source>
        <translation>Prise de vue...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1146"/>
        <source>File</source>
        <translation>Fichier</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1155"/>
        <source>Hardware</source>
        <translation>Matériel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1159"/>
        <source>Set Limit</source>
        <translation>Fixer limite</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1178"/>
        <source>Help</source>
        <translation>Aide</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1202"/>
        <source>Quit</source>
        <translation>Quitter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1205"/>
        <source>Ctrl+Q</source>
        <translation>Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1214"/>
        <source>Import Preset File...</source>
        <translation>Importer Fichier Preset...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1222"/>
        <source>Connect...</source>
        <translation>Connecter...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1231"/>
        <source>Clear Limits</source>
        <translation>Effacer les limites</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1240"/>
        <source>Yaw -</source>
        <translation>Lacet -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1249"/>
        <source>Yaw +</source>
        <translation>Lacet +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1258"/>
        <source>Pitch +</source>
        <translation>Tangage +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1267"/>
        <source>Pitch -</source>
        <translation>Tangage -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1276"/>
        <source>Manual</source>
        <translation>Manuel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1285"/>
        <source>View Log...</source>
        <translation>Voir Log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1294"/>
        <source>About Papywizard</source>
        <translation>À propos de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1303"/>
        <source>About Qt</source>
        <translation>À propos de Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1312"/>
        <source>Load Style Sheet...</source>
        <translation>Charger feuille de style...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1330"/>
        <source>Goto Initial...</source>
        <translation>Vers position initiale...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1321"/>
        <source>Goto Reference...</source>
        <translation>Vers position de référence...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="622"/>
        <source>1</source>
        <translation>1</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="627"/>
        <source>2</source>
        <translation>2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="632"/>
        <source>3</source>
        <translation>3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="689"/>
        <source>Add</source>
        <translation>Ajouter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="712"/>
        <source>Delete</source>
        <translation>Effacer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="735"/>
        <source>Replace</source>
        <translation>Remplacer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="758"/>
        <source>Goto...</source>
        <translation>Aller à...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1339"/>
        <source>Plugins...</source>
        <translation>Plugins...</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="407"/>
        <source>Step</source>
        <translation>Pas</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="502"/>
        <source>Resume</source>
        <translation>Reprendre</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="515"/>
        <source>Pause</source>
        <translation>Suspendre</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="506"/>
        <source>Paused</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="527"/>
        <source>Finished</source>
        <translation>Terminé</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="529"/>
        <source>Canceled</source>
        <translation>Annulé</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="531"/>
        <source>Failed</source>
        <translation>Échoué</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="541"/>
        <source>Waiting</source>
        <translation>Attente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="586"/>
        <source>Moving</source>
        <translation>Déplacement</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="588"/>
        <source>Stabilization</source>
        <translation>Stabilisation</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="590"/>
        <source>Mirror lockup</source>
        <translation>Verrouillage miroir</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="593"/>
        <source>Shutter - Picture</source>
        <translation>Obturateur - Image</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="530"/>
        <source>Shutter failed while mirror locking up</source>
        <translation>L&apos;obturateur n&apos;a pas pur relever le mirroir</translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="545"/>
        <source>Shutter failed while shooting</source>
        <translation>L&apos;obturateur n&apos;a pas pu prendre la vue</translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="101"/>
        <source>Warning</source>
        <translation>Warning</translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="130"/>
        <source>Question</source>
        <translation>Question</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Configuration</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Prise de vue</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Orientation tête</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>haut</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation>gauche</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation>droite</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>bas</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Orientation appareil</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>portrait</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>paysage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>autre</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Délai de stabilisation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="152"/>
        <source> s</source>
        <translation> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation>Mosaïque</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation>Recouvrement</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="195"/>
        <source> %</source>
        <translation> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="214"/>
        <source>Start from</source>
        <translation>Commence depuis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="231"/>
        <source>start</source>
        <translation>début</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="236"/>
        <source>end</source>
        <translation>fin</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="244"/>
        <source>Initial direction</source>
        <translation>Direction initiale</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="261"/>
        <source>yaw</source>
        <translation>lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="266"/>
        <source>pitch</source>
        <translation>tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="274"/>
        <source>CR</source>
        <translation>RC</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="448"/>
        <source> x</source>
        <translation> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="387"/>
        <source>3:2</source>
        <translation>3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="392"/>
        <source>4:3</source>
        <translation>4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="397"/>
        <source>5:4</source>
        <translation>5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="402"/>
        <source>16:9</source>
        <translation>16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="410"/>
        <source> Mpx</source>
        <translation>Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="309"/>
        <source>rectilinear</source>
        <translation>rectilinéaire</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="314"/>
        <source>fisheye</source>
        <translation>fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="426"/>
        <source> mm</source>
        <translation> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="625"/>
        <source>Data</source>
        <translation>Données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="633"/>
        <source>Data directory</source>
        <translation>Répertoire de données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="646"/>
        <source>Data file</source>
        <translation>Fichier de données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="823"/>
        <source>Enable</source>
        <translation>Actif</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="676"/>
        <source>Title</source>
        <translation>Titre</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="699"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="722"/>
        <source>Comment</source>
        <translation>Commentaire</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="772"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="780"/>
        <source>Start after</source>
        <translation>Commence après</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="800"/>
        <source>Repeat</source>
        <translation>Répétition</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="830"/>
        <source>Repeat every</source>
        <translation>Répète chaque</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="869"/>
        <source>HH:mm:ss</source>
        <translation>HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="882"/>
        <source>Misc</source>
        <translation>Divers</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="890"/>
        <source>Logger level</source>
        <translation>Niveau de log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="907"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="912"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="917"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="922"/>
        <source>warning</source>
        <translation>warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="927"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="932"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="937"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="370"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Capteur (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="335"/>
        <source>Sensor resolution</source>
        <translation>Résolution capteur</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="322"/>
        <source>Optical multiplier</source>
        <translation>Multiplicateur optique</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="284"/>
        <source>Camera/lens</source>
        <translation>Appareil/objectif</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="292"/>
        <source>Lens (type, focal)</source>
        <translation>Objectif (type, foccale)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="659"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation>%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="473"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="481"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="494"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="545"/>
        <source>Configure...</source>
        <translation>Configurer...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="521"/>
        <source>Shutter</source>
        <translation>Obturateur</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation>Effacer log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation>Enregistrer log</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb Picts</source>
        <translation>Nb photos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="13"/>
        <source>Plugin dialog</source>
        <translation>Fenêtre des plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="33"/>
        <source>Tab 1</source>
        <translation>Tab 1</translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation>Obturateur</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation>Pilotes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>Adresse interface BT</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="199"/>
        <source>00:50:C2:58:55:B9</source>
        <translation>00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="209"/>
        <source>Choose...</source>
        <translation>Choisir...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="219"/>
        <source>Serial port</source>
        <translation>Port série</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="235"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="248"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet hôte/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="264"/>
        <source>locahost</source>
        <translation>localhost</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation>bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation>serial</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation>ethernet</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Prise de vue</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation>Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation>Lacet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation>Tangage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation>Courante</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="259"/>
        <source>--/--</source>
        <translation>--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation>Suivante</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="338"/>
        <source>Idle</source>
        <translation>Repos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="425"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="468"/>
        <source>%p%</source>
        <translation>%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="508"/>
        <source>Data</source>
        <translation>Données</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="537"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="563"/>
        <source>Step-by-step</source>
        <translation>Pas-à-pas</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="596"/>
        <source>Start</source>
        <translation>Démarrer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="625"/>
        <source>Pause</source>
        <translation>Suspendre</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="654"/>
        <source>Stop</source>
        <translation>Arrêter</translation>
    </message>
</context>
</TS>
