<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="en">
<defaultcodec></defaultcodec>
<context>
    <name>BluetoothChooserController</name>
    <message>
        <location filename="papywizard/controller/bluetoothChooserController.py" line="138"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Can&apos;t scan bluetooth</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="156"/>
        <source>Wrong value for camera orientation</source>
        <translation>Wrong value for camera orientation</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="157"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="172"/>
        <source>Wrong value for lens type</source>
        <translation>Wrong value for lens type</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="173"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="195"/>
        <source>Choose Data Storage dir</source>
        <translation>Choose Data Storage dir</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="246"/>
        <source>Here goes the title</source>
        <translation>Here goes the title</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="250"/>
        <source>Here goes the location</source>
        <translation>Here goes the location</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="254"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Generated by Papywizard %(version)s</translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>Dialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="13"/>
        <source>Bluetooth chooser</source>
        <translation>Bluetooth chooser</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="68"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="13"/>
        <source>About Papywizard</source>
        <translation>About Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="30"/>
        <source>General</source>
        <translation>General</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="71"/>
        <source>Papywizard x.x.x</source>
        <translation>Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="83"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="107"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation>© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="129"/>
        <source>http://trac.gbiloba.org/papywizard</source>
        <translation>http://trac.gbiloba.org/papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="145"/>
        <source>Credits</source>
        <translation>Credits</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="153"/>
        <source>Written by</source>
        <translation>Written by</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="178"/>
        <source>Frédéric Mantegazza</source>
        <translation>Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="188"/>
        <source>Translated by</source>
        <translation>Translated by</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="221"/>
        <source>Graphics by</source>
        <translation>Graphics by</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="240"/>
        <source>Hubert Pawlowski
Frédéric Mantegazza</source>
        <translation>Hubert Pawlowski￼
Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="254"/>
        <source>License</source>
        <translation>License</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="260"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.￼

￼As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.￼

￼In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.￼

￼The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="48"/>
        <source>Total Fov</source>
        <translation>Total Fov</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="28"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="38"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="207"/>
        <source>Frédéric Mantegazza (fr)
Jo Lutum (de)
Maciej Dworak (pl)
Antonio Bruno (it)
Juan Carlos Andres (es)</source>
        <translation>Frédéric Mantegazza (fr)
Jo Lutum (de)
Maciej Dworak (pl)
Antonio Bruno (it)
Juan Carlos Andres (es)</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="368"/>
        <source>Manual speed set to slow</source>
        <translation>Manual speed set to slow</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="386"/>
        <source>Manual speed set to normal</source>
        <translation>Manual speed set to normal</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="389"/>
        <source>Fast manual speed</source>
        <translation>Fast manual speed</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="389"/>
        <source>This can be dangerous for the hardware!</source>
        <translation>This can be dangerous for the hardware!</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="396"/>
        <source>Manual speed set to fast</source>
        <translation>Manual speed set to fast</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="425"/>
        <source>About to Quit</source>
        <translation>About to Quit</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="425"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Are you sure you want to quit Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="484"/>
        <source>Import Preset File</source>
        <translation>Import Preset File</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="486"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML files (*.xml);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="493"/>
        <source>Load Style Sheet</source>
        <translation>Load Style Sheet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="495"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS files (*.css);;All files (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="510"/>
        <source>Yaw - limit set</source>
        <translation>Yaw - limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="516"/>
        <source>Yaw + limit set</source>
        <translation>Yaw + limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="522"/>
        <source>Pitch + limit set</source>
        <translation>Pitch + limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="528"/>
        <source>Pitch - limit set</source>
        <translation>Pitch - limit set</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="533"/>
        <source>Limits cleared</source>
        <translation>Limits cleared</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="566"/>
        <source>Operation aborted</source>
        <translation>Operation aborted</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="556"/>
        <source>Goto initial position...</source>
        <translation>Goto initial position...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="570"/>
        <source>Initial position reached</source>
        <translation>Initial position reached</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="623"/>
        <source>Yaw start set from current position</source>
        <translation>Yaw start set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="630"/>
        <source>Pitch start set from current position</source>
        <translation>Pitch start set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="637"/>
        <source>Yaw end set from current position</source>
        <translation>Yaw end set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="644"/>
        <source>Pitch end set from current position</source>
        <translation>Pitch end set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="742"/>
        <source>Yaw/pitch start set from current position</source>
        <translation>Yaw/pitch start set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="750"/>
        <source>Yaw/pitch end set from current position</source>
        <translation>Yaw/pitch end set from current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="763"/>
        <source>Field of view set to user value</source>
        <translation>Field of view set to user value</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="776"/>
        <source>Number of pictures set to user value</source>
        <translation>Number of pictures set to user value</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="802"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Opening configuration dialog. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="837"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Opening shoot dialog. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="881"/>
        <source>Can&apos;t import preset file</source>
        <translation>Can&apos;t import preset file</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="899"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Can&apos;t load style sheet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="676"/>
        <source>Reference set at current position</source>
        <translation>Reference set at current position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="559"/>
        <source>Please wait...</source>
        <translation>Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="559"/>
        <source>Goto initial position</source>
        <translation>Goto initial position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="537"/>
        <source>Goto reference position...</source>
        <translation>Goto reference position...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="539"/>
        <source>Goto reference position</source>
        <translation>Goto reference position</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="550"/>
        <source>Reference position reached</source>
        <translation>Reference position reached</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="783"/>
        <source>Opening preferences dialog. Please wait...</source>
        <translation>Opening preferences dialog. Please wait...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="980"/>
        <source>Establishing connection...</source>
        <translation>Establishing connection...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1002"/>
        <source>Connection established</source>
        <translation>Connection established</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1007"/>
        <source>Connection failed</source>
        <translation>Connection failed</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1008"/>
        <source>Can&apos;t establish connection</source>
        <translation>Can&apos;t establish connection</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1050"/>
        <source>One or more plugin failed to shutdown</source>
        <translation>One or more plugin failed to shutdown</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1054"/>
        <source>Connection shutdown</source>
        <translation>Connection shutdown</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="977"/>
        <source>One or more plugin failed to connect:
%s</source>
        <translation>One or more plugin failed to connect:
%s</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="22"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="75"/>
        <source>Mosaic</source>
        <translation>Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="633"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="649"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="125"/>
        <source>Start (°)</source>
        <translation>Start (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="681"/>
        <source>--</source>
        <translation>--</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="179"/>
        <source>End (°)</source>
        <translation>End (°)</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="230"/>
        <source>Total Fov (°)</source>
        <translation>Total Fov (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="287"/>
        <source>Nb Picts</source>
        <translation># Picts</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="344"/>
        <source>Real overlap (%)</source>
        <translation>Real overlap (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="407"/>
        <source>Resolution (px)</source>
        <translation>Resolution (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="467"/>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="490"/>
        <source>Name</source>
        <translation>Name</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="534"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Be sure that the preset used is compatible with your camera and lens size (collision).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="556"/>
        <source>Timelapse</source>
        <translation>Timelapse</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="566"/>
        <source>Not yet implemented</source>
        <translation>Not yet implemented</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="595"/>
        <source>Move</source>
        <translation>Move</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="847"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="883"/>
        <source>Configure...</source>
        <translation>Configure...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="906"/>
        <source>Shoot...</source>
        <translation>Shoot...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="942"/>
        <source>File</source>
        <translation>File</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="951"/>
        <source>Hardware</source>
        <translation>Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="955"/>
        <source>Set Limit</source>
        <translation>Set Limit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="974"/>
        <source>Help</source>
        <translation>Help</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="998"/>
        <source>Quit</source>
        <translation>Quit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1001"/>
        <source>Ctrl+Q</source>
        <translation>Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1010"/>
        <source>Import Preset File...</source>
        <translation>Import Preset File...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1018"/>
        <source>Connect...</source>
        <translation>Connect...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1027"/>
        <source>Clear Limits</source>
        <translation>Clear Limits</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1036"/>
        <source>Yaw -</source>
        <translation>Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1045"/>
        <source>Yaw +</source>
        <translation>Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1054"/>
        <source>Pitch +</source>
        <translation>Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1063"/>
        <source>Pitch -</source>
        <translation>Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1072"/>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1081"/>
        <source>View Log...</source>
        <translation>View Log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1090"/>
        <source>About Papywizard</source>
        <translation>About Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1099"/>
        <source>About Qt</source>
        <translation>About Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1108"/>
        <source>Load Style Sheet...</source>
        <translation>Load Style Sheet...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1126"/>
        <source>Goto Initial...</source>
        <translation>Goto Initial...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1117"/>
        <source>Goto Reference...</source>
        <translation>Goto Reference...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1135"/>
        <source>Preferences...</source>
        <translation>Preferences...</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="404"/>
        <source>Step</source>
        <translation>Step</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="499"/>
        <source>Resume</source>
        <translation>Resume</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="512"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="503"/>
        <source>Paused</source>
        <translation>Paused</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="524"/>
        <source>Finished</source>
        <translation>Finished</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="526"/>
        <source>Canceled</source>
        <translation>Canceled</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="528"/>
        <source>Failed</source>
        <translation>Failed</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="538"/>
        <source>Waiting</source>
        <translation>Waiting</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="583"/>
        <source>Moving</source>
        <translation>Moving</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="585"/>
        <source>Stabilization</source>
        <translation>Stabilization</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="587"/>
        <source>Mirror lockup</source>
        <translation>Mirror lockup</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="590"/>
        <source>Shutter - Picture</source>
        <translation>Shutter - Picture</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="532"/>
        <source>Shutter failed while mirror locking up</source>
        <translation>Shutter failed while mirror locking up</translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="553"/>
        <source>Shutter failed while shooting</source>
        <translation>Shutter failed while shooting</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="16"/>
        <source>Configuration</source>
        <translation>Configuration</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="36"/>
        <source>Shooting</source>
        <translation>Shooting</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="44"/>
        <source>Head orientation</source>
        <translation>Head orientation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="61"/>
        <source>up</source>
        <translation>up</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="66"/>
        <source>left</source>
        <translation>left</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="71"/>
        <source>right</source>
        <translation>right</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="76"/>
        <source>down</source>
        <translation>down</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="84"/>
        <source>Camera orientation</source>
        <translation>Camera orientation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="101"/>
        <source>portrait</source>
        <translation>portrait</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="106"/>
        <source>landscape</source>
        <translation>landscape</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="111"/>
        <source>custom</source>
        <translation>custom</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/configDialog.ui" line="122"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="138"/>
        <source>Stabilization delay</source>
        <translation>Stabilization delay</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="151"/>
        <source> s</source>
        <translation> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="173"/>
        <source>Mosaic</source>
        <translation>Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="181"/>
        <source>Overlap</source>
        <translation>Overlap</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="194"/>
        <source> %</source>
        <translation> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="213"/>
        <source>Start from</source>
        <translation>Start from</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="230"/>
        <source>start</source>
        <translation>start</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="235"/>
        <source>end</source>
        <translation>end</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="243"/>
        <source>Initial direction</source>
        <translation>Initial direction</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="260"/>
        <source>yaw</source>
        <translation>yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="265"/>
        <source>pitch</source>
        <translation>pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="273"/>
        <source>CR</source>
        <translation>CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="454"/>
        <source> x</source>
        <translation> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="393"/>
        <source>3:2</source>
        <translation>3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="398"/>
        <source>4:3</source>
        <translation>4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="403"/>
        <source>5:4</source>
        <translation>5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="408"/>
        <source>16:9</source>
        <translation>16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="416"/>
        <source> Mpx</source>
        <translation> Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="315"/>
        <source>rectilinear</source>
        <translation>rectilinear</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="320"/>
        <source>fisheye</source>
        <translation>fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="432"/>
        <source> mm</source>
        <translation> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="478"/>
        <source>Data</source>
        <translation>Data</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="486"/>
        <source>Data directory</source>
        <translation>Data directory</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="499"/>
        <source>Data file</source>
        <translation>Data file</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="512"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation>%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="676"/>
        <source>Enable</source>
        <translation>Enable</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="529"/>
        <source>Title</source>
        <translation>Title</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="552"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="575"/>
        <source>Comment</source>
        <translation>Comment</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="625"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="633"/>
        <source>Start after</source>
        <translation>Start after</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="653"/>
        <source>Repeat</source>
        <translation>Repeat</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="683"/>
        <source>Repeat every</source>
        <translation>Repeat every</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="722"/>
        <source>HH:mm:ss</source>
        <translation>HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="735"/>
        <source>Misc</source>
        <translation>Misc</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="743"/>
        <source>Logger level</source>
        <translation>Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="760"/>
        <source>trace</source>
        <translation>trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="765"/>
        <source>debug</source>
        <translation>debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="770"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="775"/>
        <source>warning</source>
        <translation>warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="780"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="785"/>
        <source>exception</source>
        <translation>exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="790"/>
        <source>critical</source>
        <translation>critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="376"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Sensor (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="341"/>
        <source>Sensor resolution</source>
        <translation>Sensor resolution</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="328"/>
        <source>Optical multiplier</source>
        <translation>Optical multiplier</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="283"/>
        <source>Camera/lens</source>
        <translation>Camera/lens</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="298"/>
        <source>Lens (type, focal)</source>
        <translation>Lens (type, focal)</translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation>Clear log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation>Save log</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="48"/>
        <source>Nb Picts</source>
        <translation># Picts</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="28"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="38"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginConfigDialog.ui" line="13"/>
        <source>Plugin dialog</source>
        <translation>Plugin dialog</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginConfigDialog.ui" line="33"/>
        <source>Tab 1</source>
        <translation>Tab 1</translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="16"/>
        <source>Preferences</source>
        <translation>Preferences</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="36"/>
        <source>Plugins</source>
        <translation>Plugins</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="44"/>
        <source>Yaw axis</source>
        <translation>Yaw axis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="64"/>
        <source>Pitch Axis</source>
        <translation>Pitch Axis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation>Shutter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="123"/>
        <source>Drivers</source>
        <translation>Drivers</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="131"/>
        <source>BT device address</source>
        <translation>BT device address</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="144"/>
        <source>00:50:C2:58:55:B9</source>
        <translation>00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="154"/>
        <source>Choose...</source>
        <translation>Choose...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="164"/>
        <source>Serial port</source>
        <translation>Serial port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="180"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="193"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="209"/>
        <source>locahost</source>
        <translation>locahost</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="235"/>
        <source>Auto-connect</source>
        <translation>Auto-connect</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/preferencesDialog.ui" line="107"/>
        <source>Configure...</source>
        <translation>Configure...</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="16"/>
        <source>Shooting</source>
        <translation>Shooting</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="104"/>
        <source>Total</source>
        <translation>Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="114"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="124"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="134"/>
        <source>Current</source>
        <translation>Current</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="258"/>
        <source>--/--</source>
        <translation>--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="198"/>
        <source>Next</source>
        <translation>Next</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="337"/>
        <source>Idle</source>
        <translation>Idle</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="424"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="467"/>
        <source>%p%</source>
        <translation>%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="507"/>
        <source>Data</source>
        <translation>Data</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="536"/>
        <source>Timer</source>
        <translation>Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="562"/>
        <source>Step-by-step</source>
        <translation>Step-by-step</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="595"/>
        <source>Start</source>
        <translation>Start</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="624"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="653"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
</context>
</TS>
