<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="de">
<defaultcodec></defaultcodec>
<context>
    <name>AbortMessageDialog</name>
    <message>
        <source>Abort</source>
        <translation>Abbruch</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <source>Wrong value for camera orientation</source>
        <translation>Falscher Wert für Kameraausrichtung</translation>
    </message>
    <message>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Kameraausrichtung &apos;Eigene&apos; nicht wählbar im Rastermodus</translation>
    </message>
    <message>
        <source>Wrong value for lens type</source>
        <translation>Falscher Wert für Objektiv-Typ</translation>
    </message>
    <message>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Objektivtyp &apos;Fischauge&apos; nicht wählbar im Rastermodus</translation>
    </message>
    <message>
        <source>Choose Data Storage dir</source>
        <translation>Datenverzeichnis wählen</translation>
    </message>
    <message>
        <source>Here goes the title</source>
        <translation>Titel hier eintragen</translation>
    </message>
    <message>
        <source>Here goes the location</source>
        <translation>Ortsangabe hier eintragen</translation>
    </message>
    <message>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Erstellt von Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <source>Error</source>
        <translation>Fehler</translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <source>Exception</source>
        <translation>Exception</translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <source>Info</source>
        <translation>Info</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <source>Manual speed set to slow</source>
        <translation>Geschwindigkeit langsam</translation>
    </message>
    <message>
        <source>Manual speed set to normal</source>
        <translation>Geschwindigkeit normal</translation>
    </message>
    <message>
        <source>Manual speed set to fast</source>
        <translation>Geschwindigkeit schnell</translation>
    </message>
    <message>
        <source>About to Quit</source>
        <translation>Anwendung beenden</translation>
    </message>
    <message>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Papywizard wirklich beenden?</translation>
    </message>
    <message>
        <source>Import Preset File</source>
        <translation>Import Datei Voreinstellungen</translation>
    </message>
    <message>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML Dateien (*.xml);;Alle Dateien (*)</translation>
    </message>
    <message>
        <source>Load Style Sheet</source>
        <translation>Lade Style sheet</translation>
    </message>
    <message>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS Dateien (*.css);;All Dateien (*)</translation>
    </message>
    <message>
        <source>Yaw - limit set</source>
        <translation>Drehung - Limit setzen</translation>
    </message>
    <message>
        <source>Yaw + limit set</source>
        <translation>Drehung + Limit setzen</translation>
    </message>
    <message>
        <source>Pitch + limit set</source>
        <translation>Neigung + Limit setzen</translation>
    </message>
    <message>
        <source>Pitch - limit set</source>
        <translation>Neigung - Limit setzen</translation>
    </message>
    <message>
        <source>Limits cleared</source>
        <translation>Limits gelöscht</translation>
    </message>
    <message>
        <source>Operation aborted</source>
        <translation>Vorgang abgebrochen</translation>
    </message>
    <message>
        <source>Goto initial position...</source>
        <translation>Gehe zu Ausgangsposition...</translation>
    </message>
    <message>
        <source>Initial position reached</source>
        <translation>Ausgangsposition erreicht</translation>
    </message>
    <message>
        <source>Field of view set to user value</source>
        <translation>FOV auf Benutzerwert gesetzt</translation>
    </message>
    <message>
        <source>Number of pictures set to user value</source>
        <translation>Anzahl Aufnahmen auf Benutzerwert gesetzt</translation>
    </message>
    <message>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Einstelldialog öffnen. Bitte warten...</translation>
    </message>
    <message>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Aufnahmedialog öffnen. Bitte warten...</translation>
    </message>
    <message>
        <source>Can&apos;t import preset file</source>
        <translation>Datei mit Voreinstellungen kann nicht importiert werden</translation>
    </message>
    <message>
        <source>Can&apos;t load style sheet</source>
        <translation>Style sheet kann nicht geladen werden</translation>
    </message>
    <message>
        <source>Reference set at current position</source>
        <translation>Aktuelle Position als Nullpunkt gesetzt</translation>
    </message>
    <message>
        <source>Please wait...</source>
        <translation>Bitte warten...</translation>
    </message>
    <message>
        <source>Goto initial position</source>
        <translation>Gehe zu Ausgangsposition</translation>
    </message>
    <message>
        <source>Goto reference position...</source>
        <translation>Gehe zu Ausgangsposition...</translation>
    </message>
    <message>
        <source>Goto reference position</source>
        <translation>Gehe zu Ausgangsposition</translation>
    </message>
    <message>
        <source>Reference position reached</source>
        <translation>Ausgangsposition erreicht</translation>
    </message>
    <message>
        <source>Opening plugins dialog. Please wait...</source>
        <translation>Plugin Dialog wird geöffnet. Bitte warten...</translation>
    </message>
    <message>
        <source>Starting connection. Please wait...</source>
        <translation>Verbindung wird gestartet. Bitte warten ...</translation>
    </message>
    <message>
        <source>Connection started</source>
        <translation>Verbindung gestartet</translation>
    </message>
    <message>
        <source>Connection failed to start</source>
        <translation>Verbindung fehlgeschlagen</translation>
    </message>
    <message>
        <source>Stopping connection. Please wait...</source>
        <translation>Beende Verbindung. Bitte warten...</translation>
    </message>
    <message>
        <source>Connection stopped</source>
        <translation>Verbindung beendet</translation>
    </message>
    <message>
        <source>Yaw corner 0 set from current position</source>
        <translation>Setze Ecke 0 (Drehung) auf aktuelle Position</translation>
    </message>
    <message>
        <source>Pitch corner 0 set from current position</source>
        <translation>Setze Ecke 0 (Neigung) auf aktuelle Position</translation>
    </message>
    <message>
        <source>Yaw corner 1 set from current position</source>
        <translation>Setze Ecke 1 (Drehung) auf aktuelle Position</translation>
    </message>
    <message>
        <source>Pitch corner 1 set from current position</source>
        <translation>Setze Ecke 1 (Neigung) auf aktuelle Position</translation>
    </message>
    <message>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation>Drehung/Neigung Ecke 0 gesetzt auf aktuelle Position</translation>
    </message>
    <message>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation>Drehung/Neigung Ecke 1 gesetzt auf aktuelle Position</translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Bluetooth nicht erkannt</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <source>Step</source>
        <translation>Schritt</translation>
    </message>
    <message>
        <source>Resume</source>
        <translation>Fortsetzen</translation>
    </message>
    <message>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <source>Paused</source>
        <translation>pausiert</translation>
    </message>
    <message>
        <source>Finished</source>
        <translation>Beendet</translation>
    </message>
    <message>
        <source>Canceled</source>
        <translation>Abgebrochen</translation>
    </message>
    <message>
        <source>Failed</source>
        <translation>Fehlgeschlagen</translation>
    </message>
    <message>
        <source>Waiting</source>
        <translation>Warte</translation>
    </message>
    <message>
        <source>Moving</source>
        <translation>Kopf fährt</translation>
    </message>
    <message>
        <source>Stabilization</source>
        <translation>Stabilisierung</translation>
    </message>
    <message>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <source>Shutter - Picture</source>
        <translation>Auslöser - Bild</translation>
    </message>
    <message>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
    <message>
        <source>Finish</source>
        <translation>Beenden</translation>
    </message>
    <message>
        <source>Idle</source>
        <translation>Warte</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <source>Shutter failed while mirror locking up</source>
        <translation>Auslösefehler während Spiegelverriegelung</translation>
    </message>
    <message>
        <source>Shutter failed while shooting</source>
        <translation>Auslösefehler</translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <source>Choose program path...</source>
        <translation>Programmpfad wählen...</translation>
    </message>
    <message>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE Dateien (*.exe);;Alle Dateien (*)</translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <source>Warning</source>
        <translation>Warnung</translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <source>Question</source>
        <translation>Frage</translation>
    </message>
</context>
<context>
    <name>abstractPluginController</name>
    <message>
        <source>Main</source>
        <translation>Main</translation>
    </message>
</context>
<context>
    <name>axisPluginController</name>
    <message>
        <source>Low limit</source>
        <translation>Unteres Limit</translation>
    </message>
    <message>
        <source>High limit</source>
        <translation>Oberes Limit</translation>
    </message>
</context>
<context>
    <name>dslrRemoteProPlugins</name>
    <message>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <source>User exposure
compensation list</source>
        <translation>Anwender Belichtung
Kompensationsliste</translation>
    </message>
    <message>
        <source>Dry run</source>
        <translation>Probelauf</translation>
    </message>
    <message>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <source>Output directory</source>
        <translation>Ausgabeverzeichnis</translation>
    </message>
    <message>
        <source>Choose output directory...</source>
        <translation>Ausgabeverzeichnis wählen...</translation>
    </message>
    <message>
        <source>File name prefix</source>
        <translation>Präfix Dateiname</translation>
    </message>
    <message>
        <source>Camera exposure
compensation list</source>
        <translation>Kamera Belichtung
Kompensationsliste</translation>
    </message>
    <message>
        <source>Program path</source>
        <translation>Programmpfad</translation>
    </message>
    <message>
        <source>Choose program path...</source>
        <translation>Programmpfad wählen...</translation>
    </message>
    <message>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE Dateien (*.exe);;Alle Dateien (*)</translation>
    </message>
</context>
<context>
    <name>eosUtilityPlugins</name>
    <message>
        <source>new</source>
        <translation>neu</translation>
    </message>
    <message>
        <source>far</source>
        <translation>fern</translation>
    </message>
    <message>
        <source>medium</source>
        <translation>mittel</translation>
    </message>
    <message>
        <source>old</source>
        <translation>alt</translation>
    </message>
    <message>
        <source>near</source>
        <translation>nah</translation>
    </message>
    <message>
        <source>small</source>
        <translation>klein</translation>
    </message>
    <message>
        <source>large</source>
        <translation>groß</translation>
    </message>
    <message>
        <source>Program path</source>
        <translation>Programmpfad</translation>
    </message>
    <message>
        <source>EOS Utility version</source>
        <translation>EOS Utility version</translation>
    </message>
    <message>
        <source>Bracketing nb picts</source>
        <translation>BKT Anzahl Bilder</translation>
    </message>
    <message>
        <source>Bracketing type</source>
        <translation>BKT Typ</translation>
    </message>
    <message>
        <source>Dry run</source>
        <translation>Probelauf</translation>
    </message>
    <message>
        <source>Bulb</source>
        <translation>Bulb</translation>
    </message>
    <message>
        <source>Enable</source>
        <translation>Aktivieren</translation>
    </message>
    <message>
        <source>Base exposure</source>
        <translation>Ausgangsbelichtung</translation>
    </message>
    <message>
        <source>Focus</source>
        <translation>Fokus</translation>
    </message>
    <message>
        <source>Direction</source>
        <translation>Richtung</translation>
    </message>
    <message>
        <source>Step</source>
        <translation>Schritt</translation>
    </message>
    <message>
        <source>Step count</source>
        <translation>Schrittzahl</translation>
    </message>
    <message>
        <source>Nb picts</source>
        <translation>Anzahl Bilder</translation>
    </message>
    <message>
        <source>Bracketing step</source>
        <translation>BKT Schritt</translation>
    </message>
</context>
<context>
    <name>genericTetheredPlugins</name>
    <message>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <source>Mirror lockup command</source>
        <translation>Befehl Spiegelverriegelung</translation>
    </message>
    <message>
        <source>Shoot command</source>
        <translation>Befehl Auslöser</translation>
    </message>
    <message>
        <source>Bracketing nb picts</source>
        <translation>BKT Anzahl Bilder</translation>
    </message>
</context>
<context>
    <name>gphotoBracketPlugins</name>
    <message>
        <source>Program path</source>
        <translation>Programmpfad</translation>
    </message>
    <message>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>gphoto2 (gphoto2);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bracketing nb picts</source>
        <translation>BKT Anzahl Bilder</translation>
    </message>
    <message>
        <source>Bracketing step</source>
        <translation>BKT Schritt</translation>
    </message>
    <message>
        <source>Exposure bias</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Resulting Ev list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Advanced</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bracketing nb picts (+)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bracketing step (+)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bracketing nb picts (-)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bracketing step (-)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Download</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Enable</source>
        <translation>Aktivieren</translation>
    </message>
    <message>
        <source>Download directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Choose download directory...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Download after</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Each shot</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bracketing sequence</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Delete camera picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <source>Plugins selection</source>
        <translation>Plugin Auswahl</translation>
    </message>
    <message>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation>Vor Einsatz von Papywizard müssen die Plugins für die Steuerung der Hardware ausgewählt werden.

Nach Schliessen diese Dialogs erscheint ein Prompt zur Auswahl. Dann können sie im Einstellungsdialog konfiguriert werden</translation>
    </message>
</context>
<context>
    <name>merlinOrionPlugins</name>
    <message>
        <source>Hard</source>
        <translation>Hard</translation>
    </message>
    <message>
        <source>Alternate drive</source>
        <translation>Alternate drive</translation>
    </message>
    <message>
        <source>Inertia angle</source>
        <translation>Inertia angle</translation>
    </message>
</context>
<context>
    <name>nkRemotePlugins</name>
    <message>
        <source>Program path</source>
        <translation>Programmpfad</translation>
    </message>
    <message>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE Dateien (*.exe);;Alle Dateien (*)</translation>
    </message>
    <message>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <source>User exposure
compensation list</source>
        <translation>Anwender Belichtung
Kompensationsliste</translation>
    </message>
    <message>
        <source>Dry run</source>
        <translation>Probelauf</translation>
    </message>
    <message>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <source>Choose output directory...</source>
        <translation>Ausgabeverzeichnis wählen...</translation>
    </message>
    <message>
        <source>File name prefix</source>
        <translation>Präfix Dateiname</translation>
    </message>
    <message>
        <source>Camera exposure
compensation list</source>
        <translation>Kamera Belichtung
Kompensationsliste</translation>
    </message>
    <message>
        <source>Output directory</source>
        <translation>Ausgabeverzeichnis</translation>
    </message>
</context>
<context>
    <name>panoduinoPlugins</name>
    <message>
        <source>forward</source>
        <translation>vorwärts</translation>
    </message>
    <message>
        <source>Speed</source>
        <translation>Geschwindigkeit</translation>
    </message>
    <message>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <source>Direction</source>
        <translation>Richtung</translation>
    </message>
    <message>
        <source>Neutral position</source>
        <translation>Neutrale Position</translation>
    </message>
    <message>
        <source>Value off</source>
        <translation>Wert AN</translation>
    </message>
    <message>
        <source>Value on</source>
        <translation>Wert AUS</translation>
    </message>
    <message>
        <source>reverse</source>
        <translation>rückwärts</translation>
    </message>
</context>
<context>
    <name>pixOrbPlugins</name>
    <message>
        <source>Speed index</source>
        <translation>Speed index</translation>
    </message>
    <message>
        <source>Hard</source>
        <translation>Hard</translation>
    </message>
    <message>
        <source>Axis with break</source>
        <translation>Axis with break</translation>
    </message>
    <message>
        <source>Axis accuracy</source>
        <translation>Axis accuracy</translation>
    </message>
</context>
<context>
    <name>simulationPlugins</name>
    <message>
        <source>Speed</source>
        <translation>Geschwindigkeit</translation>
    </message>
    <message>
        <source>Time value</source>
        <translation>Zeitwert</translation>
    </message>
    <message>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <source>Bracketing nb picts</source>
        <translation>BKT Anzahl Bilder</translation>
    </message>
</context>
<context>
    <name>standardShutterPluginController</name>
    <message>
        <source>Time value</source>
        <translation>Zeitwert</translation>
    </message>
    <message>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <source>Bracketing nb picts</source>
        <translation>BKT Anzahl Bilder</translation>
    </message>
    <message>
        <source>Hard</source>
        <translation>Hard</translation>
    </message>
    <message>
        <source>Pulse width high</source>
        <translation>Pulse width high</translation>
    </message>
    <message>
        <source>Pulse width low</source>
        <translation>Pulse width low</translation>
    </message>
    <message>
        <source>Bulb</source>
        <translation>Bulb</translation>
    </message>
</context>
<context>
    <name>timelordPlugins</name>
    <message>
        <source>Program path</source>
        <translation>Programmpfad</translation>
    </message>
    <message>
        <source>Choose program path...</source>
        <translation>Programmpfad wählen ...</translation>
    </message>
    <message>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation>EXE Dateien (*.exe);;Alle Dateien (*)</translation>
    </message>
    <message>
        <source>LRD file</source>
        <translation>LRD Datei</translation>
    </message>
    <message>
        <source>Choose LRD file...</source>
        <translation>LRD Datei wählen...</translation>
    </message>
    <message>
        <source>LRD files (*.lrd);;All files (*)</source>
        <translation>LRD Dateien (*.lrd);;Alle Dateien (*)</translation>
    </message>
</context>
<context>
    <name>ursaMinorBt2Plugins</name>
    <message>
        <source>Focus</source>
        <translation>Fokus</translation>
    </message>
    <message>
        <source>Enable</source>
        <translation>Aktivieren</translation>
    </message>
    <message>
        <source>Pulse width</source>
        <translation>Pulse width</translation>
    </message>
    <message>
        <source>Maintain focus</source>
        <translation>Fokus beibehalten</translation>
    </message>
</context>
<context>
    <name>ursaMinorUsbPlugins</name>
    <message>
        <source>Trigger line</source>
        <translation>Triggerleitung</translation>
    </message>
    <message>
        <source>Line inverted</source>
        <translation>Leitung umkehren</translation>
    </message>
</context>
</TS>
