<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="es">
<context>
    <name></name>
    <message>
        <location filename="papywizard/scripts/main.py" line="217"/>
        <source>Plugins selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="222"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="138"/>
        <source>Abort</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="166"/>
        <source>Wrong value for camera orientation</source>
        <translation>Valor incorrecto para orientación cámara</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="167"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>No puedes fijar la orientacion de la camara en &apos;custom&apos; mientras estas en modo &apos;mosaic&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="180"/>
        <source>Wrong value for lens type</source>
        <translation>Valor incorrecto para tipo de lente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="181"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>No puedes fijar el tipo de lente en &apos;fisheye&apos; mientras estas en modo &apos;mosaic&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="225"/>
        <source>Choose Data Storage dir</source>
        <translation>Elegir Dir. almacenaje de datos</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="284"/>
        <source>Here goes the title</source>
        <translation>Aqui va el titulo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="288"/>
        <source>Here goes the location</source>
        <translation>Aqui va la localizacion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="292"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Generado por Papywizard %(version)s</translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>Dialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth chooser</source>
        <translation type="unfinished">Elegir Bluetooth</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation type="unfinished">Acerca de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation type="unfinished">General</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="72"/>
        <source>Papywizard x.x.x</source>
        <translation type="unfinished">Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation type="unfinished">Papywizard es un software para controlar una pano-cabeza, desarrollado principalmente para la montura astronomica Merlin/Orion, pero utilizable para otras pano-cabezas.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation type="unfinished">© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation type="unfinished">Creditos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="188"/>
        <source>License</source>
        <translation type="unfinished">Licencia</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="194"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation type="unfinished">This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total Fov</source>
        <translation type="unfinished">Total Fov</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished">Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished">Pitch</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation type="unfinished"> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="130"/>
        <source>http://www.papywizard.org</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="109"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="118"/>
        <source>Exception</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="91"/>
        <source>Info</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="364"/>
        <source>Manual speed set to slow</source>
        <translation>Velocidad manual fijada en lenta</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="382"/>
        <source>Manual speed set to normal</source>
        <translation>Velocidad manual fijada en normal</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="392"/>
        <source>Manual speed set to fast</source>
        <translation>Velocidad manual fijada en rapida</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="421"/>
        <source>About to Quit</source>
        <translation>Acerca de como salir</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="421"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>¿Estas seguro de que quieres salir de Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="481"/>
        <source>Import Preset File</source>
        <translation>Importar Preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="483"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>Archivos XML (*.xml);;Todos los archivos (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="490"/>
        <source>Load Style Sheet</source>
        <translation>Cargar hoja de estilo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="492"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>Archivos CSS (*.css);;Todos los archivos (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="507"/>
        <source>Yaw - limit set</source>
        <translation>Yaw - limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="513"/>
        <source>Yaw + limit set</source>
        <translation>Yaw + limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="519"/>
        <source>Pitch + limit set</source>
        <translation>Pitch + limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="525"/>
        <source>Pitch - limit set</source>
        <translation>Pitch - limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="530"/>
        <source>Limits cleared</source>
        <translation>Límites borrados</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="564"/>
        <source>Operation aborted</source>
        <translation>Operacion cancelada</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="553"/>
        <source>Goto initial position...</source>
        <translation>Ir a la posicion inicial...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="568"/>
        <source>Initial position reached</source>
        <translation>Initial position reached</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="621"/>
        <source>Yaw start set from current position</source>
        <translation>Yaw origen fijado desde actual posicion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="628"/>
        <source>Pitch start set from current position</source>
        <translation>Pitch-origen fijado desde la posicion actual</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="635"/>
        <source>Yaw end set from current position</source>
        <translation>Yaw final fijado desde actual posicion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="642"/>
        <source>Pitch end set from current position</source>
        <translation>Pitch-final fijado desde la posicion actual</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="674"/>
        <source>Reference set at current position</source>
        <translation>Referencia fijada a la posicion actual</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="735"/>
        <source>Yaw/pitch start set from current position</source>
        <translation>Yaw/pitch origen fijado desde actual posicion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="743"/>
        <source>Yaw/pitch end set from current position</source>
        <translation>Yaw/pitch final fijado desde actual posicion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="756"/>
        <source>Field of view set to user value</source>
        <translation>Campo visual fijado en valor de usuario</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="769"/>
        <source>Number of pictures set to user value</source>
        <translation>Numero de imagenes fijado en valor del usuario</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="793"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Abriendo dialogo de configuracion. Por favor, espere...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="828"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Abriendo dialogo de disparo. Por favor, espere...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="877"/>
        <source>Can&apos;t import preset file</source>
        <translation>No se puede importar el archivo preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="895"/>
        <source>Can&apos;t load style sheet</source>
        <translation>No puede cargar la hoja de estilo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="557"/>
        <source>Please wait...</source>
        <translation>Por favor, espere...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="557"/>
        <source>Goto initial position</source>
        <translation>Ir a la posicion inicial</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="534"/>
        <source>Goto reference position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="536"/>
        <source>Goto reference position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="547"/>
        <source>Reference position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="774"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="937"/>
        <source>Starting connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="956"/>
        <source>Connection started</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="961"/>
        <source>Connection failed to start</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="975"/>
        <source>Stopping connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="988"/>
        <source>Connection stopped</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation type="unfinished">Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="438"/>
        <source>Mosaic</source>
        <translation type="unfinished">Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1004"/>
        <source>Yaw</source>
        <translation type="unfinished">Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1009"/>
        <source>Pitch</source>
        <translation type="unfinished">Pitch</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="484"/>
        <source>Start (°)</source>
        <translation type="unfinished">Empezar (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="813"/>
        <source>--</source>
        <translation type="unfinished">--</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="538"/>
        <source>End (°)</source>
        <translation type="unfinished">Final (°)</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="589"/>
        <source>Total Fov (°)</source>
        <translation type="unfinished">Total Fov (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="646"/>
        <source>Nb Picts</source>
        <translation type="unfinished">N. Imagenes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="703"/>
        <source>Real overlap (%)</source>
        <translation type="unfinished">Superposicion real  (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="766"/>
        <source>Resolution (px)</source>
        <translation type="unfinished">Resolucion (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="830"/>
        <source>Preset</source>
        <translation type="unfinished">Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="849"/>
        <source>Name</source>
        <translation type="unfinished">Nombre</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="893"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation type="unfinished">Estas seguro de que el preset utilizado es compatible con el tamaño de tu camara y lente (colision).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="919"/>
        <source>Timelapse</source>
        <translation type="unfinished">Timelapse</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation type="unfinished">Mover</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="312"/>
        <source>...</source>
        <translation type="unfinished">...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="348"/>
        <source>Configure...</source>
        <translation type="unfinished">Configurar...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="371"/>
        <source>Shoot...</source>
        <translation type="unfinished">Disparo...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1151"/>
        <source>File</source>
        <translation type="unfinished">Archivo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1160"/>
        <source>Hardware</source>
        <translation type="unfinished">Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1164"/>
        <source>Set Limit</source>
        <translation type="unfinished">Fijar limite</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1183"/>
        <source>Help</source>
        <translation type="unfinished">Ayuda</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1207"/>
        <source>Quit</source>
        <translation type="unfinished">Salir</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1210"/>
        <source>Ctrl+Q</source>
        <translation type="unfinished">Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1219"/>
        <source>Import Preset File...</source>
        <translation type="unfinished">Importar archivo Preset...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1227"/>
        <source>Connect...</source>
        <translation type="unfinished">Conectar...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1236"/>
        <source>Clear Limits</source>
        <translation type="unfinished">Borrar limites</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1245"/>
        <source>Yaw -</source>
        <translation type="unfinished">Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1254"/>
        <source>Yaw +</source>
        <translation type="unfinished">Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1263"/>
        <source>Pitch +</source>
        <translation type="unfinished">Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1272"/>
        <source>Pitch -</source>
        <translation type="unfinished">Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1281"/>
        <source>Manual</source>
        <translation type="unfinished">Manual</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1290"/>
        <source>View Log...</source>
        <translation type="unfinished">Ver Log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1299"/>
        <source>About Papywizard</source>
        <translation type="unfinished">Acerca de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1308"/>
        <source>About Qt</source>
        <translation type="unfinished">Acerca de Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1317"/>
        <source>Load Style Sheet...</source>
        <translation type="unfinished">Cargar hoja de estilo...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1335"/>
        <source>Goto Initial...</source>
        <translation type="unfinished">Ir al inicio...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1326"/>
        <source>Goto Reference...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1067"/>
        <source>Add</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1101"/>
        <source>Delete</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1084"/>
        <source>Replace</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1118"/>
        <source>Goto...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1344"/>
        <source>Plugins...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="203"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation type="unfinished">No puede escanear bluetooth</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="406"/>
        <source>Step</source>
        <translation>Paso</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="501"/>
        <source>Resume</source>
        <translation>Resume</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="514"/>
        <source>Pause</source>
        <translation>Parar</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="505"/>
        <source>Paused</source>
        <translation>Parado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="526"/>
        <source>Finished</source>
        <translation>Terminado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="528"/>
        <source>Canceled</source>
        <translation>Cancelado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="530"/>
        <source>Failed</source>
        <translation>Fallo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="540"/>
        <source>Waiting</source>
        <translation>Esperando</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="585"/>
        <source>Moving</source>
        <translation>Moviendo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="587"/>
        <source>Stabilization</source>
        <translation>Estabilizando</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="589"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="592"/>
        <source>Shutter - Picture</source>
        <translation>Disparo - Imagen</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="522"/>
        <source>Shutter failed while mirror locking up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="537"/>
        <source>Shutter failed while shooting</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="100"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Wizard</name>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="26"/>
        <source>Wizard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="208"/>
        <source>Papywizard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="153"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600; font-style:italic;&quot;&gt;Welcome to the free panohead control software!&lt;/span&gt;&lt;/p&gt;
&lt;p align=&quot;center&quot; style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;&quot;&gt;&lt;/p&gt;
&lt;p align=&quot;justify&quot; style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Papywizard&lt;/span&gt; has not yet been configured; in the following pages, you will be asked to enter a few parameters to make a basic usable configuration.&lt;/p&gt;
&lt;p align=&quot;justify&quot; style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p align=&quot;justify&quot; style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You will be able to modify this configuration later, according to your needs.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="232"/>
        <source>Hardware configuration</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="246"/>
        <source>Real head</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="261"/>
        <source>Bluetooth address</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="277"/>
        <source>Choose...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/wizardDialog.ui" line="306"/>
        <source>page 1 of 2</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="129"/>
        <source>Question</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation type="unfinished">Configuracion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation type="unfinished">Disparando</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation type="unfinished">Orientacion cabeza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation type="unfinished">arriba</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation type="unfinished">izquierda</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation type="unfinished">derecha</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation type="unfinished">abajo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation type="unfinished">Camera orientation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation type="unfinished">retrato</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation type="unfinished">paisaje</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="492"/>
        <source>custom</source>
        <translation type="unfinished">a medida</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation type="unfinished"> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation type="unfinished">Retardo estabilizacion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="152"/>
        <source> s</source>
        <translation type="unfinished"> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation type="unfinished">Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation type="unfinished">Superposicion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="195"/>
        <source> %</source>
        <translation type="unfinished"> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="214"/>
        <source>Start from</source>
        <translation type="unfinished">Empezar desde</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="231"/>
        <source>start</source>
        <translation type="unfinished">empezar</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="236"/>
        <source>end</source>
        <translation type="unfinished">final</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="244"/>
        <source>Initial direction</source>
        <translation type="unfinished">Direccion inicial</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="261"/>
        <source>yaw</source>
        <translation type="unfinished">yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="266"/>
        <source>pitch</source>
        <translation type="unfinished">pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="274"/>
        <source>CR</source>
        <translation type="unfinished">CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="379"/>
        <source>Sensor (coef, ratio)</source>
        <translation type="unfinished">Sensor (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="460"/>
        <source> x</source>
        <translation type="unfinished"> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="396"/>
        <source>3:2</source>
        <translation type="unfinished">3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="401"/>
        <source>4:3</source>
        <translation type="unfinished">4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="406"/>
        <source>5:4</source>
        <translation type="unfinished">5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="411"/>
        <source>16:9</source>
        <translation type="unfinished">16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="419"/>
        <source> Mpx</source>
        <translation type="unfinished"> Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="344"/>
        <source>Sensor resolution</source>
        <translation type="unfinished">Resolucion del sensor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="315"/>
        <source>rectilinear</source>
        <translation type="unfinished">rectilinea</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="320"/>
        <source>fisheye</source>
        <translation type="unfinished">fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="438"/>
        <source> mm</source>
        <translation type="unfinished"> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="331"/>
        <source>Optical multiplier</source>
        <translation type="unfinished">Multip. optica</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="681"/>
        <source>Data</source>
        <translation type="unfinished">Datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="689"/>
        <source>Data directory</source>
        <translation type="unfinished">Directorio de datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="702"/>
        <source>Data file</source>
        <translation type="unfinished">Archivo de datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="715"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation type="unfinished">%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="879"/>
        <source>Enable</source>
        <translation type="unfinished">Permitir</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="732"/>
        <source>Title</source>
        <translation type="unfinished">Titulo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="755"/>
        <source>GPS</source>
        <translation type="unfinished">GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="778"/>
        <source>Comment</source>
        <translation type="unfinished">Comentario</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="828"/>
        <source>Timer</source>
        <translation type="unfinished">Tiempo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="836"/>
        <source>Start after</source>
        <translation type="unfinished">Empezar despues</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="856"/>
        <source>Repeat</source>
        <translation type="unfinished">Repetir</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="886"/>
        <source>Repeat every</source>
        <translation type="unfinished">Repetir cada</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="925"/>
        <source>HH:mm:ss</source>
        <translation type="unfinished">HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="938"/>
        <source>Misc</source>
        <translation type="unfinished">Misc</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="946"/>
        <source>Logger level</source>
        <translation type="unfinished">Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="963"/>
        <source>trace</source>
        <translation type="unfinished">rastro</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="968"/>
        <source>debug</source>
        <translation type="unfinished">elimine errores</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="973"/>
        <source>info</source>
        <translation type="unfinished">info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="978"/>
        <source>warning</source>
        <translation type="unfinished">peligro</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="983"/>
        <source>error</source>
        <translation type="unfinished">error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="988"/>
        <source>exception</source>
        <translation type="unfinished">excepcion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="993"/>
        <source>critical</source>
        <translation type="unfinished">critico</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="284"/>
        <source>Camera/lens</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="295"/>
        <source>Lens (type, focal)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="529"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="537"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="550"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="601"/>
        <source>Configure...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="577"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="503"/>
        <source>Lens configuration</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="519"/>
        <source>Add</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation type="unfinished">Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation type="unfinished">Borrar log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation type="unfinished">Guardar log</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb Picts</source>
        <translation type="unfinished">N. Imagenes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished">Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished">Pitch</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="14"/>
        <source>Plugin dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="34"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation type="unfinished">Direccion dispositivo BT</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="199"/>
        <source>00:50:C2:58:55:B9</source>
        <translation type="unfinished">00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="209"/>
        <source>Choose...</source>
        <translation type="unfinished">Elegir...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="219"/>
        <source>Serial port</source>
        <translation type="unfinished">Serial port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="235"/>
        <source>0</source>
        <translation type="unfinished">0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="248"/>
        <source>Ethernet host/port</source>
        <translation type="unfinished">Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="264"/>
        <source>locahost</source>
        <translation type="unfinished">locahost</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation type="unfinished">Disparando</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation type="unfinished">Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation type="unfinished">Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation type="unfinished">Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation type="unfinished">Actual</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="259"/>
        <source>--/--</source>
        <translation type="unfinished">--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation type="unfinished">Siguiente</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="338"/>
        <source>Idle</source>
        <translation type="unfinished">Detenido</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="425"/>
        <source>00:00:00</source>
        <translation type="unfinished">00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="468"/>
        <source>%p%</source>
        <translation type="unfinished">%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="508"/>
        <source>Data</source>
        <translation type="unfinished">Datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="537"/>
        <source>Timer</source>
        <translation type="unfinished">Tiempo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="563"/>
        <source>Step-by-step</source>
        <translation type="unfinished">Paso a paso</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="596"/>
        <source>Start</source>
        <translation type="unfinished">Empezar</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="625"/>
        <source>Pause</source>
        <translation type="unfinished">Pausa</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="654"/>
        <source>Stop</source>
        <translation type="unfinished">Stop</translation>
    </message>
</context>
</TS>
