<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1" language="de">
<context>
    <name></name>
    <message>
        <location filename="papywizard/scripts/main.py" line="210"/>
        <source>Plugins selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="215"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="139"/>
        <source>Abort</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>BluetoothChooserController</name>
    <message>
        <location filename="papywizard/controller/bluetoothChooserController.py" line="137"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Bluetooth nicht erkannt</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="167"/>
        <source>Wrong value for camera orientation</source>
        <translation>Falscher Wert für Kameraausrichtung</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="168"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Kameraausrichtung &apos;Eigene&apos; nicht wählbar im Rastermodus</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="183"/>
        <source>Wrong value for lens type</source>
        <translation>Falscher Wert für Objektiv-Typ</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="184"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>Objektivtyp &apos;Fischauge&apos; nicht wählbar im Rastermodus</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="230"/>
        <source>Choose Data Storage dir</source>
        <translation>Datenverzeichnis wählen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="289"/>
        <source>Here goes the title</source>
        <translation>Titel hier eintragen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="293"/>
        <source>Here goes the location</source>
        <translation>Ortsangabe hier eintragen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="297"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Erstellt von Papywizard %(version)s</translation>
    </message>
</context>
<context encoding="UTF-8">
    <name>Dialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth chooser</source>
        <translation type="unfinished">Bluetooth Auswahl</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation type="unfinished"> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation type="unfinished">Über Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation type="unfinished">Allgemein</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="72"/>
        <source>Papywizard x.x.x</source>
        <translation type="unfinished">Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation type="unfinished">Papywizard ist eine Panoramakopf-kontrollsoftware, entwickelt für den Merlin/Orion-Astronomie-Kopfaber auch für andere.</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation type="unfinished">© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation type="unfinished">Mitarbeit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="188"/>
        <source>License</source>
        <translation type="unfinished">Lizenz</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="194"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation type="unfinished">This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.￼

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.￼

￼In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.￼

￼The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total Fov</source>
        <translation type="unfinished">Gesamt- FOV</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished">Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished">Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="130"/>
        <source>http://www.papywizard.org</source>
        <translation type="unfinished"></translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="110"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="119"/>
        <source>Exception</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="92"/>
        <source>Info</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="357"/>
        <source>Manual speed set to slow</source>
        <translation>Geschwindigkeit langsam</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="375"/>
        <source>Manual speed set to normal</source>
        <translation>Geschwindigkeit normal</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="385"/>
        <source>Manual speed set to fast</source>
        <translation>Geschwindigkeit schnell</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="414"/>
        <source>About to Quit</source>
        <translation>Anwendung beenden</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="414"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>Papywizard wirklich beenden?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="474"/>
        <source>Import Preset File</source>
        <translation>Import Datei Voreinstellungen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="476"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>XML Dateien (*.xml);;Alle Dateien (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="483"/>
        <source>Load Style Sheet</source>
        <translation>Lade Style sheet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="485"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>CSS Dateien (*.css);;All Dateien (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="500"/>
        <source>Yaw - limit set</source>
        <translation>Drehung - Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="506"/>
        <source>Yaw + limit set</source>
        <translation>Drehung + Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="512"/>
        <source>Pitch + limit set</source>
        <translation>Neigung + Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="518"/>
        <source>Pitch - limit set</source>
        <translation>Neigung - Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="523"/>
        <source>Limits cleared</source>
        <translation>Limits gelöscht</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="556"/>
        <source>Operation aborted</source>
        <translation>Vorgang abgebrochen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="546"/>
        <source>Goto initial position...</source>
        <translation>Gehe zu Ausgangsposition...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="560"/>
        <source>Initial position reached</source>
        <translation>Ausgangsposition erreicht</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="613"/>
        <source>Yaw start set from current position</source>
        <translation>Aktuelle Position als Dreh-Start gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="620"/>
        <source>Pitch start set from current position</source>
        <translation>Aktuelle Position als Neige-Start gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="627"/>
        <source>Yaw end set from current position</source>
        <translation>Aktuelle Position als Dreh-Ende gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="634"/>
        <source>Pitch end set from current position</source>
        <translation>Aktuelle Position als Neige-Ende gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="732"/>
        <source>Yaw/pitch start set from current position</source>
        <translation>Aktuelle Position als Dreh-Neige-Start gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="740"/>
        <source>Yaw/pitch end set from current position</source>
        <translation>Aktuelle Position als Dreh-Neige-Ende gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="753"/>
        <source>Field of view set to user value</source>
        <translation>FOV auf Benutzerwert gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="766"/>
        <source>Number of pictures set to user value</source>
        <translation>Anzahl Aufnahmen auf Benutzerwert gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="792"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Einstelldialog öffnen. Bitte warten...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="827"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Aufnahmedialog öffnen. Bitte warten...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="871"/>
        <source>Can&apos;t import preset file</source>
        <translation>Datei mit Voreinstellungen kann nicht importiert werden</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="889"/>
        <source>Can&apos;t load style sheet</source>
        <translation>Style sheet kann nicht geladen werden</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="666"/>
        <source>Reference set at current position</source>
        <translation>Aktuelle Position als Nullpunkt gesetzt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="549"/>
        <source>Please wait...</source>
        <translation>Bitte warten...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="549"/>
        <source>Goto initial position</source>
        <translation>Gehe zu Ausgangsposition</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="527"/>
        <source>Goto reference position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="529"/>
        <source>Goto reference position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="540"/>
        <source>Reference position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="970"/>
        <source>Establishing connection...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="992"/>
        <source>Connection established</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="998"/>
        <source>Connection failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="999"/>
        <source>Can&apos;t establish connection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1044"/>
        <source>One or more plugin failed to shutdown</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1054"/>
        <source>Connection shutdown</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="967"/>
        <source>One or more plugin failed to connect:
%s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1045"/>
        <source>One or more plugin failed to shutdown:
%s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1046"/>
        <source>Can&apos;t shutdown connection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="773"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation type="unfinished">Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="80"/>
        <source>Mosaic</source>
        <translation type="unfinished">Raster</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="824"/>
        <source>Yaw</source>
        <translation type="unfinished">Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="840"/>
        <source>Pitch</source>
        <translation type="unfinished">Neigung</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="126"/>
        <source>Start (°)</source>
        <translation type="unfinished">Start (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="872"/>
        <source>--</source>
        <translation type="unfinished">--</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="180"/>
        <source>End (°)</source>
        <translation type="unfinished">Ende (°)</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/mainWindow.ui" line="231"/>
        <source>Total Fov (°)</source>
        <translation type="unfinished">Gesamt- FOV (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="288"/>
        <source>Nb Picts</source>
        <translation type="unfinished">Anz. Aufnahmen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="345"/>
        <source>Real overlap (%)</source>
        <translation type="unfinished">Überlappung (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="408"/>
        <source>Resolution (px)</source>
        <translation type="unfinished">Auflösung (pixel)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="472"/>
        <source>Preset</source>
        <translation type="unfinished">Vorlage</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="491"/>
        <source>Name</source>
        <translation type="unfinished">Name</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="535"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation type="unfinished">Sicherstellen dass Voreinstellung kompatibel mit Kamera und Objektiv ist (Kollision mit Merlin).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="561"/>
        <source>Timelapse</source>
        <translation type="unfinished">Zeitraffer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="786"/>
        <source>Move</source>
        <translation type="unfinished">Move</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1038"/>
        <source>...</source>
        <translation type="unfinished">...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1074"/>
        <source>Configure...</source>
        <translation type="unfinished">Einstellungen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1097"/>
        <source>Shoot...</source>
        <translation type="unfinished">Aufnahme...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1146"/>
        <source>File</source>
        <translation type="unfinished">Datei</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1155"/>
        <source>Hardware</source>
        <translation type="unfinished">Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1159"/>
        <source>Set Limit</source>
        <translation type="unfinished">Limit setzen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1178"/>
        <source>Help</source>
        <translation type="unfinished">Hilfe</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1202"/>
        <source>Quit</source>
        <translation type="unfinished">Quit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1205"/>
        <source>Ctrl+Q</source>
        <translation type="unfinished">Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1214"/>
        <source>Import Preset File...</source>
        <translation type="unfinished">Import Datei Voreinstellungen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1222"/>
        <source>Connect...</source>
        <translation type="unfinished">Verbinden...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1231"/>
        <source>Clear Limits</source>
        <translation type="unfinished">Limits löschen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1240"/>
        <source>Yaw -</source>
        <translation type="unfinished">Drehung -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1249"/>
        <source>Yaw +</source>
        <translation type="unfinished">Drehung +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1258"/>
        <source>Pitch +</source>
        <translation type="unfinished">Neigung +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1267"/>
        <source>Pitch -</source>
        <translation type="unfinished">Neigung -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1276"/>
        <source>Manual</source>
        <translation type="unfinished">Anleitung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1285"/>
        <source>View Log...</source>
        <translation type="unfinished">Log anzeigen...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1294"/>
        <source>About Papywizard</source>
        <translation type="unfinished">Über Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1303"/>
        <source>About Qt</source>
        <translation type="unfinished">Über Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1312"/>
        <source>Load Style Sheet...</source>
        <translation type="unfinished">Lade Style Sheet</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1330"/>
        <source>Goto Initial...</source>
        <translation type="unfinished">Gehe zur Ausgangsposition...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1321"/>
        <source>Goto Reference...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="622"/>
        <source>1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="627"/>
        <source>2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="632"/>
        <source>3</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="689"/>
        <source>Add</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="712"/>
        <source>Delete</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="735"/>
        <source>Replace</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="758"/>
        <source>Goto...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1339"/>
        <source>Plugins...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="407"/>
        <source>Step</source>
        <translation>Schritt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="502"/>
        <source>Resume</source>
        <translation>Fortsetzen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="515"/>
        <source>Pause</source>
        <translation>Pause</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="506"/>
        <source>Paused</source>
        <translation>pausiert</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="527"/>
        <source>Finished</source>
        <translation>Beendet</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="529"/>
        <source>Canceled</source>
        <translation>Abgebrochen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="531"/>
        <source>Failed</source>
        <translation>Fehlgeschlagen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="541"/>
        <source>Waiting</source>
        <translation>Warte</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="586"/>
        <source>Moving</source>
        <translation>Kopf fährt</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="588"/>
        <source>Stabilization</source>
        <translation>Stabilisierung</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="590"/>
        <source>Mirror lockup</source>
        <translation>Spiegelverriegelung</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="593"/>
        <source>Shutter - Picture</source>
        <translation>Auslöser - Bild</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="530"/>
        <source>Shutter failed while mirror locking up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="545"/>
        <source>Shutter failed while shooting</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="101"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="130"/>
        <source>Question</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation type="unfinished">Konfiguration</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation type="unfinished">Aufnahme</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation type="unfinished">Geräte-Ausrichtung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation type="unfinished">hoch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation type="unfinished">links</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation type="unfinished">rechts</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation type="unfinished">runter</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation type="unfinished">Ausrichtung der Kamera</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation type="unfinished">Hoch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation type="unfinished">Quer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation type="unfinished">Eigene</translation>
    </message>
    <message encoding="UTF-8">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation type="unfinished"> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation type="unfinished">Stab. Pause</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="152"/>
        <source> s</source>
        <translation type="unfinished"> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation type="unfinished">Raster</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation type="unfinished">Überlappung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="195"/>
        <source> %</source>
        <translation type="unfinished"> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="214"/>
        <source>Start from</source>
        <translation type="unfinished">Start bei</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="231"/>
        <source>start</source>
        <translation type="unfinished">Start</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="236"/>
        <source>end</source>
        <translation type="unfinished">ende</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="244"/>
        <source>Initial direction</source>
        <translation type="unfinished">Anfangsrichtung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="261"/>
        <source>yaw</source>
        <translation type="unfinished">drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="266"/>
        <source>pitch</source>
        <translation type="unfinished">neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="274"/>
        <source>CR</source>
        <translation type="unfinished">CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="448"/>
        <source> x</source>
        <translation type="unfinished"> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="387"/>
        <source>3:2</source>
        <translation type="unfinished">3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="392"/>
        <source>4:3</source>
        <translation type="unfinished">4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="397"/>
        <source>5:4</source>
        <translation type="unfinished">5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="402"/>
        <source>16:9</source>
        <translation type="unfinished">16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="410"/>
        <source> Mpx</source>
        <translation type="unfinished"> Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="309"/>
        <source>rectilinear</source>
        <translation type="unfinished">rechtwinklig</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="314"/>
        <source>fisheye</source>
        <translation type="unfinished">rischauge</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="426"/>
        <source> mm</source>
        <translation type="unfinished"> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="625"/>
        <source>Data</source>
        <translation type="unfinished">Daten</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="633"/>
        <source>Data directory</source>
        <translation type="unfinished">Daten-Verzeichnis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="646"/>
        <source>Data file</source>
        <translation type="unfinished">Datei</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="659"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation type="unfinished">%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="823"/>
        <source>Enable</source>
        <translation type="unfinished">Aktivieren</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="676"/>
        <source>Title</source>
        <translation type="unfinished">Titel</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="699"/>
        <source>GPS</source>
        <translation type="unfinished">GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="722"/>
        <source>Comment</source>
        <translation type="unfinished">Bemerkung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="772"/>
        <source>Timer</source>
        <translation type="unfinished">Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="780"/>
        <source>Start after</source>
        <translation type="unfinished">Start nach</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="800"/>
        <source>Repeat</source>
        <translation type="unfinished">Wiederhole</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="830"/>
        <source>Repeat every</source>
        <translation type="unfinished">Wiederhole alle</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="869"/>
        <source>HH:mm:ss</source>
        <translation type="unfinished">HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="882"/>
        <source>Misc</source>
        <translation type="unfinished">Verschiedenes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="890"/>
        <source>Logger level</source>
        <translation type="unfinished">Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="907"/>
        <source>trace</source>
        <translation type="unfinished">trace</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="912"/>
        <source>debug</source>
        <translation type="unfinished">debug</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="917"/>
        <source>info</source>
        <translation type="unfinished">info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="922"/>
        <source>warning</source>
        <translation type="unfinished">warning</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="927"/>
        <source>error</source>
        <translation type="unfinished">error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="932"/>
        <source>exception</source>
        <translation type="unfinished">exception</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="937"/>
        <source>critical</source>
        <translation type="unfinished">critical</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="370"/>
        <source>Sensor (coef, ratio)</source>
        <translation type="unfinished">Sensor (Faktor, Verhältnis)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="335"/>
        <source>Sensor resolution</source>
        <translation type="unfinished">Sensorauflösung MP</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="322"/>
        <source>Optical multiplier</source>
        <translation type="unfinished">Optischer Faktor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="284"/>
        <source>Camera/lens</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="292"/>
        <source>Lens (type, focal)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="473"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="481"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="494"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="545"/>
        <source>Configure...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="521"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation type="unfinished">Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation type="unfinished">Logdateien löschen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation type="unfinished">Log anzeigen</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb Picts</source>
        <translation type="unfinished">Anz. Aufnahmen</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished">Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished">Neigung</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="13"/>
        <source>Plugin dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="33"/>
        <source>Tab 1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation type="unfinished">BT Geräteadresse</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="199"/>
        <source>00:50:C2:58:55:B9</source>
        <translation type="unfinished">00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="209"/>
        <source>Choose...</source>
        <translation type="unfinished">Wähle...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="219"/>
        <source>Serial port</source>
        <translation type="unfinished">Serieller Anschluss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="235"/>
        <source>0</source>
        <translation type="unfinished">0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="248"/>
        <source>Ethernet host/port</source>
        <translation type="unfinished">Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="264"/>
        <source>locahost</source>
        <translation type="unfinished">localhost</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation type="unfinished">Aufnahme</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation type="unfinished">Gesamt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation type="unfinished">Drehung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation type="unfinished">Neigung</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation type="unfinished">Aktuell</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="259"/>
        <source>--/--</source>
        <translation type="unfinished">--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation type="unfinished">Nächste</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="338"/>
        <source>Idle</source>
        <translation type="unfinished">Warte</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="425"/>
        <source>00:00:00</source>
        <translation type="unfinished">00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="468"/>
        <source>%p%</source>
        <translation type="unfinished">%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="508"/>
        <source>Data</source>
        <translation type="unfinished">Daten</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="537"/>
        <source>Timer</source>
        <translation type="unfinished">Timer</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="563"/>
        <source>Step-by-step</source>
        <translation type="unfinished">Einzelschritt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="596"/>
        <source>Start</source>
        <translation type="unfinished">Start</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="625"/>
        <source>Pause</source>
        <translation type="unfinished">Pause</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="654"/>
        <source>Stop</source>
        <translation type="unfinished">Stop</translation>
    </message>
</context>
</TS>
