<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="es">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="138"/>
        <source>Abort</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="176"/>
        <source>Wrong value for camera orientation</source>
        <translation>Valor incorrecto para orientación cámara</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="177"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation>No puedes fijar la orientacion de la camara en &apos;custom&apos; mientras estas en modo &apos;mosaic&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="190"/>
        <source>Wrong value for lens type</source>
        <translation>Valor incorrecto para tipo de lente</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="191"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation>No puedes fijar el tipo de lente en &apos;fisheye&apos; mientras estas en modo &apos;mosaic&apos;</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="235"/>
        <source>Choose Data Storage dir</source>
        <translation>Elegir Dir. almacenaje de datos</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="330"/>
        <source>Here goes the title</source>
        <translation>Aqui va el titulo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="334"/>
        <source>Here goes the location</source>
        <translation>Aqui va la localizacion</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="338"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation>Generado por Papywizard %(version)s</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="109"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="118"/>
        <source>Exception</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="91"/>
        <source>Info</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="366"/>
        <source>Manual speed set to slow</source>
        <translation>Velocidad manual fijada en lenta</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="384"/>
        <source>Manual speed set to normal</source>
        <translation>Velocidad manual fijada en normal</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="394"/>
        <source>Manual speed set to fast</source>
        <translation>Velocidad manual fijada en rapida</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="423"/>
        <source>About to Quit</source>
        <translation>Acerca de como salir</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="423"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation>¿Estas seguro de que quieres salir de Papywizard?</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="483"/>
        <source>Import Preset File</source>
        <translation>Importar Preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="485"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation>Archivos XML (*.xml);;Todos los archivos (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="492"/>
        <source>Load Style Sheet</source>
        <translation>Cargar hoja de estilo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="494"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation>Archivos CSS (*.css);;Todos los archivos (*)</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="516"/>
        <source>Yaw - limit set</source>
        <translation>Yaw - limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="522"/>
        <source>Yaw + limit set</source>
        <translation>Yaw + limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="528"/>
        <source>Pitch + limit set</source>
        <translation>Pitch + limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="534"/>
        <source>Pitch - limit set</source>
        <translation>Pitch - limite fijado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="539"/>
        <source>Limits cleared</source>
        <translation>Límites borrados</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="573"/>
        <source>Operation aborted</source>
        <translation>Operacion cancelada</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="562"/>
        <source>Goto initial position...</source>
        <translation>Ir a la posicion inicial...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="577"/>
        <source>Initial position reached</source>
        <translation>Initial position reached</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="695"/>
        <source>Reference set at current position</source>
        <translation>Referencia fijada a la posicion actual</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="761"/>
        <source>Field of view set to user value</source>
        <translation>Campo visual fijado en valor de usuario</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="774"/>
        <source>Number of pictures set to user value</source>
        <translation>Numero de imagenes fijado en valor del usuario</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="798"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation>Abriendo dialogo de configuracion. Por favor, espere...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="833"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation>Abriendo dialogo de disparo. Por favor, espere...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="882"/>
        <source>Can&apos;t import preset file</source>
        <translation>No se puede importar el archivo preset</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="900"/>
        <source>Can&apos;t load style sheet</source>
        <translation>No puede cargar la hoja de estilo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="566"/>
        <source>Please wait...</source>
        <translation>Por favor, espere...</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="566"/>
        <source>Goto initial position</source>
        <translation>Ir a la posicion inicial</translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="543"/>
        <source>Goto reference position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="545"/>
        <source>Goto reference position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="556"/>
        <source>Reference position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="779"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="962"/>
        <source>Starting connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="985"/>
        <source>Connection started</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="990"/>
        <source>Connection failed to start</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1004"/>
        <source>Stopping connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="1017"/>
        <source>Connection stopped</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="639"/>
        <source>Yaw corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="647"/>
        <source>Pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="663"/>
        <source>Yaw corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="671"/>
        <source>Pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="631"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="655"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="438"/>
        <source>Mosaic</source>
        <translation>Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="974"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="990"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1098"/>
        <source>--</source>
        <translation>--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="737"/>
        <source>Real overlap (%)</source>
        <translation>Superposicion real  (%)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="800"/>
        <source>Resolution (px)</source>
        <translation>Resolucion (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="864"/>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="883"/>
        <source>Name</source>
        <translation>Nombre</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="927"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation>Estas seguro de que el preset utilizado es compatible con el tamaño de tu camara y lente (colision).</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="953"/>
        <source>Timelapse</source>
        <translation>Timelapse</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Mover</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="312"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="348"/>
        <source>Configure...</source>
        <translation>Configurar...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="371"/>
        <source>Shoot...</source>
        <translation>Disparo...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1184"/>
        <source>File</source>
        <translation>Archivo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1193"/>
        <source>Hardware</source>
        <translation>Hardware</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1197"/>
        <source>Set Limit</source>
        <translation>Fijar limite</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1218"/>
        <source>Help</source>
        <translation>Ayuda</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1242"/>
        <source>Quit</source>
        <translation>Salir</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1245"/>
        <source>Ctrl+Q</source>
        <translation>Ctrl+Q</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1254"/>
        <source>Import Preset File...</source>
        <translation>Importar archivo Preset...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1262"/>
        <source>Connect...</source>
        <translation>Conectar...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1386"/>
        <source>Clear Limits</source>
        <translation>Borrar limites</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1271"/>
        <source>Yaw -</source>
        <translation>Yaw -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1280"/>
        <source>Yaw +</source>
        <translation>Yaw +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1289"/>
        <source>Pitch +</source>
        <translation>Pitch +</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1298"/>
        <source>Pitch -</source>
        <translation>Pitch -</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1307"/>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1316"/>
        <source>View Log...</source>
        <translation>Ver Log...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1325"/>
        <source>About Papywizard</source>
        <translation>Acerca de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1334"/>
        <source>About Qt</source>
        <translation>Acerca de Qt</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1343"/>
        <source>Load Style Sheet...</source>
        <translation>Cargar hoja de estilo...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1361"/>
        <source>Goto Initial...</source>
        <translation>Ir al inicio...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1352"/>
        <source>Goto Reference...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1370"/>
        <source>Plugins...</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="615"/>
        <source>Total fov (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1105"/>
        <source>Nb picts</source>
        <translation>N. imagenes</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="487"/>
        <source>Corner 0 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="554"/>
        <source>Corner 1 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="1006"/>
        <source>Start (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="1060"/>
        <source>End (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1381"/>
        <source>Suspend Spy</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1138"/>
        <source>Shoot while moving</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1155"/>
        <source>HH:mm:ss</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1128"/>
        <source>Duration</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="203"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>No puede escanear bluetooth</translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="391"/>
        <source>Step</source>
        <translation>Paso</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="462"/>
        <source>Resume</source>
        <translation>Resume</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="475"/>
        <source>Pause</source>
        <translation>Parar</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="466"/>
        <source>Paused</source>
        <translation>Parado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="487"/>
        <source>Finished</source>
        <translation>Terminado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="489"/>
        <source>Canceled</source>
        <translation>Cancelado</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="491"/>
        <source>Failed</source>
        <translation>Fallo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="498"/>
        <source>Waiting</source>
        <translation>Esperando</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="544"/>
        <source>Moving</source>
        <translation>Moviendo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="546"/>
        <source>Stabilization</source>
        <translation>Estabilizando</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="548"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="551"/>
        <source>Shutter - Picture</source>
        <translation>Disparo - Imagen</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="681"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="493"/>
        <source>Finish</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="592"/>
        <source>Idle</source>
        <translation>Detenido</translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="548"/>
        <source>Shutter failed while mirror locking up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="563"/>
        <source>Shutter failed while shooting</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="199"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="200"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="100"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="129"/>
        <source>Question</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>abstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="73"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>axisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="66"/>
        <source>Low limit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="68"/>
        <source>High limit</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Configuracion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Disparando</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Orientacion cabeza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>arriba</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation>izquierda</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation>derecha</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>abajo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Camera orientation</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>retrato</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>paisaje</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>a medida</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Retardo estabilizacion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="152"/>
        <source> s</source>
        <translation> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation>Mosaic</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation>Superposicion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="195"/>
        <source> %</source>
        <translation> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="217"/>
        <source>Start from</source>
        <translation>Empezar desde</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="260"/>
        <source>Initial direction</source>
        <translation>Direccion inicial</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>yaw</source>
        <translation>yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>pitch</source>
        <translation>pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="290"/>
        <source>CR</source>
        <translation>CR</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="386"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Sensor (coef, ratio)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="473"/>
        <source> x</source>
        <translation> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="403"/>
        <source>3:2</source>
        <translation>3:2</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="408"/>
        <source>4:3</source>
        <translation>4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="413"/>
        <source>5:4</source>
        <translation>5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="418"/>
        <source>16:9</source>
        <translation>16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="426"/>
        <source> Mpx</source>
        <translation> Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="351"/>
        <source>Sensor resolution</source>
        <translation>Resolucion del sensor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="325"/>
        <source>rectilinear</source>
        <translation>rectilinea</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="330"/>
        <source>fisheye</source>
        <translation>fisheye</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="448"/>
        <source> mm</source>
        <translation> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="338"/>
        <source>Optical multiplier</source>
        <translation>Multip. optica</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="650"/>
        <source>Data</source>
        <translation>Datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="658"/>
        <source>Data directory</source>
        <translation>Directorio de datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="674"/>
        <source>Data file</source>
        <translation>Archivo de datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="690"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation>%(date_time)s_%(mode)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="884"/>
        <source>Enable</source>
        <translation>Permitir</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="713"/>
        <source>Title</source>
        <translation>Titulo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="742"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="771"/>
        <source>Comment</source>
        <translation>Comentario</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="824"/>
        <source>Timer</source>
        <translation>Tiempo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="835"/>
        <source>Start after</source>
        <translation>Empezar despues</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="858"/>
        <source>Repeat</source>
        <translation>Repetir</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="894"/>
        <source>Repeat every</source>
        <translation>Repetir cada</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="939"/>
        <source>HH:mm:ss</source>
        <translation>HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="962"/>
        <source>Misc</source>
        <translation>Misc</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="970"/>
        <source>Logger level</source>
        <translation>Logger level</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="987"/>
        <source>trace</source>
        <translation>rastro</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="992"/>
        <source>debug</source>
        <translation>elimine errores</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="997"/>
        <source>info</source>
        <translation>info</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1002"/>
        <source>warning</source>
        <translation>peligro</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1007"/>
        <source>error</source>
        <translation>error</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1012"/>
        <source>exception</source>
        <translation>excepcion</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1017"/>
        <source>critical</source>
        <translation>critico</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="300"/>
        <source>Camera/lens</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="308"/>
        <source>Lens (type, focal)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="498"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="506"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="519"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="570"/>
        <source>Configure...</source>
        <translation>Configurar...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="546"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="237"/>
        <source>top-left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="242"/>
        <source>top-right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>bottom-left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="252"/>
        <source>bottom-right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="952"/>
        <source>Reverse direction before repeat</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>dslrRemoteProPlugins</name>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="202"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="204"/>
        <source>User exposure
compensation list</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="206"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="208"/>
        <source>Camera</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="209"/>
        <source>Output directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="211"/>
        <source>Choose output directory...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="213"/>
        <source>File name prefix</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/dslrRemoteProPlugins.py" line="215"/>
        <source>Camera exposure
compensation list</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>eosUtilityPlugins</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>new</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>far</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>medium</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>old</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="92"/>
        <source>near</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="96"/>
        <source>small</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>large</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="198"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="203"/>
        <source>EOS Utility version</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="205"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="209"/>
        <source>Bracketing stops</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="211"/>
        <source>Bracketing type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="213"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="215"/>
        <source>Bulb</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="221"/>
        <source>Enable</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="218"/>
        <source>Base exposure</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="220"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="224"/>
        <source>Direction</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="227"/>
        <source>Step</source>
        <translation>Paso</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="229"/>
        <source>Step count</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="231"/>
        <source>Nb picts</source>
        <translation>N. imagenes</translation>
    </message>
</context>
<context>
    <name>genericTetheredPlugins</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="124"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="126"/>
        <source>Mirror lockup command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="128"/>
        <source>Shoot command</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="130"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>gphotoPlugins</name>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="159"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="161"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="163"/>
        <source>Bracketing step</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>Acerca de Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>General</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="72"/>
        <source>Papywizard x.x.x</source>
        <translation>Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard es un software para controlar una pano-cabeza, desarrollado principalmente para la montura astronomica Merlin/Orion, pero utilizable para otras pano-cabezas.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation>© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="130"/>
        <source>http://www.papywizard.org</source>
        <translation>http://www.papywizard.org</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Creditos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="189"/>
        <source>License</source>
        <translation>Licencia</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="195"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation>Logger</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation>Borrar log</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation>Guardar log</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="219"/>
        <source>Plugins selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>merlinOrionPlugins</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="482"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="483"/>
        <source>Alternate drive</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="485"/>
        <source>Inertia angle</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation>N. Imagenes</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation>N. imagenes</translation>
    </message>
</context>
<context>
    <name>pixOrbPlugins</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="430"/>
        <source>Speed index</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="432"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="433"/>
        <source>Axis with break</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="26"/>
        <source>Plugin dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="46"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pluginsStatusDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="14"/>
        <source>Plugins Status</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="49"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="65"/>
        <source>Init</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsStatusDialog.ui" line="81"/>
        <source>Connect</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pololuServoPlugins</name>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="94"/>
        <source>forward</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="95"/>
        <source>reverse</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="443"/>
        <source>Speed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="510"/>
        <source>Servo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="511"/>
        <source>Channel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="449"/>
        <source>Direction</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="451"/>
        <source>Angle for 1ms</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="453"/>
        <source>Neutral position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="513"/>
        <source>Value off</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="515"/>
        <source>Value on</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation>Direccion dispositivo BT</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="199"/>
        <source>00:50:C2:58:55:B9</source>
        <translation>00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="209"/>
        <source>Choose...</source>
        <translation>Elegir...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="219"/>
        <source>Serial port</source>
        <translation>Serial port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="235"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="248"/>
        <source>Ethernet host/port</source>
        <translation>Ethernet host/port</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="264"/>
        <source>locahost</source>
        <translation>locahost</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation>Disparando</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation>Total</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation>Actual</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="259"/>
        <source>--/--</source>
        <translation>--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation>Siguiente</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="341"/>
        <source>Idle</source>
        <translation>Detenido</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="428"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="471"/>
        <source>%p%</source>
        <translation>%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="511"/>
        <source>Data</source>
        <translation>Datos</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="540"/>
        <source>Timer</source>
        <translation>Tiempo</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="566"/>
        <source>Step-by-step</source>
        <translation>Paso a paso</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="599"/>
        <source>Start</source>
        <translation>Empezar</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="628"/>
        <source>Pause</source>
        <translation>Pausa</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="657"/>
        <source>Stop</source>
        <translation>Stop</translation>
    </message>
</context>
<context>
    <name>simulationPlugins</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="220"/>
        <source>Speed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="265"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="267"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="269"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>standardShutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="63"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="65"/>
        <source>Mirror lockup</source>
        <translation>Levantar espejo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="67"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="69"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="70"/>
        <source>Pulse width high</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="72"/>
        <source>Pulse width low</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>timelordPlugins</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="126"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="127"/>
        <source>Choose program path...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="128"/>
        <source>EXE files (*.exe);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="130"/>
        <source>LRD file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="131"/>
        <source>Choose LRD file...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="132"/>
        <source>LRD files (*.lrd);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation>Total Fov</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation>Yaw</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation>Pitch</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation>Total fov</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
<context>
    <name>ursaMinorBt2Plugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="153"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="154"/>
        <source>Enable</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="156"/>
        <source>Pulse width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="158"/>
        <source>Maintain focus</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ursaMinorUsbPlugins</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="116"/>
        <source>Trigger line</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="118"/>
        <source>Line inverted</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
