<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="cs_CZ">
<context>
    <name>AbortMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="138"/>
        <source>Abort</source>
        <translation>Zrušit</translation>
    </message>
</context>
<context>
    <name>AbstractPluginController</name>
    <message>
        <location filename="papywizard/plugins/abstractPluginController.py" line="73"/>
        <source>Main</source>
        <translation>Hlavní</translation>
    </message>
</context>
<context>
    <name>AxisPluginController</name>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="66"/>
        <source>Low limit</source>
        <translation>Nejnižší hodnota</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/axisPluginController.py" line="68"/>
        <source>High limit</source>
        <translation>Nejvyšší hodnota</translation>
    </message>
</context>
<context>
    <name>ConfigController</name>
    <message>
        <location filename="papywizard/controller/configController.py" line="176"/>
        <source>Wrong value for camera orientation</source>
        <translation>Špatná hodnnota pro orientaci fotoaparátu.</translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="177"/>
        <source>Can&apos;t set camera orientation to &apos;custom&apos; while in &apos;mosaic&apos; mode</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="190"/>
        <source>Wrong value for lens type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="191"/>
        <source>Can&apos;t set lens type to &apos;fisheye&apos; while in &apos;mosaic&apos; mode</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="235"/>
        <source>Choose Data Storage dir</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="330"/>
        <source>Here goes the title</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="334"/>
        <source>Here goes the location</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/configController.py" line="338"/>
        <source>Generated by Papywizard %(version)s</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>EOSUtilityShutterController</name>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="88"/>
        <source>new</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="91"/>
        <source>far</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="97"/>
        <source>medium</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="87"/>
        <source>old</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="92"/>
        <source>near</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="96"/>
        <source>small</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="98"/>
        <source>large</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="198"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="201"/>
        <source>EOS Utility version</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="203"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="207"/>
        <source>Bracketing stops</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="209"/>
        <source>Bracketing type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="211"/>
        <source>Dry run</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="213"/>
        <source>Bulb</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="219"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="216"/>
        <source>Base exposure</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="218"/>
        <source>Focus</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="222"/>
        <source>Direction</source>
        <translation>Směr</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="225"/>
        <source>Step</source>
        <translation>Krok</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="227"/>
        <source>Step count</source>
        <translation>Počet kroků</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/eosUtilityPlugins.py" line="229"/>
        <source>Nb picts</source>
        <translation>Počet obrázků</translation>
    </message>
</context>
<context>
    <name>ErrorMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="109"/>
        <source>Error</source>
        <translation>Chyba</translation>
    </message>
</context>
<context>
    <name>ExceptionMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="118"/>
        <source>Exception</source>
        <translation>Vyjímka</translation>
    </message>
</context>
<context>
    <name>GenericTetheredShutterController</name>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="124"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="126"/>
        <source>Mirror lockup command</source>
        <translation>Příkaz předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="128"/>
        <source>Shoot command</source>
        <translation>Příkaz fotografování</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/genericTetheredPlugins.py" line="130"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
</context>
<context>
    <name>GphotoShutterController</name>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="159"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="161"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/gphotoPlugins.py" line="163"/>
        <source>Bracketing step</source>
        <translation>Krok při braketingu</translation>
    </message>
</context>
<context>
    <name>InfoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="91"/>
        <source>Info</source>
        <translation>Informace</translation>
    </message>
</context>
<context>
    <name>MainController</name>
    <message>
        <location filename="papywizard/controller/mainController.py" line="364"/>
        <source>Manual speed set to slow</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="382"/>
        <source>Manual speed set to normal</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="392"/>
        <source>Manual speed set to fast</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="421"/>
        <source>About to Quit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="421"/>
        <source>Are you sure you want to quit Papywizard?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="481"/>
        <source>Import Preset File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="483"/>
        <source>XML files (*.xml);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="490"/>
        <source>Load Style Sheet</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="492"/>
        <source>CSS files (*.css);;All files (*)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="507"/>
        <source>Yaw - limit set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="513"/>
        <source>Yaw + limit set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="519"/>
        <source>Pitch + limit set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="525"/>
        <source>Pitch - limit set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="530"/>
        <source>Limits cleared</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="534"/>
        <source>Goto reference position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="536"/>
        <source>Goto reference position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="557"/>
        <source>Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="564"/>
        <source>Operation aborted</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="547"/>
        <source>Reference position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="553"/>
        <source>Goto initial position...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="557"/>
        <source>Goto initial position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="568"/>
        <source>Initial position reached</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="621"/>
        <source>Yaw corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="628"/>
        <source>Pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="635"/>
        <source>Yaw corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="642"/>
        <source>Pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="674"/>
        <source>Reference set at current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="735"/>
        <source>Yaw/pitch corner 0 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="743"/>
        <source>Yaw/pitch corner 1 set from current position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="756"/>
        <source>Field of view set to user value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="769"/>
        <source>Number of pictures set to user value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="774"/>
        <source>Opening plugins dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="793"/>
        <source>Opening configuration dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="828"/>
        <source>Opening shoot dialog. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="877"/>
        <source>Can&apos;t import preset file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="895"/>
        <source>Can&apos;t load style sheet</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="937"/>
        <source>Starting connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="956"/>
        <source>Connection started</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="961"/>
        <source>Connection failed to start</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="975"/>
        <source>Stopping connection. Please wait...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/mainController.py" line="988"/>
        <source>Connection stopped</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="23"/>
        <source>Papywizard</source>
        <translation>Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="60"/>
        <source>Move</source>
        <translation>Posun</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="933"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="949"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1057"/>
        <source>--</source>
        <translation>--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="312"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="348"/>
        <source>Configure...</source>
        <translation>Nastavit...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="371"/>
        <source>Shoot...</source>
        <translation>Fotografovat...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="438"/>
        <source>Mosaic</source>
        <translation>Mosaika</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="484"/>
        <source>Corner 0 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="538"/>
        <source>Corner 1 (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="589"/>
        <source>Total fov (°)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="646"/>
        <source>Nb picts</source>
        <translation>Počet obrázků</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="703"/>
        <source>Real overlap (%)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="766"/>
        <source>Resolution (px)</source>
        <translation>Rozlišení (px)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="830"/>
        <source>Preset</source>
        <translation>Předvolba</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="849"/>
        <source>Name</source>
        <translation>Název</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="893"/>
        <source>Be sure that the preset used is compatible with your camera and lens size (collision).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="919"/>
        <source>Timelapse</source>
        <translation>Časosběrné</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="965"/>
        <source>Start (°)</source>
        <translation>Začátek (°)</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="1019"/>
        <source>End (°)</source>
        <translation>Konec (°)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1100"/>
        <source>File</source>
        <translation>Soubor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1109"/>
        <source>Hardware</source>
        <translation>Zařízení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1113"/>
        <source>Set Limit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1132"/>
        <source>Help</source>
        <translation>Nápověda
</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1156"/>
        <source>Quit</source>
        <translation>Ukončit</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1159"/>
        <source>Ctrl+Q</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1168"/>
        <source>Import Preset File...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1176"/>
        <source>Connect...</source>
        <translation>Připojit...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1185"/>
        <source>Clear Limits</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1194"/>
        <source>Yaw -</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1203"/>
        <source>Yaw +</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1212"/>
        <source>Pitch +</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1221"/>
        <source>Pitch -</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1230"/>
        <source>Manual</source>
        <translation>Ručně</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1239"/>
        <source>View Log...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1248"/>
        <source>About Papywizard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1257"/>
        <source>About Qt</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1266"/>
        <source>Load Style Sheet...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1275"/>
        <source>Goto Reference...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1284"/>
        <source>Goto Initial...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/mainWindow.ui" line="1293"/>
        <source>Plugins...</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="1302"/>
        <source>+360°</source>
        <translation>+360°</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/mainWindow.ui" line="1311"/>
        <source>-360°</source>
        <translation>-360°</translation>
    </message>
</context>
<context>
    <name>MerlinOrionAxisController</name>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="482"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="483"/>
        <source>Alternate drive</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/merlinOrionPlugins.py" line="485"/>
        <source>Inertia angle</source>
        <translation type="unfinished">Neutrální úhel</translation>
    </message>
</context>
<context>
    <name>PixOrbAxisController</name>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="403"/>
        <source>Speed table index</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="405"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pixOrbPlugins.py" line="406"/>
        <source>Axis with break</source>
        <translation>Osa s brzdou</translation>
    </message>
</context>
<context>
    <name>PluginsController</name>
    <message>
        <location filename="papywizard/controller/pluginsController.py" line="203"/>
        <source>Can&apos;t scan bluetooth</source>
        <translation>Nemohu prohledat bluetooth</translation>
    </message>
</context>
<context>
    <name>PololuServoAxisController</name>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="94"/>
        <source>forward</source>
        <translation>vpřed</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="95"/>
        <source>reverse</source>
        <translation>zpět</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="443"/>
        <source>Speed</source>
        <translation>Rychlost</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="445"/>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="446"/>
        <source>Channel</source>
        <translation>Kanál</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="449"/>
        <source>Direction</source>
        <translation>Směr</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="451"/>
        <source>Angle for 1ms</source>
        <translation>Úhel za 1 ms</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="453"/>
        <source>Neutral position</source>
        <translation>Neutrální pozice</translation>
    </message>
</context>
<context>
    <name>PololuServoShutterController</name>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="510"/>
        <source>Servo</source>
        <translation>Servo</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="511"/>
        <source>Channel</source>
        <translation>Kanál</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="513"/>
        <source>Value off</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/pololuServoPlugins.py" line="515"/>
        <source>Value on</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ShootController</name>
    <message>
        <location filename="papywizard/controller/shootController.py" line="387"/>
        <source>Step</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="458"/>
        <source>Resume</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="471"/>
        <source>Pause</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="462"/>
        <source>Paused</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="483"/>
        <source>Finished</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="485"/>
        <source>Canceled</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="487"/>
        <source>Failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="489"/>
        <source>Finish</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="494"/>
        <source>Waiting</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="540"/>
        <source>Moving</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="542"/>
        <source>Stabilization</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="544"/>
        <source>Mirror lockup</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="547"/>
        <source>Shutter - Picture</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="588"/>
        <source>Idle</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/controller/shootController.py" line="678"/>
        <source>Stop</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Shooting</name>
    <message>
        <location filename="papywizard/model/shooting.py" line="548"/>
        <source>Shutter failed while mirror locking up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/model/shooting.py" line="563"/>
        <source>Shutter failed while shooting</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SimulationAxisController</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="220"/>
        <source>Speed</source>
        <translation>Rychlost</translation>
    </message>
</context>
<context>
    <name>SimulationShutterController</name>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="265"/>
        <source>Time value</source>
        <translation type="unfinished">Čas</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="267"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/simulationPlugins.py" line="269"/>
        <source>Bracketing nb picts</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>StandardShutterPluginController</name>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="63"/>
        <source>Time value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="65"/>
        <source>Mirror lockup</source>
        <translation>Předsklopení zrcátka</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="67"/>
        <source>Bracketing nb picts</source>
        <translation>Počet obrázků při braketingu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="69"/>
        <source>Hard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="70"/>
        <source>Pulse width high</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/standardShutterPluginController.py" line="72"/>
        <source>Pulse width low</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TimelordShutterController</name>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="125"/>
        <source>Program path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/timelordPlugins.py" line="127"/>
        <source>LRD file path</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>UrsaMinorBt2ShutterController</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="153"/>
        <source>Focus</source>
        <translation>Ostření</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="154"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="156"/>
        <source>Pulse width</source>
        <translation>Délka pulsu</translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorBt2Plugins.py" line="158"/>
        <source>Maintain focus</source>
        <translation>Zachová zaostření</translation>
    </message>
</context>
<context>
    <name>UrsaMinorUsbShutterController</name>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="116"/>
        <source>Trigger line</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/plugins/ursaMinorUsbPlugins.py" line="118"/>
        <source>Line inverted</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>WarningMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="100"/>
        <source>Warning</source>
        <translation>Varování</translation>
    </message>
</context>
<context>
    <name>YesNoMessageDialog</name>
    <message>
        <location filename="papywizard/view/messageDialog.py" line="129"/>
        <source>Question</source>
        <translation>Dotaz</translation>
    </message>
</context>
<context>
    <name>bluetoothChooserDialog</name>
    <message>
        <location filename="papywizard/view/ui/bluetoothChooserDialog.ui" line="14"/>
        <source>Bluetooth Chooser</source>
        <translation>Výběr Bluetooth</translation>
    </message>
</context>
<context>
    <name>configDialog</name>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="17"/>
        <source>Configuration</source>
        <translation>Nastavení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="37"/>
        <source>Shooting</source>
        <translation>Fotografování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="45"/>
        <source>Head orientation</source>
        <translation>Orientace hlavy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="62"/>
        <source>up</source>
        <translation>nahoru</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="67"/>
        <source>left</source>
        <translation>doleva</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="72"/>
        <source>right</source>
        <translation>doprava</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="77"/>
        <source>down</source>
        <translation>dolů</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="85"/>
        <source>Camera orientation</source>
        <translation>Orientace fotoaparátu</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="102"/>
        <source>portrait</source>
        <translation>portrét</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="107"/>
        <source>landscape</source>
        <translation>krajina</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="112"/>
        <source>custom</source>
        <translation>jiné</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/configDialog.ui" line="123"/>
        <source> °</source>
        <translation> °</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="139"/>
        <source>Stabilization delay</source>
        <translation>Čas pro stabilizaci</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="152"/>
        <source> s</source>
        <translation> s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="174"/>
        <source>Mosaic</source>
        <translation>Mozaika</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="182"/>
        <source>Overlap</source>
        <translation>Překryv</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="195"/>
        <source> %</source>
        <translation> %</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="217"/>
        <source>Start from</source>
        <translation>Začít od</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="237"/>
        <source>top-left</source>
        <translation>levý horní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="242"/>
        <source>top-right</source>
        <translation>pravý horní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="247"/>
        <source>bottom-left</source>
        <translation>levý dolní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="252"/>
        <source>bottom-right</source>
        <translation>pravý dolní</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="260"/>
        <source>Initial direction</source>
        <translation>Výchozí zaměření</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="277"/>
        <source>yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="282"/>
        <source>pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="290"/>
        <source>CR</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="300"/>
        <source>Camera/lens</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="308"/>
        <source>Lens (type, focal)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="325"/>
        <source>rectilinear</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="330"/>
        <source>fisheye</source>
        <translation>rybí oko</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="338"/>
        <source>Optical multiplier</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="351"/>
        <source>Sensor resolution</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="464"/>
        <source> x</source>
        <translation> x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="386"/>
        <source>Sensor (coef, ratio)</source>
        <translation>Snímač(ořez, poměr)</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="403"/>
        <source>3:2</source>
        <translation></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="408"/>
        <source>4:3</source>
        <translation>4:3</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="413"/>
        <source>5:4</source>
        <translation>5:4</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="418"/>
        <source>16:9</source>
        <translation>16:9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="426"/>
        <source> Mpx</source>
        <translation>Mpx</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="442"/>
        <source> mm</source>
        <translation> mm</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="489"/>
        <source>Plugins</source>
        <translation>Rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="497"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="510"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="561"/>
        <source>Configure...</source>
        <translation>Nastavit...</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="537"/>
        <source>Shutter</source>
        <translation>Spoušť</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="641"/>
        <source>Data</source>
        <translation>Soubory</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="649"/>
        <source>Data directory</source>
        <translation>Výchozí adresář</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="665"/>
        <source>Data file</source>
        <translation>Soubor</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="681"/>
        <source>%(date_time)s_%(mode)s</source>
        <translation type="unfinished">%(datum)s_%(režim)s</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="875"/>
        <source>Enable</source>
        <translation>Povoleno</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="704"/>
        <source>Title</source>
        <translation type="unfinished">Nadpis</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="733"/>
        <source>GPS</source>
        <translation>GPS</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="762"/>
        <source>Comment</source>
        <translation>Komentář</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="815"/>
        <source>Timer</source>
        <translation>Časovač</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="826"/>
        <source>Start after</source>
        <translation>Začít za</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="849"/>
        <source>Repeat</source>
        <translation>Opakovat</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="885"/>
        <source>Repeat every</source>
        <translation>Opakovat po</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="930"/>
        <source>HH:mm:ss</source>
        <translation>HH:mm:ss</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="943"/>
        <source>Reverse direction before repeat</source>
        <translation>Obrátit směr pře opakováním</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="953"/>
        <source>Misc</source>
        <translation>Pomocné</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="961"/>
        <source>Logger level</source>
        <translation>Množství hlášení</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="978"/>
        <source>trace</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="983"/>
        <source>debug</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="988"/>
        <source>info</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="993"/>
        <source>warning</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="998"/>
        <source>error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1003"/>
        <source>exception</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/configDialog.ui" line="1008"/>
        <source>critical</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>helpAboutDialog</name>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="14"/>
        <source>About Papywizard</source>
        <translation>Co je Papywizard</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="31"/>
        <source>General</source>
        <translation>Obecné</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="72"/>
        <source>Papywizard x.x.x</source>
        <translation>Papywizard x.x.x</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="84"/>
        <source>Papywizard is a panohead control software, mainly developped for the Merlin/Orion astronomic mount but usable for other panoheads.</source>
        <translation>Papywizard je nástroj pro kontrolu  panoramatických hlav, vyvýjený zejména pro použití astronomických montáží Merlin/Orion, ale využitelný i s jinými hlavami.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="108"/>
        <source>© 2007-2009 Frédéric Mantegazza</source>
        <translation>© 2007-2009 Frédéric Mantegazza</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="130"/>
        <source>http://www.papywizard.org</source>
        <translation>http://www.papywizard.org</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="146"/>
        <source>Credits</source>
        <translation>Autoři</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="189"/>
        <source>License</source>
        <translation>Licence</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="195"/>
        <source>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</source>
        <translation>This software is governed by the CeCILL license under French law and abiding by the rules of distribution of free software. You can  use, modify and/or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL http://www.cecill.info.

As a counterpart to the access to the source code and  rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty  and the software&apos;s author,  the holder of the economic rights,  and the successive licensors  have only  limited liability.

In this respect, the user&apos;s attention is drawn to the risks associated with loading,  using,  modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean  that it is complicated to manipulate,  and  that  also therefore means  that it is reserved for developers  and  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software&apos;s suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and,  more generally, to use and operate it in the same conditions as regards security.

The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you accept its terms.</translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/helpAboutDialog.ui" line="155"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:10pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Written by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (main core)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jones Henry Subbiah (EOS Utility plugin)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Translated by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (fr)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jo Lutum (de)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Maciej Dworak (pl)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Antonio Bruno (it)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Juan Carlos Andres (es)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Vaclav Cerny (cz)&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Graphics by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Hubert Pawlowski&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Packaged by:&lt;/span&gt;&lt;/p&gt;
&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Frédéric Mantegazza (linux, windows, maemo)&lt;/p&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Jeremy Pronk (MacOS)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>loggerDialog</name>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="13"/>
        <source>Logger</source>
        <translation>Sledování</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="144"/>
        <source>Clear log</source>
        <translation>Vymazat záznamy</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/loggerDialog.ui" line="151"/>
        <source>Save log</source>
        <translation>Uložit záznamy</translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="papywizard/scripts/main.py" line="219"/>
        <source>Plugins selection</source>
        <translation>Výběr rozšíření</translation>
    </message>
    <message>
        <location filename="papywizard/scripts/main.py" line="224"/>
        <source>Before you can use Papywizard, you must choose what plugins to use to control your hardware.

After closing this dialog, you will be prompt to select these plugins. Once it is done, you can configure them in the global Configuration dialog</source>
        <translation>Než budete moci začít používat Pappywizard, musíte vybrat, jak budete ovládat vaše zařízení.

Po zavření tohoto dialogu budete vyzváni k výběru těchto rozšíření. Jakmile to bude hotové, můžete je nastavit v hlavním dialogu Nastavení.</translation>
    </message>
</context>
<context>
    <name>nbPictsDialog</name>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="14"/>
        <source>Nb Picts</source>
        <translation>Počet obrázků</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/nbPictsDialog.ui" line="49"/>
        <source>Nb picts</source>
        <translation>Počet obrázků</translation>
    </message>
</context>
<context>
    <name>pluginConfigDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="14"/>
        <source>Plugin dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsConfigDialog.ui" line="34"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>preferencesDialog</name>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="43"/>
        <source>Plugins</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="51"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="71"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="87"/>
        <source>Shutter</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="145"/>
        <source>bluetooth</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="150"/>
        <source>serial</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="155"/>
        <source>ethernet</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="166"/>
        <source>Drivers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="174"/>
        <source>BT device address</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="199"/>
        <source>00:50:C2:58:55:B9</source>
        <translation>00:50:C2:58:55:B9</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="209"/>
        <source>Choose...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="219"/>
        <source>Serial port</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="235"/>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="248"/>
        <source>Ethernet host/port</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/pluginsDialog.ui" line="264"/>
        <source>locahost</source>
        <translation>locahost</translation>
    </message>
</context>
<context>
    <name>shootDialog</name>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="17"/>
        <source>Shooting</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="105"/>
        <source>Total</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="115"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="125"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="135"/>
        <source>Current</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="259"/>
        <source>--/--</source>
        <translation>--/--</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="199"/>
        <source>Next</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="341"/>
        <source>Idle</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="428"/>
        <source>00:00:00</source>
        <translation>00:00:00</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="471"/>
        <source>%p%</source>
        <translation>%p%</translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="511"/>
        <source>Data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="540"/>
        <source>Timer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="566"/>
        <source>Step-by-step</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="599"/>
        <source>Start</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="628"/>
        <source>Pause</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/shootDialog.ui" line="657"/>
        <source>Stop</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>totalFovDialog</name>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="14"/>
        <source>Total Fov</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="29"/>
        <source>Yaw</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="39"/>
        <source>Pitch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="49"/>
        <source>Total fov</source>
        <translation type="unfinished"></translation>
    </message>
    <message utf8="true">
        <location filename="papywizard/view/ui/totalFovDialog.ui" line="69"/>
        <source> °</source>
        <translation> °</translation>
    </message>
</context>
</TS>
